### ISSUE TITLE
Concurrency issue in ReplaySubject

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJava#1025]
In our testing we've seen a few ArrayIndexOutOfBoundsExceptions in the replay subject. 

```
Observable OnError
java.lang.IndexOutOfBoundsException: Index: 272, Size: 272
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    at java.util.ArrayList.get(ArrayList.java:411)
    at rx.subjects.ReplaySubject.replayObserverFromIndex(ReplaySubject.java:198)
    at rx.subjects.ReplaySubject.access$000(ReplaySubject.java:52)
    at rx.subjects.ReplaySubject$1.call(ReplaySubject.java:74)
    at rx.subjects.ReplaySubject$1.call(ReplaySubject.java:69)
    at rx.subjects.SubjectSubscriptionManager$1.call(SubjectSubscriptionManager.java:54)
    at rx.subjects.SubjectSubscriptionManager$1.call(SubjectSubscriptionManager.java:48)
```

**Comment by tir38** [comment]
If you got here looking for an answer, read more in this issue: https://github.com/ReactiveX/RxJava/issues/1029
