### ISSUE TITLE
Test isolation problem

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#1624]
```NewThreadSchedulerTest``` fails 9 out of 10 runs on my laptop when I run the unit test suite but passes every time if run individually.

Stack trace of failing test:
```java
java.lang.AssertionError: expected:<2> but was:<4>
at rx.schedulers.AbstractSchedulerConcurrencyTests.testUnSubscribeForScheduler(AbstractSchedulerConcurrencyTests.java:107)
```

I've dumped the thread stack traces at the start of the test in question and it appears that ```OperatorParallelTest``` is still busy, being mentioned in 4 threads. See one example at the bottom of this post.

So the issue I want to raise is that tests of asynchronous code are not releasing resources effectively so that a following unit test that relies on timing can proceed deterministically.

In particular I think that 

* ```OperatorParallelTest``` should release its resources after completion so that the behaviour I'm seeing is fixed. Would someone like to have a go at it?
*  Strategies for test isolation could be discussed further, for example enabling such isolation in the Scheduler API

What do you think?

```
RxComputationThreadPool-3
java.lang.Thread.sleep(Native Method)
rx.internal.operators.OperatorParallelTest$10$1.call(OperatorParallelTest.java:210)
rx.internal.operators.OperatorParallelTest$10$1.call(OperatorParallelTest.java:1)
rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
rx.internal.operators.NotificationLite.accept(NotificationLite.java:147)
rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:169)
rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$0(OperatorObserveOn.java:158)
rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:151)
rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:43)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```

**Comment by akarnokd** [comment]
Do you still experience this failure?

**Comment by davidmoten** [comment]
Not this one, no. OperatorParallelTest is gone now but the issue of tests being able to affect other tests (especially those relying on timeouts) due to async work continuing on Schedulers after a test has finished is probably still around and I imagine may rear its head again. @akarnokd the Scheduler.reset() work would be useful in this regard if it does happen again, assuming that the Scheduler.reset() work has gotten into the codebase (?). 

By the way I did get a test failure on my 5 year old 2 core laptop when I checked running all tests in Eclipse but I'll raise it as a separate issue.

**Comment by davidmoten** [comment]
ah, hold your horses. The latest failure is another example of a test isolation issue. The test passes every time if run alone but fails if run in the suite (I'll check with what frequency).

```
java.lang.AssertionError: expected:<257> but was:<256>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at rx.internal.operators.OperatorMergeTest.testBackpressureUpstream2(OperatorMergeTest.java:651)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by davidmoten** [comment]
OperatorMergeTest.testBackpressureUpstream2 fails 2 out of 3 times when running the whole suite in Eclipse.

**Comment by davidmoten** [comment]
The test ```OperatorMergeTest.testBackpressureUpstream2``` makes use of ```Schedulers.computation``` and only fails when other tests have run before it (presumably async work is taking place still once this test starts). To clarify what I mean with ```Scheduler.reset()```, what I'd hope is that when a test like the one in question makes use of an async ```Scheduler``` we should be able to ensure test isolation by starting the test with a call to ```Schedulers.computation().reset()```. This would ensure that any outstanding work on the computation Scheduler completed before the test gets going. Do you think this is a valid approach @akarnokd @zsxwing @benjchristensen?

**Comment by benjchristensen** [comment]
reset() may be sufficient. Or we should ensure that we're not letting things run async in the background and that tests must wait for all work to finish. The fact this is happening suggests we are allowing tests to finish prematurely. The reset() thing seems to bandage over the real issue.

**Comment by davidmoten** [comment]
Yep I agree. It would be nice to ensure tests clean up after themselves but
that seems like a big ask to review all existing tests for possible async
leftovers (or just uniformly put a reset() at the end of each test!). It
might be easier to apply the reset() bandaid reactively at the start of
non-deterministic tests as they turn up. Dunno.

**Comment by akarnokd** [comment]
On one time, I've created a small utility method that takes the computation scheduler, asks for ```availableProcessor()``` number of workers, issues a task to each and waits 1s to get a response. This should detect obstruction. Another option is to get all Threads and see if we detect unrecognized threads or leftover newthreads by their name.

**Comment by akarnokd** [comment]
The master now has the [TestObstructionDetection] class (https://github.com/ReactiveX/RxJava/blob/1.x/src/test/java/rx/test/TestObstructionDetection.java) which you can insert at various places to see if something hung in a computation scheduler.
