### ISSUE TITLE
OperatorRetryTest.testRetryWithBackpressure fails under load

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#1703]
If I run a build from Eclipse while my system is under load I get a random failure with the test method mentioned in the title. The stacktracetrace:

```
org.mockito.exceptions.verification.VerificationInOrderFailure: 
Verification in order failure:
observer.onError(<any>);
Wanted 0 times:
-> at rx.internal.operators.OperatorRetryTest.testRetryWithBackpressure(OperatorRetryTest.java:649)
But was 1 time. Undesired invocation:
-> at rx.observers.TestObserver.onError(TestObserver.java:62)

	at rx.internal.operators.OperatorRetryTest.testRetryWithBackpressure(OperatorRetryTest.java:649)
```

Output:
```
4 @ -4
Retry # 1
3 @ -4
Retry # 2
2 @ -4
Retry # 3
1 @ -4
Retry # 4
0 @ -8
```

**Comment by akarnokd** [comment]
The test has been fixed.
