### ISSUE TITLE
Non-deterministic test failure: OperatorObserveOnTest.testOnErrorCutsAheadOfOnNext

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#1737]
```java
rx.internal.operators.OperatorObserveOnTest > testOnErrorCutsAheadOfOnNext FAILED
    java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:400)
        at java.util.ArrayList.get(ArrayList.java:413)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1211)
        at rx.internal.operators.OperatorObserveOnTest.testOnErrorCutsAheadOfOnNext(OperatorObserveOnTest.java:650)
```

**Comment by akarnokd** [comment]
This test should no longer error out.
