### ISSUE TITLE
RxRingBuffer Concurrent Unsubscribe Non-ThreadSafe

### ISSUE THREAD

**Issue by laktech** [ReactiveX/RxJava#1845]
rx-java version 0.20.6

```
java.lang.NullPointerException
        at rx.internal.util.RxRingBuffer.poll(RxRingBuffer.java:282)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.drainAll(OperatorMerge.java:723)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.drainQueue(OperatorMerge.java:744)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.access$300(OperatorMerge.java:505)
        at rx.internal.operators.OperatorMerge$MergeSubscriber$1.call(OperatorMerge.java:376)
        at rx.internal.operators.OperatorMerge$MergeSubscriber$1.call(OperatorMerge.java:369)
        at rx.internal.util.IndexedRingBuffer.forEach(IndexedRingBuffer.java:281)
        at rx.internal.util.IndexedRingBuffer.forEach(IndexedRingBuffer.java:247)
        at rx.internal.util.SubscriptionIndexedRingBuffer.forEach(SubscriptionIndexedRingBuffer.java:131)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainChildrenQueues(OperatorMerge.java:331)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainQueuesIfNeeded(OperatorMerge.java:308)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.access$400(OperatorMerge.java:96)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:674)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:528)
        at rx.internal.operators.OperatorSubscribeOn$1$1$1.onNext(OperatorSubscribeOn.java:76)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:105)
        at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:96)
        at rx.internal.operators.OperatorSubscribeOn$1$1$1$1.request(OperatorSubscribeOn.java:88)
        at rx.Subscriber.setProducer(Subscriber.java:150)
        at rx.internal.operators.OperatorSubscribeOn$1$1$1.setProducer(OperatorSubscribeOn.java:81)
        at rx.Subscriber.setProducer(Subscriber.java:144)
        at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:47)
        at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
        at rx.Observable.subscribe(Observable.java:8680)
        at ********************
        at ********************
        at rx.Observable.unsafeSubscribe(Observable.java:8591)
        at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
        at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
        at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnable.exec(ForkJoinTask.java:1265)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:334)
        at java.util.concurrent.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:604)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:784)
        at java.util.concurrent.ForkJoinPool.work(ForkJoinPool.java:646)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:398)
```

**Comment by akarnokd** [comment]
Fixed in 1.0.5.
