### ISSUE TITLE
Non-deterministic test failure: OnSubscribeCacheTest.testWithBehaviorSubjectAndRepeat

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJava#2242]
This occurred while playing with RxRingBuffer. Not sure if it's RxRingBuffer that causes it, or it's just non-deterministic. I saw it fail once. 

```
java.lang.AssertionError: Value at index: 1 expected to be [1] (Integer) but was: [2] (Integer)
	at rx.observers.TestObserver.assertReceivedOnNext(TestObserver.java:126)
	at rx.observers.TestSubscriber.assertReceivedOnNext(TestSubscriber.java:164)
	at rx.internal.operators.OnSubscribeCacheTest.testWithCustomSubjectAndRepeat(OnSubscribeCacheTest.java:127)
	at rx.internal.operators.OnSubscribeCacheTest.testWithBehaviorSubjectAndRepeat(OnSubscribeCacheTest.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:62)
```

I will try replicating in a tight-loop in a bit and post here.

**Comment by benjchristensen** [comment]
Closing due to old age. I haven't seen this causing us issues.
