### ISSUE TITLE
Stack trace is opaque for IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by jondwillis** [ReactiveX/RxJava#2293]
This occurs when using RxAndroid 0.23.0/RxJava 1.0.0, please redirect me if this is not the most appropriate place for this.

There seem to be a several ways to cause the following exception, notably using observeOn() on a when there exists overproducing or underconsuming, and there is no clear association with client code:

```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:50)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5598)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: rx.exceptions.OnErrorNotImplementedException
       at rx.Observable$31.onError(Observable.java:7204)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:127)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:96)
       at rx.internal.operators.NotificationLite.accept(NotificationLite.java:147)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:177)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:45)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5598)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: rx.exceptions.MissingBackpressureException
       at rx.internal.util.RxRingBuffer.onNext(RxRingBuffer.java:222)
       at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceProducer.onNext(OnSubscribeCombineLatest.java:201)
       at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceRequestableSubscriber.onNext(OnSubscribeCombineLatest.java:252)
       at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:51)
       at rx.Scheduler$Worker$1.call(Scheduler.java:118)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:45)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

I'd like to strike up a discussion highlighting common causes on these backpressure exceptions, how to determine the source of them in client code, and finally how to improve the stacktrace.

**Comment by Diolor** [comment]
@benjchristensen Not sure if my suggestion is solid. I have seen the following above:

>I personally am researching solutions for stitching together artificial callstacks that show the actual user code instead of the JVM callstacks which show the Rx library, 

The problem I am facing right now is that somewhere there is not placed an onError so it causes the (android) program to crash. It would be very helpful to see the codeline of the original Action0 (or something similar) so we can easily locate the problem. Of course I do not know the implications of the whole JVM - as you say above.

**Comment by benjchristensen** [comment]
We are actively exploring this space, but nothing usable yet. Also, it is only for the Hotspot/OpenJDK/Oracle JVMs that we are pursuing anything right now. I don't know what the options are for Android. 

Just the other day I saw some native C code via native plugins and also via JNI allowing a logical callstack across async boundaries. Performance is still an issue though. Beyond that I don't have much further to offer as a solution at this time.

We still use println logging (via `doOnEach`, `doOnNext`, `doOnSubscribe`, `doOnUnsubscribe`, `doOnRequest`, etc) for our debugging today at Netflix.

**Comment by zhihuitang** [comment]
Hi @benjchristensen , I did register a global error handler in Application, but the exception:
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

did I do something wrong? thanks.
here is my code
> public class WrapperApplication extends MultiDexApplication {
> 
>     @Override
>     public void onCreate() {
>         super.onCreate();
>        
>         RxJavaPlugins.getInstance().registerErrorHandler(new ErrorHandler(this));
> 
>     }
> 
> }
> 
> public class ErrorHandler extends RxJavaErrorHandler {
>     Context context;
>     public ErrorHandler(Context context) {
>         this.context = context;
>     }
> 
>     @Override
>     public void handleError(Throwable e) {
>         e.printStackTrace();
>         if (context != null) {
>             Toast.makeText(context,
>                     "Unexpected error happened",
>                     Toast.LENGTH_LONG).show();
>         }
>     }
> }
>

**Comment by corlaez** [comment]
I am toying with RxJava and I had this issue as well. I think ReactiveX should be very careful to explain the difference between Observable.doOnError (side effect, will still blow up) and Subscriber.onError (last consumer, if handled here your error won't pop anymore. At least that was my problem. https://twitter.com/Corlaez/status/782023068793339904

**Comment by zmin666** [comment]
maybe callback run in wrong thread.
i just meet the problem, and solve it.

**Comment by gubo** [comment]
it occurs to me that Action1<> can be dangerous to use, given that Observable.subscribe will throw unchecked exception in onError ... ex:

```        
final rx.plugins.RxJavaErrorHandler rxJavaErrorHandler = new rx.plugins.RxJavaErrorHandler() {
            @Override
            public void handleError( final Throwable x ) {
                System.out.println( "rxJavaErrorHandler.handleError: " + x.getClass().getSimpleName() );
            }
        };
        rx.plugins.RxJavaPlugins.getInstance().registerErrorHandler( rxJavaErrorHandler );

        final rx.functions.Action1<Long> action = new rx.functions.Action1<Long>() {
            @Override
            public void call( final Long L ) {
                System.out.println( "tick" );
                try { Thread.sleep( 2500 ); } catch ( InterruptedException x ) {}
            }
        };

        final rx.Subscription subscription = rx.Observable.interval( 100L,TimeUnit.MILLISECONDS )
                .subscribeOn( rx.schedulers.Schedulers.io() )
                .observeOn( rx.schedulers.Schedulers.newThread() )
                .subscribe( action );
```

this code generates MissingBackpressureException, which propogates to OnErrorNotImplementedException then is wrapped in IllegalStateException ... but in ScheduledAction.run, calls `RxJavaPlugins.getInstance().getErrorHandler().handleError(ie);` and then regardless calls `thread.getUncaughtExceptionHandler().uncaughtException(thread, ie);`
to me this means you don't really get to "handle" the error in your registered RxJavaPlugins error handler. 
on android, this will kill the process.

**Comment by JakeWharton** [comment]
That seems normal. If you don't supply what is the reactive equivalent of a
catch block then the exception propagates resulting in app death. Supply an
error handler and the problem goes away.

**Comment by gubo** [comment]
but rx.plugins.RxJavaPlugins.getInstance().registerErrorHandler( rxJavaErrorHandler );
was my error handler.

if i put .doOnError( Action1<Throwable>... ) after .observeOn, it gets called but the chain
continues on to call the plugin errorhandler, then it calls the actual Subscriber that Observable creates to wrap the Action, and this then throws OnErrorNotImplementedException.

(if i subscribe on a SafeSubscriber, i.e. new rx.Observer<>... then there is not the problem ... problem is with subscribing with an Action1)

**Comment by akarnokd** [comment]
The problem is this:

> .subscribe( action );

You have to handle exception by consuming it via `subscribe`:

```java
.subscribe( action, error -> errorHandler(error) );
```

**Comment by DP0326** [comment]
I am trying a program in android studio which was provided by ResearchStack. I am acing the same error and I now I should use an Error Handler to solve this issue. But the RxJava program is an executable jar file of RxJava. So where can I add the error handler program?
