### ISSUE TITLE
Issue with amb operator

### ISSUE THREAD

**Issue by pradhakrishnan** [ReactiveX/RxJava#2537]
I am getting below error when i tried to get the value using toBlocking()
Error:
java.util.NoSuchElementException: Sequence contains no elements
	at rx.internal.operators.OperatorSingle$1.onCompleted(OperatorSingle.java:82)
	at rx.internal.operators.OperatorTake$1.onCompleted(OperatorTake.java:50)
	at rx.internal.operators.OnSubscribeAmb$AmbSubscriber.onCompleted(OnSubscribeAmb.java:297)
	at rx.internal.operators.OperatorFilter$1.onCompleted(OperatorFilter.java:42)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.onCompleted(OperatorSubscribeOn.java:66)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:42)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```
private Observable<RecordStatus> linearStatus = Observable.create();
private Observable<RecordStatus> nlvStatus = Observable.create();

if(LINEAR.equals(message)){
	linearStatus = getVideoStatusOnSubscribe(message);
}
if(NONLINEAR.equals(message)){
    nlvStatus = getVideoStatusOnSubscribe(message);
}

Observable<RecordStatus> obStatus = Observable.amb(linearStatus.subscribeOn(Schedulers.io()).filter(new Func1<RecordStatus, Boolean>() {

    @Override
    public Boolean call(RecordStatus t1) {
        return t1.equals(RecordStatus.CURRENT);
    }
}), nlvStatus.subscribeOn(Schedulers.io()).filter(new Func1<RecordStatus, Boolean>() {

    @Override
    public Boolean call(RecordStatus t1) {
        return t1.equals(RecordStatus.CURRENT);
    }
})
RecordStatus status = obStatus.toBlocking().first();

 private Observable<RecordStatus> getVideoStatusOnSubscribe(
    final String message) {
	return Observable.create(new OnSubscribe<RecordStatus>() {

    @Override
    public void call(Subscriber<? super RecordStatus> subscriber) {
        subscriber.onNext(restTemplate.postForObject(url, message, String.class););
        subscriber.onCompleted();
    }
});
}
```
Could someone please help me to fix this.

**Comment by akarnokd** [comment]
All of your sources where filterd to emptyness and first() expects at least a single value. You can use firstOrDefault instead to avoid the exception.

**Comment by pradhakrishnan** [comment]
It works, Thanks Akarnokd.

**Comment by pradhakrishnan** [comment]
Hi Akarnokd,
I have tried using that, some times it works, but most of the time it is giving default value.  Is there anything wrong in my code?

```
private Observable<RecordStatus> linearStatus = Observable.create();
private Observable<RecordStatus> nlvStatus = Observable.create();

if(LINEAR.equals(message)){
    linearStatus = getVideoStatusOnSubscribe(message);
}
if(NONLINEAR.equals(message)){
    nlvStatus = getVideoStatusOnSubscribe(message);
}

Observable<RecordStatus> obStatus = Observable.amb(linearStatus.subscribeOn(Schedulers.io()).filter(new Func1<RecordStatus, Boolean>() {

    @Override
    public Boolean call(RecordStatus t1) {
        return t1.equals(RecordStatus.CURRENT);
    }
}), nlvStatus.subscribeOn(Schedulers.io()).filter(new Func1<RecordStatus, Boolean>() {

    @Override
    public Boolean call(RecordStatus t1) {
        return t1.equals(RecordStatus.CURRENT);
    }
})
RecordStatus status = obStatus.toBlocking().firstOrDefalut(RecordStatus.DEFAULT);
System.out.println("Final status Status === "+status);

 private Observable<RecordStatus> getVideoStatusOnSubscribe(
    final String message) {
    return Observable.create(new OnSubscribe<RecordStatus>() {

    @Override
    public void call(Subscriber<? super RecordStatus> subscriber) {
        RecordStatus status = (RecordStatus) restTemplate.postForObject(url, message, String.class);
        logger.info("Thread "+ Thread.currentThread().getId() + " for "+ message
            			+ " giving status "+status);
        subscriber.onNext(status);
        subscriber.onCompleted();
    }
});
}

```

Output trace:

157 [2015-01-24 18:08:49,917] [main] WARN  com.umapranesh.sample.observable.asynceventhandler.GetVideoStatusEventHandler  - *****Status Event***** 
com.umapranesh.sample.observable.GetVideoStatusMessage
Final status Status === DEFAULT
Thread 10 for LINEAR giving status INVALID
Thread 11 for NONLINEAR giving status CURRENT

Thread 11 is giving the value what i expected, but before that observable returns the default value.
