### ISSUE TITLE
Questions about Zip operator

### ISSUE THREAD

**Issue by pradhakrishnan** [ReactiveX/RxJava#2588]
I have an issue with zip operator, I have few observables which execute asynchronously. And finally I am zipping all the results from each observable. It works fine, but sometime zip operator is waiting for long time to get the value from one of the observable.

```
 List<Observable<Set<Item>>> observableList = new ArrayList<Observable<Set<Item>>>();
for (ItemProvider ep : itemList) {
          ItemStrategy strategey = (ItemStrategy) ep.strategy();
          observableList.add(strategey.determineItems(message).subscribeOn(Schedulers.io()));
      }
 }

Set<Item> items = Observable.zip(observableList, new FuncN<Set<Item>>() {
  Set<Item> returnSet = new HashSet<Item>();

  @SuppressWarnings("unchecked")
  @Override
  public Set<Item> call(Object... args) {
      for (int i = 0; i < args.length; i++) {
        Set<Item> items = (Set<Item>) args[i];
          returnSet.addAll(items);
      }
      return returnSet;
  }
}).toBlocking().singleOrDefault(Collections.<Item> emptySet());

This is the code to get the items in Strategy class
@Override
    public Observable<Set<Item>> determineItems(final ItemsMessageExchange message) {
      return Observable.create(new OnSubscribe<Set<Item>>() {

            @Override
            public void call(Subscriber<? super Set<Item>> subscriber) {
                checkPreconditions(message);
                Set<Record> records = getRecordsOfQuery(message.toRecordQuery());
                Set<Item> items = new HashSet<Item>();
                for (Record record : records) {
                    try {
                        items.addAll(record.determineItems());
                    } catch (Exception ex) {
                        subscriber.onError(ex);
                    }
                }
                subscriber.onNext(items);
                subscriber.onCompleted();
            }

        });
    }
```
Can anyone help me to fix this.

**Comment by akarnokd** [comment]
Did you measure how long the ```getRecordsOfQuery``` takes?

**Comment by pradhakrishnan** [comment]
Yes, it is taking 95ms.

**Comment by akarnokd** [comment]
Does zip ever complete or just hangs?

**Comment by pradhakrishnan** [comment]
sometimes zip completes without any issue, sometime it is hanging.

**Comment by akarnokd** [comment]
Could you test something out? Put a return after ```subscriber.onError(ex);``` and see if it still hangs?

**Comment by pradhakrishnan** [comment]
Yes, I tried it still it hangs.

**Comment by akarnokd** [comment]
Found the bug and posted a fix. Could you verify if #2590 works for you?

**Comment by pradhakrishnan** [comment]
Sure, thanks Akarnokd. I will check and let you know.

**Comment by pradhakrishnan** [comment]
I have tried with that build, but still it hangs.

**Comment by akarnokd** [comment]
Could you post a unit test which demonstrates the problem?

**Comment by pradhakrishnan** [comment]
Hi Akarnokd,
I think the problem is with the determineItems method. Earlier it just returned Set<Item> but i changed to Observable<Set<Item>> ( Because I wanted to execute that in asynchronous and finally zip all the results). I just debugged using debug mode of eclipse the method getRecordsOfQuery() is gets hangs sometimes, not sure why. Most of the times it works fine. But sometimes it gets hangs there. 
Anything I did wrong in the above code?

Note : Without observable changes it works fine.

**Comment by akarnokd** [comment]
There is nothing wrong with the code above.

**Comment by pradhakrishnan** [comment]
When I Checked the Thread dump. One thread is waiting in Running state always and it happens on observable unsafeSubscribe. 
```
"RxCachedThreadScheduler-1" daemon prio=5 tid=0x00007fb1ec9bb800 nid=0xa103 runnable [0x0000000115eee000]
   java.lang.Thread.State: RUNNABLE
  at java.net.SocketInputStream.socketRead0(Native Method)
  at java.net.SocketInputStream.read(SocketInputStream.java:152)
  at java.net.SocketInputStream.read(SocketInputStream.java:122)
  at oracle.net.ns.Packet.receive(Unknown Source)
  at oracle.net.ns.DataPacket.receive(Unknown Source)
  at oracle.net.ns.NetInputStream.getNextPacket(Unknown Source)
  at oracle.net.ns.NetInputStream.read(Unknown Source)
  at oracle.net.ns.NetInputStream.read(Unknown Source)
  at oracle.net.ns.NetInputStream.read(Unknown Source)
  at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1104)
  at oracle.jdbc.driver.T4CMAREngine.unmarshalSB1(T4CMAREngine.java:1075)
  at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:480)
  at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
  at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
  at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10690)
  - locked <0x00000007b13c0988> (a oracle.jdbc.driver.T4CPreparedStatement)
  - locked <0x00000007b13147b0> (a oracle.jdbc.driver.T4CConnection)
  at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
  at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
  at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:266)
  at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:168)
  at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
  at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
  at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1027)
  at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:365)
  at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:137)
  at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:657)
  at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
  at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
  at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:387)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
  at com.sun.proxy.$Proxy114.entitlementRecordsOfQuery(Unknown Source)
  at com.umapranesh.service.DefaultEntitlementStrategy.getRecordsOfQuery(DefaultEntitlementStrategy.java:153)
  at com.umapranesh.service.DefaultEntitlementStrategy$1.call(DefaultEntitlementStrategy.java:71)
  at com.umapranesh.service.DefaultEntitlementStrategy$1.call(DefaultEntitlementStrategy.java:1)
  at rx.Observable.unsafeSubscribe(Observable.java:7326)
  at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)```
