### ISSUE TITLE
Observable hangs

### ISSUE THREAD

**Issue by pradhakrishnan** [ReactiveX/RxJava#2605]
This is the continuation of my old issue #2588 
 I took the Thread dump. One thread is in Running state always , This happens after i used Scheduler.io()
```
"RxCachedThreadScheduler-1" daemon prio=5 tid=0x00007fb1ec9bb800 nid=0xa103 runnable [0x0000000115eee000]
   java.lang.Thread.State: RUNNABLE
  at java.net.SocketInputStream.socketRead0(Native Method)
  at java.net.SocketInputStream.read(SocketInputStream.java:152)
  at java.net.SocketInputStream.read(SocketInputStream.java:122)
  at oracle.net.ns.Packet.receive(Unknown Source)
  at oracle.net.ns.DataPacket.receive(Unknown Source)
  at oracle.net.ns.NetInputStream.getNextPacket(Unknown Source)
  at oracle.net.ns.NetInputStream.read(Unknown Source)
  at oracle.net.ns.NetInputStream.read(Unknown Source)
  at oracle.net.ns.NetInputStream.read(Unknown Source)
  at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1104)
  at oracle.jdbc.driver.T4CMAREngine.unmarshalSB1(T4CMAREngine.java:1075)
  at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:480)
  at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
  at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
  at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10690)
  - locked <0x00000007b13c0988> (a oracle.jdbc.driver.T4CPreparedStatement)
  - locked <0x00000007b13147b0> (a oracle.jdbc.driver.T4CConnection)
  at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
  at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
  at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:266)
  at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:168)
  at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
  at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
  at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1027)
  at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:365)
  at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:137)
  at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:657)
  at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
  at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
  at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:387)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
  at com.sun.proxy.$Proxy114.entitlementRecordsOfQuery(Unknown Source)
  at com.umapranesh.service.DefaultEntitlementStrategy.getRecordsOfQuery(DefaultEntitlementStrategy.java:153)
  at com.umapranesh.service.DefaultEntitlementStrategy$1.call(DefaultEntitlementStrategy.java:71)
  at com.umapranesh.service.DefaultEntitlementStrategy$1.call(DefaultEntitlementStrategy.java:1)
  at rx.Observable.unsafeSubscribe(Observable.java:7326)
  at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by benjchristensen** [comment]
If it is hung, it is hung reading IO according to that stack:

> at java.net.SocketInputStream.socketRead0(Native Method)

What makes you think Rx has anything to do with the thread not completing while reading IO?

**Comment by akarnokd** [comment]
I'm closing this due to inactivity. If you have further questions, please don't hesitate to reopen this issue or post a new one.
