### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by VladDrake** [ReactiveX/RxJava#2651]
I' he downloaded your zip and followed steps for building and got error.
![default](https://cloud.githubusercontent.com/assets/2158923/6165526/6af4079a-b2b1-11e4-8da0-da2bf01c2dba.png)

**Comment by akarnokd** [comment]
```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'rxjava-project']
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:117)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:131)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:37)
        at org.gradle.api.Project$apply$0.call(Unknown Source)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_9a6lmk3rvf0u4oi9skiqtlo34.run(C:\Temp\rxjava\build.gradle:8)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
        ... 35 more
Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: C:\RxJava
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:575)
        at org.eclipse.jgit.api.Git.open(Git.java:113)
        at org.eclipse.jgit.api.Git.open(Git.java:97)
        at org.eclipse.jgit.api.Git$open.call(Unknown Source)
        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy:223)
        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy)
        at org.ajoberstar.grgit.Grgit$open.call(Unknown Source)
        at nebula.plugin.release.ReleasePlugin$_apply_closure2.doCall(ReleasePlugin.groovy:43)
        at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy:42)
        at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:107)
        at org.gradle.api.plugins.PluginContainer$apply.call(Unknown Source)
        at nebula.plugin.rxjavaproject.RxJavaReleasePlugin.apply(RxJavaReleasePlugin.groovy:20)
        at nebula.plugin.rxjavaproject.RxJavaReleasePlugin.apply(RxJavaReleasePlugin.groovy)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:107)
        at org.gradle.api.plugins.PluginContainer$apply.call(Unknown Source)
        at nebula.plugin.rxjavaproject.RxjavaProjectPlugin.apply(RxjavaProjectPlugin.groovy:80)
        at nebula.plugin.rxjavaproject.RxjavaProjectPlugin.apply(RxjavaProjectPlugin.groovy)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:115)
        ... 44 more
```

**Comment by VladDrake** [comment]
Hm, I saw it in stacktrace. How to solve it, any ideas?

It finds need jar in rep folder(from debug messages). For a test, I used "apply plugin: 'contacts'" (from the same rep) and hadn't applying error.

**Comment by zsxwing** [comment]
@VladDrake You can use git to clone the repo directly.

**Comment by akarnokd** [comment]
I'm closing this due to inactivity. If you have further questions, don't hesitate to reopen this issue or post a new one.
