### ISSUE TITLE
OperatorGroupBy throws "Group already existed while creating a new one"

### ISSUE THREAD

**Issue by jloisel** [ReactiveX/RxJava#2794]
We have encountered this exception while running a groupBy operator:
```
Error while observing HitSample java.lang.IllegalStateException: Group already existed while creating a new one
at rx.internal.operators.OperatorGroupBy$GroupBySubscriber.createNewGroup(OperatorGroupBy.java:308)
at rx.internal.operators.OperatorGroupBy$GroupBySubscriber.onNext(OperatorGroupBy.java:223)
at rx.internal.operators.OperatorGroupBy$GroupBySubscriber$2$2.onNext(OperatorGroupBy.java:286)
at rx.internal.operators.BufferUntilSubscriber.onNext(BufferUntilSubscriber.java:181)
at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
at rx.internal.operators.OperatorGroupBy$GroupBySubscriber.emitItem(OperatorGroupBy.java:338)
at rx.internal.operators.OperatorGroupBy$GroupBySubscriber.onNext(OperatorGroupBy.java:226)
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
at rx.subjects.PublishSubject.onNext(PublishSubject.java:114)
```

Our code does this:
```
subject
        .groupBy(person -> person.getFirstname())
        .flatMap(byFirstname -> byStart.groupBy(Person::getLastname))
        .flatMap(byLastname -> byLastname.buffer(30, SECONDS))
        .filter(buffer -> !buffer.isEmpty())
        .flatMap(buffer -> Observable.from(buffer).reduce(reducer));
```

When looking at the source code, it contains the following comment on this line:
```
 // this shouldn't happen (because we receive onNext sequentially) and would mean we have a bug
```

It happened only after a while with the code being running. Did not happen immediately. It sounds like a race condition.

RxJava version: 1.0.7

**Comment by jloisel** [comment]
Have just seen related issue #2791, i'm going to investigate if we have the same issue.

**Comment by jloisel** [comment]
Closing the issue, it's the same case. We're calling the subject concurrently from multiple threads. Going to wrap it with a SerializedSubject.
