### ISSUE TITLE
Improve defensive code in merge when onSubscribe function is null

### ISSUE THREAD

**Issue by YannRobert** [ReactiveX/RxJava#2848]
I get the following stacktrace in one of my test output.

```
java.lang.NullPointerException: null
	at rx.Observable.unsafeSubscribe(Observable.java:7495) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:215) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:185) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:120) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:96) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.Subscriber.setProducer(Subscriber.java:177) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:47) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.Observable.unsafeSubscribe(Observable.java:7495) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) ~[rxjava-1.0.8.jar:1.0.8]
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173) [rxjava-1.0.8.jar:1.0.8]
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99) [rxjava-1.0.8.jar:1.0.8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

I found it is because I am using the merge operator with a mocked Subject instance.

Please see the following gist that describe the problem.
https://gist.github.com/YannRobert/a07ed294dbaccd4c3705
If you run it, you will get the following stracktrace
```
java.lang.NullPointerException: null
	at rx.Observable.unsafeSubscribe(Observable.java:7495) [rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:215) [rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:185) [rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:120) [rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:96) [rxjava-1.0.8.jar:1.0.8]
	at rx.Subscriber.setProducer(Subscriber.java:177) [rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:47) [rxjava-1.0.8.jar:1.0.8]
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33) [rxjava-1.0.8.jar:1.0.8]
	at rx.Observable$1.call(Observable.java:144) [rxjava-1.0.8.jar:1.0.8]
	at rx.Observable$1.call(Observable.java:136) [rxjava-1.0.8.jar:1.0.8]
	at rx.Observable.subscribe(Observable.java:7585) [rxjava-1.0.8.jar:1.0.8]
	at rx.Observable.subscribe(Observable.java:7454) [rxjava-1.0.8.jar:1.0.8]
	at IssueInRxJavaDefensiveCodeTest.shouldThrowIllegalStateExceptionOnMockSubjectSubscribeByMerge(IssueInRxJavaDefensiveCodeTest.java:86) [test-classes/:na]
```

It seems that we could use some defensive code in the merge operator, that would detect and report this, so that's it's easier to find where the problem is.

**Comment by akarnokd** [comment]
Do you mean, for example, sending a NullPointerException via onError instead of throwing?

**Comment by YannRobert** [comment]
First, is that possible to throw an IllegalStateException or IllegalArgumentException? (instead of NPE) on Observable.java:7495 [rxjava-1.0.8.jar:1.0.8]
With a meaningfull description.

Also, the protected constructor of rx.Observable accepts null parameter. 
Is there any legitimate reason to pass null to this constructor? If not, an assertion in the constructor throwing an IllegalArgumentException may help. Otherwise, maybe document that null is a legal value.

Is that possible to throw an exception in the subscribe() [1] call stack? like this is done here [2] 

[1] https://gist.github.com/YannRobert/a07ed294dbaccd4c3705#file-issueinrxjavadefensivecodetest-java-L86
[2] https://gist.github.com/YannRobert/a07ed294dbaccd4c3705#file-issueinrxjavadefensivecodetest-java-L55

**Comment by akarnokd** [comment]
Traditionally, we throw/send NPEs.

**Comment by akarnokd** [comment]
The merge operator in 1.0.14 skips `null` `Observable`s values. I'm closing this due to inactivity.
