### ISSUE TITLE
Using merge() with throttleWithTimeout() leads to MissingBackpressureException

### ISSUE THREAD

**Issue by marshallpierce** [ReactiveX/RxJava#2850]
Repro: https://bitbucket.org/marshallpierce/rxjava-merge-backpressure

In text, here's what I'm doing: I have two observables: `Observable.never()`, and another that emits every 200ms. I `merge()` those two and `throttleWithTimeout()` the result with a long timeout. In a few seconds, I'll get this:

```
rx.exceptions.MissingBackpressureException
	at rx.internal.util.RxRingBuffer.onNext(RxRingBuffer.java:349)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.enqueue(OperatorMerge.java:721)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:698)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:586)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:114)
	at org.mpierce.rxjava.merge.ExperimentMain.lambda$main$0(ExperimentMain.java:25)
	at org.mpierce.rxjava.merge.ExperimentMain$$Lambda$1/1685538367.call(Unknown Source)
	at rx.Scheduler$Worker$1.call(Scheduler.java:120)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Instead, I would expect that the combo of merge & throttle should simply result in throttle working as expected (never emitting, in this case).

**Comment by marshallpierce** [comment]
Inserting a PublishSubject between the merge and throttle calls leads to normal operation (no backpressure exception).

**Comment by dlew** [comment]
I've been looking into this with Marshall, here's some more oddities:

```
Observable.interval(200, MILLISECONDS)
    .mergeWith(Observable.just(500L))
    .debounce(500, MILLISECONDS)
    .observeOn(Schedulers.newThread())
    .subscribe(
        (i) -> System.out.println("Got " + i),
        (t) -> {
            t.printStackTrace();
        }
    );
```

If you remove mergeWith, debounce, or observeOn, it works fine. All three are needed to create a failure situation.

What's weirder is that, given the 200ms interval but 500ms debounce, the subscriber should basically never get onNext (by my understanding). Yet it actually does start to emit items (before the backpressure error kicks in).

**Comment by dlew** [comment]
Oh, and one other thing: I tried using an `DebugHook` from RxJavaDebug to look into the situation, but with the hook attached it worked fine, which mystifies me further.

**Comment by zsxwing** [comment]
Could you test #2851?

**Comment by marshallpierce** [comment]
The change in #2851 prevents the error I'm seeing.

**Comment by zsxwing** [comment]
@marshallpierce thanks for confirming it.

**Comment by yogurtearl** [comment]
@benjchristensen can we get #2851  into v 1.0.9 . :)

**Comment by zsxwing** [comment]
@yogurtearl merged.
