### ISSUE TITLE
Non-deterministic test: OnSubscribeCombineLatestTest.testWithCombineLatestIssue1717

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2869]
I put ```./gradlew clean test``` into a loop and got a faiure on second run in ```OnSubscribeCombineLatestTest.testWithCombineLatestIssue1717```:

```
java.lang.AssertionError: expected:<2000> but was:<2002>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.junit.Assert.assertEquals(Assert.java:456)
	at rx.internal.operators.OnSubscribeCombineLatestTest.testWithCombineLatestIssue1717(OnSubscribeCombineLatestTest.java:852)
```

**Comment by benjchristensen** [comment]
Closing due to age. If this is still happening comment here and ask me to re-open.
