### ISSUE TITLE
Non-deterministic test: OperatorSerializeTest.testMultiThreadedWithNPEinMiddle

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2870]
Took ~5 loops of ```./gradlew clean test``` to show itself:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at rx.internal.operators.OperatorSerializeTest.testMultiThreadedWithNPEinMiddle(OperatorSerializeTest.java:134)
```

**Comment by benjchristensen** [comment]
Looks fixed in merged PRs.
