### ISSUE TITLE
Non-deterministic test: OperatorGroupByTest.testGroupByBackpressure

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2879]
Happened on 12th run of full test suite (after I ```@Ignore```d the other reported offenders)
```
java.lang.RuntimeException: Unexpected onError events: 1
	at rx.observers.TestSubscriber.assertNoErrors(TestSubscriber.java:195)
	at rx.internal.operators.OperatorGroupByTest.testGroupByBackpressure(OperatorGroupByTest.java:1072)
```

**Comment by akarnokd** [comment]
What was the exception exactly?

**Comment by davidmoten** [comment]
Ah I see. I'll try and reproduce to get that detail.

**Comment by benjchristensen** [comment]
Closing due to age.
