### ISSUE TITLE
Non-deterministic test: OperatorMergeMaxConcurrentTest.testSimpleAsyncLoop

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2916]
Have only seen this running the full test suite. Can't duplicate in ten runs of all tests in `OperatorMergeMaxConcurrentTest`
```
java.lang.AssertionError: expected:<[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]> but was:<[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18]>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:147)
	at rx.internal.operators.OperatorMergeMaxConcurrentTest.testSimpleAsync(OperatorMergeMaxConcurrentTest.java:216)
	at rx.internal.operators.OperatorMergeMaxConcurrentTest.testSimpleAsyncLoop(OperatorMergeMaxConcurrentTest.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:62)
```

**Comment by benjchristensen** [comment]
Closing due to age.
