### ISSUE TITLE
Test failure: testGroupsWithNestedSubscribeOn 

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#2946]
```
rx.internal.operators.OperatorGroupByTest > testGroupsWithNestedSubscribeOn FAILED
    java.lang.AssertionError: expected:<4> but was:<3>
        at org.junit.Assert.fail(Assert.java:93)
        at org.junit.Assert.failNotEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:128)
        at org.junit.Assert.assertEquals(Assert.java:472)
        at org.junit.Assert.assertEquals(Assert.java:456)
        at rx.internal.operators.OperatorGroupByTest.testGroupsWithNestedSubscribeOn(
             OperatorGroupByTest.java:915)
```

**Comment by benjchristensen** [comment]
Closing due to age. Reopen if still needed.

**Comment by benjchristensen** [comment]
Reopening as this may be recent enough. Put in the 1.x backlog.

**Comment by akarnokd** [comment]
`groupBy` has been rewritten and doesn't seem to produce this error anymore.
