### ISSUE TITLE
Thread safety question

### ISSUE THREAD

**Issue by davidmoten** [ReactiveX/RxJava#2994]
When we include state in a `Subscriber` subclass my understanding is that we don't need to make that state volatile, that visiblity issues are handled somewhere for the `onNext`, `onComplete`, `onError` calls but I'm not sure where. 

For example I can make a stream switch threads for the `onNext` call using `concat` as below and the dumped stack trace is below it. What I can't see is that the field `count` has been synchronized between the changeover of threads. What is the explanation for this one?

```java
public static void main(String[] args) throws InterruptedException {
        final CountDownLatch latch = new CountDownLatch(1);
        Observable<Long> o = Observable.interval(100, TimeUnit.MILLISECONDS).take(1);
        Observable.concat(o,o).subscribe(new Subscriber<Long>() {

            int count = 0;
            
            @Override
            public void onCompleted() {
                latch.countDown();
            }

            @Override
            public void onError(Throwable e) {
                
            }

            @Override
            public void onNext(Long t) {
                count += 1;
                System.out.println(Thread.currentThread().getName() + " " + count);
                Thread.currentThread().dumpStack();
            }});
        latch.await();
    }
```

Output:
```
RxComputationThreadPool-1 1
RxComputationThreadPool-2 2
```

Thread dump at `subscriber.onNext`:
```
at com.github.davidmoten.rx.testing.TestingHelperConcatTest$2.onNext(TestingHelperConcatTest.java:63)
	at com.github.davidmoten.rx.testing.TestingHelperConcatTest$2.onNext(TestingHelperConcatTest.java:1)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
	at rx.observers.SerializedObserver.onNext(SerializedObserver.java:159)
	at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
	at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onNext(OperatorConcat.java:211)
	at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:67)
	at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:51)
	at rx.Scheduler$Worker$1.call(Scheduler.java:120)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by akarnokd** [comment]
There is a ```synchronized``` block or an atomic write operation after the calls to onXXX which flush the write buffer (release). Before an onXXX is called, there is another ```synchronized``` block or atomic read/write which forces the re-read of field values after it. Since onXXX are always called between these elements, there are no visibility issues between subsequent calls.

**Comment by davidmoten** [comment]
Thanks @akarnokd, so a synchronized read/write in `SerializedSubscriber` cascades synchronization to the fields of its final members (`actual`) and so on till we get to the `count` field?

**Comment by akarnokd** [comment]
Think of these blocks as commits to a transaction. Everything written before will be visible to subsequent reads.

**Comment by davidmoten** [comment]
I'm browsing JSR-133 and haven't spotted yet how the scope of the `synchronized` block visiblity guarantees extends down to the objects in a chain of final fields. Do you have a favourite reference for this sort of stuff?

**Comment by davidmoten** [comment]
`happens-before` seems to cover it. For every article I read I have more unanswered questions. Plenty more reading to come it seems. Thanks for your input.
