### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by lqcamen** [ReactiveX/RxJava#3072]
![p d5 21h y yjtt zx 0](https://cloud.githubusercontent.com/assets/6939010/8633117/5cfff440-27ec-11e5-9608-359baa9a25f0.jpg)
I use git to clone this project and when I try to execute "./gradlew build", something went wrong and I got an error. What should I do to fix it?

**Comment by akarnokd** [comment]
Could you post the entire output?

**Comment by lqcamen** [comment]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Process 'Gradle Test Executor 161' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 161' fi
nished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
rmalExitValue(DefaultExecHandle.java:365)
        at org.gradle.process.internal.DefaultWorkerProcess.onProcessStop(Defaul
tWorkerProcess.java:91)
        at org.gradle.process.internal.DefaultWorkerProcess.access$000(DefaultWo
rkerProcess.java:35)
        at org.gradle.process.internal.DefaultWorkerProcess$1.executionFinished(
DefaultWorkerProcess.java:57)
        at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:24)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:83)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocat
ionHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy50.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(Default
ExecHandle.java:213)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHan
dle.java:310)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunn
er.java:100)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.jav
a:80)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
                                                                               C
ould not write standard input into: Gradle Test Executor 162.
java.io.IOException: 管道正在被关闭。
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82
)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOu
tputHandleRunner.java:50)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Process 'Gradle Test Executor 162' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 162' fi
nished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
rmalExitValue(DefaultExecHandle.java:365)
        at org.gradle.process.internal.DefaultWorkerProcess.onProcessStop(Defaul
tWorkerProcess.java:91)
        at org.gradle.process.internal.DefaultWorkerProcess.access$000(DefaultWo
rkerProcess.java:35)
        at org.gradle.process.internal.DefaultWorkerProcess$1.executionFinished(
DefaultWorkerProcess.java:57)
        at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:24)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:83)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocat
ionHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy50.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(Default
ExecHandle.java:213)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHan
dle.java:310)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunn
er.java:100)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.jav
a:80)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
                                                                               C
ould not write standard input into: Gradle Test Executor 163.
java.io.IOException: 管道正在被关闭。
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82
)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOu
tputHandleRunner.java:50)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Process 'Gradle Test Executor 163' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 163' fi
nished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
rmalExitValue(DefaultExecHandle.java:365)
        at org.gradle.process.internal.DefaultWorkerProcess.onProcessStop(Defaul
tWorkerProcess.java:91)
        at org.gradle.process.internal.DefaultWorkerProcess.access$000(DefaultWo
rkerProcess.java:35)
        at org.gradle.process.internal.DefaultWorkerProcess$1.executionFinished(
DefaultWorkerProcess.java:57)
        at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:24)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:83)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocat
ionHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy50.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(Default
ExecHandle.java:213)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHan
dle.java:310)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunn
er.java:100)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.jav
a:80)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
                                                                               C
ould not write standard input into: Gradle Test Executor 164.
java.io.IOException: 管道正在被关闭。
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82
)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOu
tputHandleRunner.java:50)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Process 'Gradle Test Executor 164' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 164' fi
nished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
rmalExitValue(DefaultExecHandle.java:365)
        at org.gradle.process.internal.DefaultWorkerProcess.onProcessStop(Defaul
tWorkerProcess.java:91)
        at org.gradle.process.internal.DefaultWorkerProcess.access$000(DefaultWo
rkerProcess.java:35)
        at org.gradle.process.internal.DefaultWorkerProcess$1.executionFinished(
DefaultWorkerProcess.java:57)
        at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:24)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:83)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocat
ionHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy50.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(Default
ExecHandle.java:213)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHan
dle.java:310)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunn
er.java:100)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.jav
a:80)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
                                                                               C
ould not write standard input into: Gradle Test Executor 165.
java.io.IOException: 管道正在被关闭。
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82
)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOu
tputHandleRunner.java:50)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Process 'Gradle Test Executor 165' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 165' fi
nished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
rmalExitValue(DefaultExecHandle.java:365)
        at org.gradle.process.internal.DefaultWorkerProcess.onProcessStop(Defaul
tWorkerProcess.java:91)
        at org.gradle.process.internal.DefaultWorkerProcess.access$000(DefaultWo
rkerProcess.java:35)
        at org.gradle.process.internal.DefaultWorkerProcess$1.executionFinished(
DefaultWorkerProcess.java:57)
        at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionD
ispatch.java:24)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:83)
        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java
:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocat
ionHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy50.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(Default
ExecHandle.java:213)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHan
dle.java:310)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunn
er.java:100)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.jav
a:80)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 1 mins 29.462 secs

**Comment by lqcamen** [comment]
I`m trying to import this RxJava into eclipse and it really beats me.

**Comment by akarnokd** [comment]
I see two errors:管道正在被关闭。and memory error. You need a 64 bit JVM set up as default.

**Comment by lqcamen** [comment]
OK, I`ll have a try.

**Comment by akarnokd** [comment]
I'm closing this as it seems the problem was solved eventually by the OP.
