### ISSUE TITLE
UNSAFE used in multiple places without checking UnsafeAccess#isUnsafeAvailable

### ISSUE THREAD

**Issue by yogurtearl** [ReactiveX/RxJava#3102]
According to: 
https://github.com/ReactiveX/RxJava/blob/v1.0.13/src/main/java/rx/internal/util/unsafe/UnsafeAccess.java

```
/**
 * All use of this class MUST first check that UnsafeAccess.isUnsafeAvailable() == true
 * otherwise NPEs will happen in environments without "suc.misc.Unsafe" such as Android.
 */
```

but there are a number of places where UNSAFE is accessed, but isUnsafeAvailable is not checked.
This means RxJava won't work if sun.misc.Unsafe is not available. 

( Although, it does seem to work fine on Android, because Android does have sun.misc.Unsafe )

Examples of places with no isUnsafeAvailable check:

ConcurrentCircularArrayQueue
SpmcArrayQueueConsumerField
ConcurrentSequencedCircularArrayQueue
SpscArrayQueue
etc...

**Comment by JakeWharton** [comment]
Also, as has been made painfully public with annoyingly sensational blog articles over the last few weeks, Unsafe will be unaccessible on Java 9.

**Comment by akarnokd** [comment]
See https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OperatorObserveOn.java#L101. As far as I remember, we always check `isUnsafeAvailable()` before attempting to instantiate these queues.

There are pure standard atomics based versions of these in [JCTools](https://github.com/JCTools/JCTools/tree/master/jctools-core/src/main/java/org/jctools/queues/atomic) but I don't have the time to move those over there. Besides, `SpscAtomicArrayQueue` can be collapsed into a much smaller footprint since we don't expose the queue instances to user code and can get away with the visibility of all the methods of `AtomicReferenceArray`.

**Comment by iNoles** [comment]
@yogurtearl Android only have limited functionality of sun.misc.Unsafe. Some times, it is best to not uses it on Android.

**Comment by hzsweers** [comment]
To chime in on this, I think we may be running into an area on Android where this runs into trouble. Specifically, if we try the following conditions:

* KitKat device running ART
* RxJava 1.0.13
* proguard optimizations (not obfuscated)

The app will ANR on startup with the following trace hanging on a call to `sun.misc.Unsafe.compareAndSwapLong`. 

Not sure if it's related to this discussion, but seems like a suspicious place to hang given what others have said above about sun.misc.Unsafe usage on Android. We currently believe this is just a bug in ART on kitkat devices, but could serve as a real world example of where this can be problematic.

```
DALVIK THREADS (63):
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x64ad1c28 self=0x4185d8e8
  | sysTid=27503 nice=0 cgrp=apps sched=0/0 handle=0x400c5154
  | state=S schedstat=( 0 0 0 ) utm=7973 stm=36 core=0 HZ=100
  | stack=0xbe197000-0xbe19b000 stackSize=8MB
  kernel: futex_wait_queue_me+0xd4/0xf0
  kernel: futex_wait+0xe8/0x220
  kernel: do_futex+0xc8/0x95c
  kernel: sys_futex+0x124/0x16c
  kernel: ret_fast_syscall+0x0/0x30
  native: ??? [0x4181cca8] (libart.so)
  at sun.misc.Unsafe.compareAndSwapLong(Native method)
  at java.util.concurrent.atomic.AtomicLongFieldUpdater$CASUpdater.compareAndSet(AtomicLongFieldUpdater.java:294)
  at rx.internal.util.BackpressureDrainManager.request(BackpressureDrainManager.java:156)
  at rx.Subscriber.request(Subscriber.java:145)
  at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:529)
  at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:258)
  at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
  at rx.internal.operators.OperatorOnBackpressureBuffer$BufferSubscriber.accept(OperatorOnBackpressureBuffer.java:121)
  at rx.internal.util.BackpressureDrainManager.drain(BackpressureDrainManager.java:201)
  at rx.internal.operators.OperatorOnBackpressureBuffer$BufferSubscriber.onNext(OperatorOnBackpressureBuffer.java:116)
  at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
  at rx.subjects.SubjectSubscriptionManager$SubjectObserver.accept$a2d69e2(SubjectSubscriptionManager.java:319)
  at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitFirst$a2d69e2(SubjectSubscriptionManager.java:1292)
  at rx.subjects.BehaviorSubject$1.call(BehaviorSubject.java:1106)
  at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:4101)
  at rx.Observable$1.call(Observable.java:1144)
  at rx.Observable$1.call(Observable.java:1144)
  at rx.Observable.unsafeSubscribe(Observable.java:7531)
  at rx.internal.operators.OperatorPublish.connect(OperatorPublish.java:186)
  at rx.internal.operators.OnSubscribeRefCount.call(OnSubscribeRefCount.java:2071)
  at rx.Observable$1.call(Observable.java:1144)
  at rx.Observable$1.call(Observable.java:1144)
  at rx.Observable.unsafeSubscribe(Observable.java:7531)
  at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceProducer.request(OnSubscribeCombineLatest.java:131)
  at rx.internal.operators.OperatorTake$1$1.request(OperatorTake.java:98)
  at rx.Subscriber.setProducer(Subscriber.java:175)
  at rx.Subscriber.setProducer(Subscriber.java:171)
  at rx.Subscriber.setProducer(Subscriber.java:171)
  at rx.internal.operators.OperatorTake$1.setProducer(OperatorTake.java:82)
  at rx.Subscriber.setProducer(Subscriber.java:171)
  at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:1068)
  at rx.Observable$1.call(Observable.java:1144)
  at rx.Observable$1.call(Observable.java:1144)
  at rx.Observable.unsafeSubscribe(Observable.java:7531)
  at rx.android.lifecycle.OperatorSubscribeUntil.call(OperatorSubscribeUntil.java:1039)
  at rx.Observable$1.call(Observable.java:1140)
  at rx.Observable.subscribe(Observable.java:7621)
  at rx.Observable.subscribe(Observable.java:7349)
  at flipboard.gui.section.SectionFragment.onCreateView(SectionFragment.java:1289)
  ...
```

**Comment by hzsweers** [comment]
To add to this, Android Studio won't even let you try to import that package if you try to use it in an Android project.
