### ISSUE TITLE
MissingBackpressureException when not using Backpressure

### ISSUE THREAD

**Issue by spierce7** [ReactiveX/RxJava#3187]
Hey, I'm seeing a crash on my Android app but I'm not sure exactly what's causing the crash (Exception included at the bottom). We don't use or request backpressure anywhere in our app. This is on RxJava `1.0.13`. My only thought would be that maybe some other RX operator is doing this.

For instance, we have a zip operator:
```Java
Observable.zip(
        new ObservableThatRunsInThread1(),
        new ObservableThatRunsInThread2(),
        new ObservableThatRunsInThread3(),
        new ObservableThatRunsInThread4(),
        new Func4<Object, Object, Object, Object, Response>() {
            @Override public Response call(Object o1, Object o2, Object o3, Object o4) {
                return new Response(o1, o2, o3, o4);
            }
        }
);
```
Could the multiple threads possibly be causing a race condition, or something of the sort? I'm a bit stuck at this point. Thanks!

```Java
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5835)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: rx.exceptions.OnErrorNotImplementedException
       at rx.Observable$30.onError(Observable.java:7540)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5835)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: rx.exceptions.MissingBackpressureException
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:138)
       at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:51)
       at rx.Scheduler$Worker$1.call(Scheduler.java:120)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by akarnokd** [comment]
It appears your periodic timer overflows the observeOn buffer. You have to apply `onBackpressureDrop`.

**Comment by spierce7** [comment]
Oh, so this is happening with a timer? I see it now with the `OnSubscribeTimerPeriodically`.

On all timers should I be applying backpressure drop? If I use RxJava for any sort of timers, in what cases should I be worried about this exception?

Thanks for your fast reply!

**Comment by akarnokd** [comment]
If you don't mind losing a tick with a periodic timer then `onBackpressureDrop` should work. Otherwise, if you thing it is just a transitional effect, you can use `onBackpressureBuffer`.

If you encounter this exception, you should verify all the operators do support backpressure. If not, you need to apply one of the `onBackpressureXXX` methods. If all the operators support backpressure yet you encounter this exception, it is possible that there is a bug in one of the operators and you should report it here.

**Comment by spierce7** [comment]
So in instances where we have a long running timer like this:
```Java
mSubscription = Observable.timer(0L, DateUtils.SECOND_IN_MILLIS, TimeUnit.MILLISECONDS)
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(new Action1<Long>() {
            @Override public void call(final Long l) {
            }
        });
```

Would you recommend putting the `.onBackpressureDrop()` above or below the `.observeOn()`?

**Comment by akarnokd** [comment]
Above.

**Comment by spierce7** [comment]
Thank you, I appreciate you being so helpful. :-)
