### ISSUE TITLE
SwitchMap with connectable's Replay raise exception

### ISSUE THREAD

**Issue by Diolor** [ReactiveX/RxJava#3466]
For the following code:

```java
ConnectableObservable<Long> replayObs = Observable.interval(3, TimeUnit.SECONDS)
		.startWith(-5L)
		.switchMap(aLong -> {
			if (aLong == 2L) {
				return Observable.error(new NullPointerException());
			} else {
				return Observable.just(aLong);
			}
		})
		.replay(1);

replayObs.connect(Actions.empty());

replayObs
		.subscribe(s -> {
			Log.wtf("MainActivity ", "call " + s);
		}, throwable -> {
			Log.wtf("MainActivity ", throwable);
		});
```

It emmits the following:
```
MainActivity: call -5
MainActivity: java.lang.IllegalStateException: more items arrived than were requested
MainActivity:     at rx.internal.producers.ProducerArbiter.produced(ProducerArbiter.java:98)
```

I realize that the `.connect` is happening before the first `.subscribe` but if I have `.flatpMap` instead, which has a different producer, it doesn't complain.

This is the simplest way to raise the exception:

```java
ConnectableObservable<Long> replayObs = Observable.just(1l)
		.switchMap(Observable::just)
	//  .onBackpressureBuffer(1)
		.replay(1);
```

Adding a onBackpreassureBuffer(1) before the .replay() solves the problem. Is that a correct solution? Is that a bug in the `ProducerArbiter`?

---

Full stacktrace:
```
java.lang.IllegalStateException: more items arrived than were requested
    at rx.internal.producers.ProducerArbiter.produced(ProducerArbiter.java:98)
    at rx.internal.operators.OperatorSwitch$SwitchSubscriber.emit(OperatorSwitch.java:162)
    at rx.internal.operators.OperatorSwitch$InnerSubscriber.onNext(OperatorSwitch.java:277)
    at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:46)
    at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:35)
    at rx.Observable.unsafeSubscribe(Observable.java:7710)
    at rx.internal.operators.OperatorSwitch$SwitchSubscriber.onNext(OperatorSwitch.java:105)
    at rx.internal.operators.OperatorSwitch$SwitchSubscriber.onNext(OperatorSwitch.java:60)
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
    at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:46)
    at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:35)
    at rx.Observable$2.call(Observable.java:162)
    at rx.Observable$2.call(Observable.java:154)
    at rx.Observable$2.call(Observable.java:162)
    at rx.Observable$2.call(Observable.java:154)
    at rx.Observable.unsafeSubscribe(Observable.java:7710)
    at rx.internal.operators.OperatorReplay.connect(OperatorReplay.java:285)
    at com.lorentzos.rxexperiment.MainActivity.onCreate(MainActivity.java:42)
    at android.app.Activity.performCreate(Activity.java:5990)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
    at android.app.ActivityThread.access$900(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5289)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by davidmoten** [comment]
What's happening here is that you are using sources that don't support backpressure. `Observable.interval()` doesn't support backpressure so combine it with `.onBackpressureXXX()`. Ditto for `Observable.just` with one parameter (with two or more does support backpressure).

I'm actually intrigued to see this one because I hadn't yet been able to bring about backpressure exceptions using `Observable.just(t)` (see #3044). Thanks!

**Comment by davidmoten** [comment]
Distilling this test case a bit further:

This one fails with `java.lang.IllegalStateException: more items arrived than were requested`:
```java
ConnectableObservable<Integer> o = Observable
    .just(1,2)
    .switchMap(x -> Observable.just(x))
    .replay();
o.connect();
o.subscribe();
```

This one does not fail:
```java
ConnectableObservable<Integer> o = Observable
    .just(1,2)
    .switchMap(x -> Observable.just(x).onBackpressureBuffer())
    .replay();
o.connect();
o.subscribe();
```

**Comment by Diolor** [comment]
Thanks @davidmoten, I saw today that `just(t1, t2)` is using a producer which handles back pressure `just(t1)` doesn't.

I will close this, since #3044 is open.

Thanks! :+1:
