### ISSUE TITLE
Run tests on Android during CI

### ISSUE THREAD

**Issue by artem-zinnatullin** [ReactiveX/RxJava#3503]
Subj ^. Since Android is major platform for RxJava and RxJava has some Android-specific code would be nice to run tests on it during the CI.

At the moment I'm targeting 1.x branch, when and if 2.x will be compilable to Java 6 — we will be able to do the same for 2.x.

I've started movements in that direction but currently blocked by https://github.com/nebula-plugins/nebula-release-plugin/issues/33.

In case you worried about the speed of builds on the CI: we will run tests on Android in parallel to current builds, Travis CI allows that via build matrix.

What does community think about it?

**Comment by artem-zinnatullin** [comment]
Well, looks like it worh it, tests failures (Nexus 5, Android 6.0):

* `CachedObservableTest.testNoMissingBackpressureException`
* `OnSubscribeCombineLatest.test1ToNSources` (not timeout)
* `OnSubscribeRefCountTest.testUpstreamErrorAllowsRetry`
* `CachedThreadSchedulerTest.testCancelledTaskRetention` (not timeout)
* `ComputationSchedulerTests.testCancelledTaskRetention` (not timeout)
* `TrampolineSchedulerTest.testTrampolineWorkerHandlesConcurrentScheduling`
* `ObservableTests.testErrorThrownIssue1685`

Good news, test runner sees all tests and project setup was pretty easy! (except nebula plugin, I had to disable it):
![screen shot 2015-11-09 at 06 10 27](https://cloud.githubusercontent.com/assets/967132/11025414/ab663ae0-86ab-11e5-9eb2-8dc2d5fa73f8.png)

Here is the branch in my fork if somebody wants to play with it: https://github.com/artem-zinnatullin/RxJava/tree/android-tests, `./gradlew connectedAndroidTest`.

@akarnokd if you want to investigate tests failures — ping me, I'll help you setup device/emulator!

**Comment by davidmoten** [comment]
Thanks for this. Can you publish error stack traces here as well?

**Comment by akarnokd** [comment]
Please post the failure stacktraces for a start.

**Comment by akarnokd** [comment]
I managed to set up a simulated environment and I get the error from 

ObservableTests.testErrorThrownIssue1685
-------------

```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
  Caused by: rx.exceptions.OnErrorNotImplementedException: oops
     at rx.Observable$26.onError(Observable.java:7954)
     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:158)
     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:119)
     at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onError(SubjectSubscriptionManager.java:226)
     at rx.internal.operators.NotificationLite.accept(NotificationLite.java:147)
     at rx.subjects.ReplaySubject$UnboundedReplayState.accept(ReplaySubject.java:466)
     at rx.subjects.ReplaySubject$UnboundedReplayState.replayObserverFromIndex(ReplaySubject.java:515)
     at rx.subjects.ReplaySubject$UnboundedReplayState.replayObserver(ReplaySubject.java:503)
     at rx.subjects.ReplaySubject.caughtUp(ReplaySubject.java:423)
     at rx.subjects.ReplaySubject.onError(ReplaySubject.java:383)
     at rx.Observable$30.onError(Observable.java:8137)
     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:158)
     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:119)
     at rx.internal.operators.OperatorDematerialize$1.onError(OperatorDematerialize.java:72)
     at rx.internal.operators.OperatorDematerialize$1.onNext(OperatorDematerialize.java:60)
     at rx.internal.operators.OperatorDematerialize$1.onNext(OperatorDematerialize.java:48)
     at rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:89)
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
     at java.lang.Thread.run(Thread.java:818) 
  Caused by: java.lang.RuntimeException: oops
     at rx.ObservableTests.testErrorThrownIssue1685(ObservableTests.java:1107)
     at java.lang.reflect.Method.invoke(Native Method)
     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     at org.junit.runners.Suite.runChild(Suite.java:128)
     at org.junit.runners.Suite.runChild(Suite.java:27)
     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
     at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
 	at android.support.test.internal.runner
```

The reason for this popping up is that on desktop, the uncaught exception handler of a thread does nothing by default whereas the Android version will panic [ScheduledAction.java:66](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/schedulers/ScheduledAction.java#L66).

Making sure `onError` is there defeats the purpose of the test. Removing the call to `uncaughtException` endangers discovering real problems.

testNoMissingBackpressureException
----

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 13 byte allocation with 4194304 free bytes and 11MB until OOM; failed due to fragmentation (required continguous free 4096 bytes for a new buffer where largest contiguous free 0 bytes)
     at rx.internal.schedulers.ScheduledAction.<init>(ScheduledAction.java:48)
     at rx.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:265)
     at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker.schedule(EventLoopsScheduler.java:164)
     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.schedule(OperatorObserveOn.java:177)
     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:141)
     at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
     at rx.internal.operators.CachedObservable$ReplayProducer.replay(CachedObservable.java:404)
     at rx.internal.operators.CachedObservable$ReplayProducer.request(CachedObservable.java:304)
     at rx.Subscriber.request(Subscriber.java:157)
     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:224)
     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
```

My device is the default `Nexus 5` emulator. Either the the test or the device doesn't allow for much memory and hence the OOM.

testWithCombineLatestIssue1717
---

The test times out with 3 seconds; My guess is that the newThread reacts to slowly and the millisecond timer overflows the `observeOn` queue, causing a hidden `MissingBackpressureException` but the latch is only decremented on the normal path.

testUpstreamErrorAllowsRetry
---

Similar `uncaughtException` handler problem: after the 6th retry, the exception finally passes through to the subscriber and fails with `OnErrorNotImplementedException` immediately. This test can be modified to swallow the exception as it is not relevant.

NullPointerException
----

I'm getting NPEs all over the place:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
 at com.android.dx.mockito.DexmakerMockMaker.getInvocationHandlerAdapter(DexmakerMockMaker.java:81)
 at com.android.dx.mockito.DexmakerMockMaker.getHandler(DexmakerMockMaker.java:76)
 at org.mockito.internal.util.MockUtil.isMockitoMock(MockUtil.java:74)
 at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:66)
 at org.mockito.internal.configuration.injection.scanner.MockScanner.isMockOrSpy(MockScanner.java:86)
 at org.mockito.internal.configuration.injection.scanner.MockScanner.preparedMock(MockScanner.java:72)
 at org.mockito.internal.configuration.injection.scanner.MockScanner.scan(MockScanner.java:61)
 at org.mockito.internal.configuration.injection.scanner.MockScanner.addPreparedMocks(MockScanner.java:47)
 at org.mockito.internal.configuration.InjectingAnnotationEngine.injectMocks(InjectingAnnotationEngine.java:96)
 at org.mockito.internal.configuration.InjectingAnnotationEngine.processInjectMocks(InjectingAnnotationEngine.java:62)
 at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:56)
 at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:108)
 at rx.internal.operators.OnSubscribeTimerTest.before(OnSubscribeTimerTest.java:51)
```

**Comment by artem-zinnatullin** [comment]
@akarnokd great! Looks like most of them are fixable.

`ObservableTests.testErrorThrownIssue1685` what if we set default exception handler before test and then remove after the test and check that it was called? It will make test better and prevent crash on the Android.

`testNoMissingBackpressureException` we can try to increase heap size on Android, but it's more hack than a good solution.

>I'm getting NPEs all over the place:

Looks like a bug in DexMaker https://github.com/crittercism/dexmaker/pull/24/, though I haven't seen it in my run.

**Comment by akarnokd** [comment]
> ObservableTests.testErrorThrownIssue1685 what if we set default exception handler before test and then remove after the test and check that it was called? It will make test better and prevent crash on the Android.

We could run that on a custom single threaded scheduler which is preset with a no-op handler.

**Comment by akarnokd** [comment]
Added a few fixes in #3504.

**Comment by akarnokd** [comment]
> At the moment I'm targeting 1.x branch, when and if 2.x will be compilable to Java 6 — we will be able to do the same for 2.x.

You can try my backport `com.github.akarnokd:rxjava2-backport:2.0.0-RC2` right away.

**Comment by artem-zinnatullin** [comment]
Issue with nebula-release-plugin was resolved, I'll try to prepare PR in a couple days, but since it requires project structure change — PR will conflict with all other PRs (though I hope git will manage file path changes and most of the PRs will be okay).

>You can try my backport com.github.akarnokd:rxjava2-backport:2.0.0-RC2 right away.

Yeah, but looks like we need to discuss plans about RxJava 2.x again, work on 2.x branch almost stopped, I guess collaborators and community need to talk and define clear roadmap for 2.x so we could continue work on it. What about Hangouts meeting? (not directly related to this issue, feel free to move discussion to some issue about 2.x).

**Comment by akarnokd** [comment]
Closing for now as #3519 is closed.
