### ISSUE TITLE
Null pointer using ConcatMapEager on Android 4.2

### ISSUE THREAD

**Issue by jjvargas** [ReactiveX/RxJava#3508]
I am using a Tablet with Android 4.2  using 'io.reactivex:rxjava:1.0.15'

In Android 5.1 it works fine, but not it 4.2

    public Observable<Artist[]> batchGetArtistsById(ArtistIdList artistIdList) {
            return Observable.from(artistIdList.getArtistIds())
                    .concatMapEager(artist -> getArtistById(artist))
                    .subscribeOn(Schedulers.io())
                    .toList()
                    .observeOn(AndroidSchedulers.mainThread())
                    .doOnError(e ->
                            {
                                System.out.println("Error what to do? " + e);
                            }
                    )
                    .flatMap(artistList -> {
                        Artist[] artistsArray = artistList.toArray(new Artist[artistList.size()]);
                        return Observable.just(artistsArray);
                    });
    }

11-09 16:23:01.485 6762-6782/? E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                 java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                     at java.lang.Thread.run(Thread.java:856)
                                                  Caused by: java.lang.ExceptionInInitializerError
                                                     at rx.internal.operators.OperatorEagerConcatMap$EagerInnerSubscriber.<init>(OperatorEagerConcatMap.java:281)
                                                     at rx.internal.operators.OperatorEagerConcatMap$EagerOuterSubscriber.onNext(OperatorEagerConcatMap.java:130)
                                                     at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:127)
                                                     at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:70)
                                                     at rx.Subscriber.setProducer(Subscriber.java:209)
                                                     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:49)
                                                     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:32)
                                                     at rx.Observable$2.call(Observable.java:162)
                                                     at rx.Observable$2.call(Observable.java:154)
                                                     at rx.Observable.unsafeSubscribe(Observable.java:8171)
                                                     at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153) 
                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                     at java.lang.Thread.run(Thread.java:856) 
                                                  Caused by: java.lang.NullPointerException
                                                     at rx.internal.util.unsafe.ConcurrentCircularArrayQueue.<clinit>(ConcurrentCircularArrayQueue.java:51)
                                                     at rx.internal.operators.OperatorEagerConcatMap$EagerInnerSubscriber.<init>(OperatorEagerConcatMap.java:281) 
                                                     at rx.internal.operators.OperatorEagerConcatMap$EagerOuterSubscriber.onNext(OperatorEagerConcatMap.java:130) 
                                                     at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:127) 
                                                     at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:70) 
                                                     at rx.Subscriber.setProducer(Subscriber.java:209) 
                                                     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:49) 
                                                     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:32) 
                                                     at rx.Observable$2.call(Observable.java:162) 
                                                     at rx.Observable$2.call(Observable.java:154) 
                                                     at rx.Observable.unsafeSubscribe(Observable.java:8171) 
                                                     at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) 
                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153) 
                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                     at java.lang.Thread.run(Thread.java:856)

**Comment by akarnokd** [comment]
Do you, by any chance, have a Samsung device?

**Comment by jjvargas** [comment]
Its a Custom Tablet , non branded .

**Comment by artem-zinnatullin** [comment]
@akarnokd you can create Android 4.2 emulator (Android API level 17) and try to run tests (#3503) on it, or I'll do this tonight.

**Comment by jjvargas** [comment]
I tried with Genymotion I get the same error

**Comment by akarnokd** [comment]
My guess is that there is the same field error as with those Samsung devices so android.os.Build.VERSION.INT_VER is not properly discovered and the library thinks it runs on desktop Java.

**Comment by akarnokd** [comment]
Ups, my bad. Forgot to check the unsafe access in eager concatmap.

**Comment by akarnokd** [comment]
Fix posted in #3510

**Comment by akarnokd** [comment]
Closing via #3510.
