### ISSUE TITLE
BlockingObservable.blockForSingle() can throw exception that doesn't have a stacktrace for the current thread

### ISSUE THREAD

**Issue by cer** [ReactiveX/RxJava#3558]
lines 452:

```
       if (returnException.get() != null) {
            if (returnException.get() instanceof RuntimeException) {
                throw (RuntimeException) returnException.get();
            } else {
                throw new RuntimeException(returnException.get());
            }
        }
```

`throw (RuntimeException) returnException.get();` throws an exception for another thread resulting in unhelpful stack traces such as 

```
java.util.NoSuchElementException: Sequence contains no elements
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:131)
	at rx.internal.operators.OperatorTake$1.onCompleted(OperatorTake.java:50)
	at rx.internal.operators.OperatorFilter$1.onCompleted(OperatorFilter.java:42)
	at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:44)
	at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:69)
	at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:51)
	at rx.Scheduler$Worker$1.call(Scheduler.java:120)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by akarnokd** [comment]
We wanted to avoid wrapping a `RuntimeException`. The analogous `Future.get()` does wrap everything and throws a checked `ExecutionException`. Even if we wrap the exception into an unchecked exception in the operator, that counts as an incompatible API change.

**Comment by akarnokd** [comment]
I'm closing this. Let me know if you have further questions.
