### ISSUE TITLE
ArrayIndexOutOfBoundsException caused by ReplaySubject.java:459 in ArrayList

### ISSUE THREAD

**Issue by Hauke85** [ReactiveX/RxJava#3725]
I wrote some testcode that causes an `ArrayIndexOutOfBoundsException` on almost every run and i do not understand why, how to avoid it or if this is a bug in (rx)java.

The exception is thrown in `ArrayList#add(E e)` by calling `elementData[size++] = e;` where a call of `ensureCapacityInternal(size+1)` should have made sure that the capacity is sufficient. I assume some concurrency-related problem.

What the code was intended to do:  Start a new "WorkerThread" every second that produces Strings at a given rate and collect the resulting items of all those workers (here called "Minions") in one re-playable `Observable<String>`. 
The actual parameters are just set to increase probability of this exception to be thrown.

```java
package mypackage;

import rx.Observable;
import rx.Scheduler;
import rx.observables.ConnectableObservable;
import rx.schedulers.Schedulers;
import rx.subjects.ReplaySubject;

import java.util.Iterator;
import java.util.concurrent.TimeUnit;

public class TestOutOfBounds {

    public static void main(String... args) throws InterruptedException {
        boolean exitAfterIdling = false;
        boolean spamConsole = false;

        ConnectableObservable<String> someWorker = makeWorker("Some Worker", 1000, Schedulers.newThread(), 5); //Sends one Item per second, and finishes after 5 items

        /* Everything runs fine with these values
        //Milliseconds our workers will take for each item
        long minionDelay = 500;
        //how many items each worker produces
        int minionWorkload = 5;
        */

        //Problems start here
        //FIXME: ArrayIndexOutOfBoundsException with these values
        //Milliseconds our workers will take for each item
        long minionDelay = 1;
        //how many items each worker produces
        int minionWorkload = 50000;


        ConnectableObservable<ConnectableObservable<String>> minions =
                Observable.range(0, 20) //make 20 minions
                        .map(i -> makeWorker("Minion " + i, minionDelay, Schedulers.newThread(), minionWorkload))//map number to minion instances
                        .subscribeOn(Schedulers.newThread())
                        .replay(); //make sure we dont loose any


        final ReplaySubject<String> minionOutput = ReplaySubject.create();

        minions.subscribe(minion -> {
            //forward all items to the ReplaySubject
            minion.subscribe(minionOutput::onNext);
        });

        //start one per second
        minions.subscribe(minion -> {
            try {
                //We want to simmulate some setup time/latency;
                //So we connect one per second
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println("Connecting a Minion");
            minion.connect();
        });

        //"merging items emmitted of someWorker and our minions;
        Observable<String> allWork = Observable.merge(someWorker, minionOutput);
        //make it replayable to make sure we do not loose items and have it wait for connection
        ConnectableObservable<String> replayableWork = allWork.replay();

        if(spamConsole) {
            //Show everything our workers emmited
            replayableWork.map(s->"Subscriber 1: " + s ).subscribe(System.out::println);
        }

        minions.connect();
        someWorker.connect();

        if (exitAfterIdling) {
            //If for 5 seconds no new items come in we assume to have finished
            //FIXME: does not work, if @code{exitAfterIdling} is true we immediatly terminate here
            replayableWork.timeout(5, TimeUnit.SECONDS).doOnNext(foo -> {
                System.out.println("Looks like we are done");
                System.exit(0);
            }).subscribe();
        }

        //Begin observing work results
        replayableWork.connect();

        //Wait some time to let some work accumulate to test if second subscriber gets all items
        Thread.sleep(5000);
        System.out.println("2nd Subscriber");
        if(spamConsole) {
            replayableWork.subscribe(s -> {
                System.out.println("Subscriber 2: " + s);
            });
        }

        while (true) {
            //Keep the Programm running untill told otherwise
            System.out.println("Mainthread Idle");
            Thread.sleep(10000);
        }
    }

    public static ConnectableObservable<String> makeWorker(String name, long delay, Scheduler scheduler, final int ammount) {
        final Iterator<Integer> counter = makeCounter(ammount);
        Observable<String> worker = Observable.create(subscriber -> {
            System.out.println("Starting Worker-Subsciber \"" + name + "\" for " + ammount + " lots of work");
            int lastCount = 0;
            subscriber.onStart();
            while (counter.hasNext() && !subscriber.isUnsubscribed()) {
                lastCount = counter.next() + 1;

                try {
                    //Simmulate hard work by doing nothing
                    subscriber.onNext("Work from \"" + name + "\"" + " (" + lastCount + "/" + ammount + ")");
                    Thread.currentThread().sleep(delay);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
            if (!subscriber.isUnsubscribed()) {
                System.out.println("Worker-Subscriber \"" + name + "\" finished after " + lastCount + "/" + ammount + " lots of work");
                subscriber.onCompleted();
            } else {
                System.out.println("Worker-Subscriber \"" + name + "\" was unsuscribed and finished after " + lastCount + "/" + ammount + " lots of work");
            }


        });
        //make this connectable so we dont miss one of our workers items
        return worker.subscribeOn(scheduler).replay();//;
    }


    /**Just a counter, could be done with range, but was intended to test with somthing statefull*/
    private static Iterator<Integer> makeCounter(final int ammount) {
        return new Iterator<Integer>() {
            private int counter = 0;
            @Override
            public boolean hasNext() {return counter < ammount;}
            @Override
            public Integer next() {return counter++;}
        };
    }
}
```

this usually results in an exception (some time with much lower index):

```
Exception in thread "RxNewThreadScheduler-4" Exception in thread "RxNewThreadScheduler-7" Exception in thread "RxNewThreadScheduler-3" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: 10390
	at rx.Observable$27.onError(Observable.java:8139)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:200)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
	at rx.internal.operators.OperatorReplay$UnboundedReplayBuffer.replay(OperatorReplay.java:821)
	at rx.internal.operators.OperatorReplay$ReplaySubscriber.replay(OperatorReplay.java:559)
	at rx.internal.operators.OperatorReplay$ReplaySubscriber.onNext(OperatorReplay.java:450)
	at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
	at mypackage.TestOutOfBounds.lambda$makeWorker$0(TestOutOfBounds.java:24)
	at mypackage.TestOutOfBounds$$Lambda$1/1567581361.call(Unknown Source)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10390
	at java.util.ArrayList.add(ArrayList.java:459)
	at rx.subjects.ReplaySubject$UnboundedReplayState.next(ReplaySubject.java:459)
	at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:371)
	at mypackage.TestOutOfBounds$$Lambda$5/1948591192.call(Unknown Source)
	at rx.Observable$27.onNext(Observable.java:8144)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	... 17 more
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: 10390
	at rx.Observable$27.onError(Observable.java:8139)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:200)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
	at rx.internal.operators.OperatorReplay$UnboundedReplayBuffer.replay(OperatorReplay.java:821)
	at rx.internal.operators.OperatorReplay$ReplaySubscriber.replay(OperatorReplay.java:559)
	at rx.internal.operators.OperatorReplay$ReplaySubscriber.onNext(OperatorReplay.java:450)
	at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
	at mypackage.TestOutOfBounds.lambda$makeWorker$0(TestOutOfBounds.java:24)
	at mypackage.TestOutOfBounds$$Lambda$1/1567581361.call(Unknown Source)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10390
	at java.util.ArrayList.add(ArrayList.java:459)
	at rx.subjects.ReplaySubject$UnboundedReplayState.next(ReplaySubject.java:459)
	at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:371)
	at mypackage.TestOutOfBounds$$Lambda$5/1948591192.call(Unknown Source)
	at rx.Observable$27.onNext(Observable.java:8144)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	... 17 more
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: 10390
	at rx.Observable$27.onError(Observable.java:8139)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:200)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
	at rx.internal.operators.OperatorReplay$UnboundedReplayBuffer.replay(OperatorReplay.java:821)
	at rx.internal.operators.OperatorReplay$ReplaySubscriber.replay(OperatorReplay.java:559)
	at rx.internal.operators.OperatorReplay$ReplaySubscriber.onNext(OperatorReplay.java:450)
	at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
	at mypackage.TestOutOfBounds.lambda$makeWorker$0(TestOutOfBounds.java:24)
	at mypackage.TestOutOfBounds$$Lambda$1/1567581361.call(Unknown Source)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10390
	at java.util.ArrayList.add(ArrayList.java:459)
	at rx.subjects.ReplaySubject$UnboundedReplayState.next(ReplaySubject.java:459)
	at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:371)
	at mypackage.TestOutOfBounds$$Lambda$5/1948591192.call(Unknown Source)
	at rx.Observable$27.onNext(Observable.java:8144)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	... 17 more
```
Thanks

**Comment by akarnokd** [comment]
I've run your code several times and it didn't crash. The exception may only happen if you call `onNext` of the `minionOutput` concurrently; the example doesn't seem to do this.

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
