### ISSUE TITLE
1.x: BlockingOperatorNextTest > testNoBufferingOrBlockingOfSequence FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#3835]
```
rx.internal.operators.BlockingOperatorNextTest > testNoBufferingOrBlockingOfSequence FAILED
    java.lang.AssertionError: c should not just be the next in sequence
        at org.junit.Assert.fail(Assert.java:93)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at rx.internal.operators.BlockingOperatorNextTest.testNoBufferingOrBlockingOfSequence(BlockingOperatorNextTest.java:286)
```

This appears to be a flaky tests:
- calls `next()` when the source releases a latch, which could still end up receiving the subsequent value, not skipping as expected
- failure in the test won't shut down the source thread which then keeps spinning.

**Comment by akarnokd** [comment]
Closing for now. I don't think this can be resolved because the operator relies on meeting offer-demand situation that any delay can throw off.
