### ISSUE TITLE
java.lang.IllegalStateException: more items arrived than were requested

### ISSUE THREAD

**Issue by vadims** [ReactiveX/RxJava#3892]
We're seeing this exception for a small percent of our users. We haven't been able to reproduce this ourselves so providing a sample might not be feasible. Any idea what could be causing this based on the stacktrace alone?

```java
Non-fatal Exception: java.lang.IllegalStateException: more items arrived than were requested
       at rx.internal.producers.ProducerArbiter.produced(ProducerArbiter.java:98)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerCompleted(OnSubscribeConcatMap.java:206)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onCompleted(OnSubscribeConcatMap.java:345)
       at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
       at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:129)
       at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:107)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:635)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:547)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:268)
       at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:47)
       at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:32)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable.unsafeSubscribe(Observable.java:8741)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerCompleted(OnSubscribeConcatMap.java:209)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onCompleted(OnSubscribeConcatMap.java:345)
       at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
       at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:125)
       at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.emit(OperatorTakeLastOne.java:159)
       at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:125)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:635)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:547)
       at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:836)
       at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
       at rx.internal.operators.OperatorSubscribeOn$1$1.onCompleted(OperatorSubscribeOn.java:68)
       at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:76)
       at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
       at rx.Observable.unsafeSubscribe(Observable.java:8741)
       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by akarnokd** [comment]
Looks like `OnSubscribeToObservableFuture` was not refitted with backpressure support and it fires the future's value unconditionally. I'll post a fix for this. Thanks for reporting!

**Comment by akarnokd** [comment]
See #3893.

Workaround for now: apply `onBackpressureBuffer()` after the `from(Future)` you are using.

**Comment by vadims** [comment]
Great, thanks!

**Comment by vadims** [comment]
I think there might be other operators that need to be retrofitted? 

```java
Non-fatal Exception: java.lang.IllegalStateException: more items arrived than were requested
       at rx.internal.producers.ProducerArbiter.produced(ProducerArbiter.java:98)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerCompleted(OnSubscribeConcatMap.java:206)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onCompleted(OnSubscribeConcatMap.java:345)
       at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
       at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:129)
       at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:107)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:635)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:547)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:268)
       at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:47)
       at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:32)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable$2.call(Observable.java:233)
       at rx.Observable$2.call(Observable.java:225)
       at rx.Observable.unsafeSubscribe(Observable.java:8741)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerCompleted(OnSubscribeConcatMap.java:209)
       at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onCompleted(OnSubscribeConcatMap.java:345)
       at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
       at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:125)
       at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.emit(OperatorTakeLastOne.java:159)
       at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:125)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:635)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:547)
       at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:836)
       at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
       at rx.internal.operators.OperatorOnBackpressureBuffer$BufferSubscriber.complete(OperatorOnBackpressureBuffer.java:169)
       at rx.internal.util.BackpressureDrainManager.drain(BackpressureDrainManager.java:187)
       at rx.internal.util.BackpressureDrainManager.terminateAndDrain(BackpressureDrainManager.java:114)
       at rx.internal.operators.OperatorOnBackpressureBuffer$BufferSubscriber.onCompleted(OperatorOnBackpressureBuffer.java:140)
       at rx.internal.operators.OperatorSubscribeOn$1$1.onCompleted(OperatorSubscribeOn.java:68)
       at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:76)
       at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
       at rx.Observable.unsafeSubscribe(Observable.java:8741)
       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by akarnokd** [comment]
Do you have a default value on your single() operator?

**Comment by vadims** [comment]
We call `lastOrDefault` which calls `new OperatorSingle<T>(defaultValue)`.

**Comment by akarnokd** [comment]
Thanks, found the issue in OperatorSingle, when the default path is taken, the value is emitted without checking for backpressure. I'll post a fix soon.

**Comment by akarnokd** [comment]
See #3905.

**Comment by vadims** [comment]
Thanks!

**Comment by zsxwing** [comment]
Close via #3905
