### ISSUE TITLE
error when Zipping 2 publish subjects asynchroneously

### ISSUE THREAD

**Issue by Crystark** [ReactiveX/RxJava#3967]
Hi,

I'm having some weird problem I've tried to simplify.

Take for instance the following code:

``` java
        for (int i = 0; i < 500; i++) {
            Subject<Integer, Integer> s1 = PublishSubject.<Integer> create().toSerialized();
            Subject<Integer, Integer> s2 = PublishSubject.<Integer> create().toSerialized();

            Observable.zip(s1.single(), s2.toList(), (a, b) -> null)
                .subscribeOn(Schedulers.io())
                .subscribe(
                    j -> {},
                    t -> {
                        t.printStackTrace();
                    });

            s1.onNext(1);
            s2.onNext(1);
            s1.onCompleted();
            s2.onCompleted();
        }
        Thread.sleep(5000);
```

I'm often getting the following error:

```
java.util.NoSuchElementException: Sequence contains no elements
    at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:131)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
    at rx.subjects.SubjectSubscriptionManager$SubjectObserver.accept(SubjectSubscriptionManager.java:318)
    at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitLoop(SubjectSubscriptionManager.java:291)
    at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitFirst(SubjectSubscriptionManager.java:270)
    at rx.subjects.PublishSubject$1.call(PublishSubject.java:66)
    at rx.subjects.PublishSubject$1.call(PublishSubject.java:62)
    at rx.subjects.SubjectSubscriptionManager.add(SubjectSubscriptionManager.java:95)
    at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:60)
    at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:35)
    at rx.Observable.unsafeSubscribe(Observable.java:8172)
    at rx.subjects.SerializedSubject$1.call(SerializedSubject.java:45)
    at rx.subjects.SerializedSubject$1.call(SerializedSubject.java:41)
    at rx.Observable$2.call(Observable.java:162)
    at rx.Observable$2.call(Observable.java:154)
    at rx.Observable.unsafeSubscribe(Observable.java:8172)
    at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:209)
    at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:156)
    at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:122)
    at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:46)
    at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:35)
    at rx.Observable$2.call(Observable.java:162)
    at rx.Observable$2.call(Observable.java:154)
    at rx.Observable.unsafeSubscribe(Observable.java:8172)
    at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I'm not sure what's going wrong here. It would seem that from time to time, the `s1` subject receives the onCompleted before the onNext.

I saw that removing `.subscribeOn(Schedulers.io())` fixes this but I'd like to understand why.
Depending on that I could come up with an other solution to what i'm trying to do.

Thanks

**Comment by akarnokd** [comment]
Because you subscribe on a different thread, the two subjects don't have any subscriber yet when you call onXXX on them, dropping the values. Once zip can subscribe, both may end up being completed and thus the first source will signal the `NoSuchElementException`.

**Comment by Crystark** [comment]
Indeed, I can see it now. Thanks for the explanation.
So if I understand this well, using a `ReplaySubject` seems to be the way to go if I want to keep this order of code ?

**Comment by akarnokd** [comment]
Yes.

**Comment by Crystark** [comment]
Thanks alot!
