### ISSUE TITLE
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by cn-ljb** [ReactiveX/RxJava#3972]
I met this exception, I hope someone can help me

```
Process: cn.com.xgo.dealer.two, PID: 3921
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5438)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:194)
  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
  at rx.observers.SerializedObserver.onError(SerializedObserver.java:159)
  at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:79)
  at rx.internal.operators.OperatorTakeUntil$1.onError(OperatorTakeUntil.java:49)
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  at android.os.Handler.handleCallback(Handler.java:739) 
  at android.os.Handler.dispatchMessage(Handler.java:95) 
  at android.os.Looper.loop(Looper.java:148) 
  at android.app.ActivityThread.main(ActivityThread.java:5438) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:194) 
  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120) 
  at rx.observers.SerializedObserver.onError(SerializedObserver.java:159) 
  at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:79) 
  at rx.internal.operators.OperatorTakeUntil$1.onError(OperatorTakeUntil.java:49) 
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191) 
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162) 
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
  at android.os.Handler.handleCallback(Handler.java:739) 
  at android.os.Handler.dispatchMessage(Handler.java:95) 
  at android.os.Looper.loop(Looper.java:148) 
  at android.app.ActivityThread.main(ActivityThread.java:5438) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
  at android.util.Log.getStackTraceString(Log.java:342)
  at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:60)
  at com.android.internal.os.RuntimeInit.access$200(RuntimeInit.java:44)
  at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:86)
  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
  at android.os.Handler.handleCallback(Handler.java:739) 
  at android.os.Handler.dispatchMessage(Handler.java:95) 
  at android.os.Looper.loop(Looper.java:148) 
  at android.app.ActivityThread.main(ActivityThread.java:5438) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
Caused by: cn.com.xgo.dealer.two.net.ErrorThrowable
  at cn.com.xgo.dealer.two.protocol.base.BaseProtocol.setData(BaseProtocol.java:69)
  at cn.com.xgo.dealer.two.protocol.base.BaseProtocol$1.call(BaseProtocol.java:44)
  at cn.com.xgo.dealer.two.protocol.base.BaseProtocol$1.call(BaseProtocol.java:34)
  at rx.Observable.unsafeSubscribe(Observable.java:8098)
  at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4de6919 is not valid; is your activity running?
  at android.view.ViewRootImpl.setView(ViewRootImpl.java:575)
  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:313)
  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
  at android.app.Dialog.show(Dialog.java:322)
  at cn.com.xgo.dealer.two.view.HintDialog$1.run(HintDialog.java:87)
  at android.app.Activity.runOnUiThread(Activity.java:5573)
  at cn.com.xgo.dealer.two.view.HintDialog.show(HintDialog.java:82)
  at cn.com.xgo.dealer.two.parser.JsonParser.fromError(JsonParser.java:92)
  at cn.com.xgo.dealer.two.activity.OrderDetailActivity$6.call(OrderDetailActivity.java:227)
  at cn.com.xgo.dealer.two.activity.OrderDetailActivity$6.call(OrderDetail
```

The following code is an exception

``` java
protected Observable<String> createObservable(final String url, final String method, final XgoRequestParams params) {

        return Observable.create(new Observable.OnSubscribe<String>() {
            @Override
            public void call(Subscriber<? super String> subscriber) {
                Request request = XgoHttpClient.getClient().getRequest(url, method, params);

                try {
                    Response response = XgoHttpClient.getClient().execute(request);
                    if (response != null && response.isSuccessful()) {
                        setData(subscriber, response.body().string(), true);
                    } else {
                        assert response != null;
                        setData(subscriber, response.body().string(), false);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    subscriber.onError(e);
                    subscriber.onCompleted();
                }
            }
        }).subscribeOn(Schedulers.io());
    }
```

``` java
protected void setData(Subscriber<? super String> subscriber, String json, boolean isSuccess) {
        if (TextUtils.isEmpty(json)) {
            subscriber.onError(new Throwable("not data"));
            subscriber.onCompleted();
            return;
        }
        if (isSuccess) {
            subscriber.onNext(json);
            subscriber.onCompleted();
        } else {
            subscriber.onError(new ErrorThrowable(json)); //**** An exception is thrown here ***
            subscriber.onCompleted();
        }
    }
```

**Comment by artem-zinnatullin** [comment]
If you read stacktrace carefully, you'll find that
"cn.com.xgo.dealer.two.net.ErrorThrowable
at
cn.com.xgo.dealer.two.protocol.base.BaseProtocol.setData(BaseProtocol.java:69)"
caused the problem.

RxJava simply delivers it to you through ton of calls.

Doesn't look like RxJava problem, please close issue if you'll find that
it's not related to RxJava.

**Comment by akarnokd** [comment]
You didn't use the `subscribe(Action1<T>, Action<Throwable>)` when consuming the sequence and you get the `OnErrorNotImplementedException`.

**Comment by cn-ljb** [comment]
subscriber.onError(new ErrorThrowable(json));

I can't understand why this line of code throws an exception, sometimes can run normally.
I hope that in the request fails, to get the HTTP data in the body.

**Comment by zsxwing** [comment]
@cn-ljb it's because your subscriber's `onError` throws an exception which was saying the Activity was gone. 

> Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4de6919 is not valid; is your activity running?

I guess your probably forget to unsubscribe it in `onDestroy`.

**Comment by cn-ljb** [comment]
I have to use RxLifecycle ,But in the open when the activity is thrown exception And downs
Thank you , I'll think it over
