### ISSUE TITLE
2.x: ObservableRefCountTest > testRepeat FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4015]
```
io.reactivex.internal.operators.observable.NbpOnSubscribeRefCountTest > testRepeat FAILED
    java.lang.AssertionError: Subscriber still running! Error(s) present: [java.lang.IllegalStateException: onSubscribe not called in proper order]
        at io.reactivex.observers.TestObserver.fail(TestObserver.java:302)
        at io.reactivex.observers.TestObserver.assertNoErrors(TestObserver.java:365)
        at io.reactivex.internal.operators.observable.NbpOnSubscribeRefCountTest.testRepeat(NbpOnSubscribeRefCountTest.java:197)
        Caused by:
        io.reactivex.exceptions.CompositeException
            at io.reactivex.observers.TestObserver.fail(TestObserver.java:303)
            ... 2 more
            Caused by:
            io.reactivex.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                Caused by:
                java.lang.IllegalStateException: onSubscribe not called in proper order
```

**Comment by akarnokd** [comment]
Should be resolved in #4506.
