### ISSUE TITLE
2.x: Flaky test NbpOperatorWindowWithSizeTest.testWindowUnsubscribeOverlappingAsyncSource

### ISSUE THREAD

**Issue by JakeWharton** [ReactiveX/RxJava#4054]
```
io.reactivex.internal.operators.observable.NbpOperatorWindowWithSizeTest > testWindowUnsubscribeOverlappingAsyncSource FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.reactivex.internal.operators.observable.NbpOperatorWindowWithSizeTest.testWindowUnsubscribeOverlappingAsyncSource(NbpOperatorWindowWithSizeTest.java:188)
```

From https://travis-ci.org/ReactiveX/RxJava/builds/139345308

**Comment by JakeWharton** [comment]
https://travis-ci.org/ReactiveX/RxJava/builds/139590872

Also the non-overlapping test failed this time

```
io.reactivex.internal.operators.observable.NbpOperatorWindowWithSizeTest > testWindowUnsubscribeNonOverlappingAsyncSource FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.reactivex.internal.operators.observable.NbpOperatorWindowWithSizeTest.testWindowUnsubscribeNonOverlappingAsyncSource(NbpOperatorWindowWithSizeTest.java:145)
```

**Comment by akarnokd** [comment]
A small hiccup and the sourc range runs to completion, failing the assumption it will be cancelled in time. Having no backpressure doesn't really help. I'm thinking about commenting out those two final checks in the methods.

**Comment by akarnokd** [comment]
Didn't happen for some time now.
