### ISSUE TITLE
2.x: NbpOperatorConcatTest > testIssue2890NoStackoverflow FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4109]
Looks like a timeout issue.

```
io.reactivex.internal.operators.observable.NbpOperatorConcatTest > testIssue2890NoStackoverflow FAILED
    java.lang.AssertionError: expected:<5000> but was:<3797>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.reactivex.internal.operators.observable.NbpOperatorConcatTest.testIssue2890NoStackoverflow(NbpOperatorConcatTest.java:730)
```

**Comment by akarnokd** [comment]
Closing via #4139
