### ISSUE TITLE
2.x: FlowableReplayTest > testAsyncComeAndGo 

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4138]
Could be an bug with `replay()` or the fact that it goes lockstep and doesn't request in time if the further downstream (observeOn) is slow.

```
io.reactivex.internal.operators.flowable.FlowableReplayTest > testAsyncComeAndGo FAILED
    java.lang.AssertionError: Error(s) present: [io.reactivex.exceptions.MissingBackpressureException: Can't deliver value 236 due to lack of requests]
        at io.reactivex.subscribers.TestSubscriber.fail(TestSubscriber.java:397)
        at io.reactivex.subscribers.TestSubscriber.assertNoErrors(TestSubscriber.java:465)
        at io.reactivex.internal.operators.flowable.FlowableReplayTest.testAsyncComeAndGo(FlowableReplayTest.java:1022)
        Caused by:
        io.reactivex.exceptions.CompositeException
            at io.reactivex.subscribers.TestSubscriber.fail(TestSubscriber.java:398)
            ... 2 more
            Caused by:
            io.reactivex.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                Caused by:
                io.reactivex.exceptions.MissingBackpressureException: Can't deliver value 236 due to lack of requests
```

**Comment by akarnokd** [comment]
Closing via #4139

**Comment by akarnokd** [comment]
It's [back](https://travis-ci.org/ReactiveX/RxJava/builds/144412254#L3408).

**Comment by akarnokd** [comment]
Closing again. Haven't encountered this for a while.
