### ISSUE TITLE
test failed in testMergeAsync

### ISSUE THREAD

**Issue by chanx2** [ReactiveX/RxJava#4170]
I got this test failed in v1.1.6, is it a known issue?

here is the output:

> testMergeAsync => Received: 524  Emitted: 640 / 1

and here is the stack:

> java.lang.AssertionError
>   at org.junit.Assert.fail(Assert.java:92)
>   at org.junit.Assert.assertTrue(Assert.java:43)
>   at org.junit.Assert.assertTrue(Assert.java:54)
>   at rx.BackpressureTests.testMergeAsync(BackpressureTests.java:122)
>        ...

**Comment by akarnokd** [comment]
That test tends to fail if there is a hiccup in the main thread. I haven't seen it in our tests for some time now.

**Comment by chanx2** [comment]
I'm trying to build RxJava from source code for my project but unluckily it always failed somehow , I've seen several failed ut cases these two days,  guess I should just ignore them first as a workaround :(

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
