### ISSUE TITLE
testRetryWithBackpressureParallel failed

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4175]
Just [failed on Travis](https://travis-ci.org/ReactiveX/RxJava/builds/143126717). Last time it was some time ago.

```
rx.internal.operators.OperatorRetryTest > testRetryWithBackpressureParallel FAILED
    java.lang.AssertionError: Data content mismatch: 15={beginningEveryTime x 128}
        at org.junit.Assert.fail(Assert.java:88)
        at rx.internal.operators.OperatorRetryTest.testRetryWithBackpressureParallel(OperatorRetryTest.java:771)
```

**Comment by akarnokd** [comment]
Closing as appears to be fixed with #4241.
