### ISSUE TITLE
2.x: BlockingObservableNextTest > testSingleSourceManyIterators FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4369]
```
io.reactivex.internal.operators.observable.BlockingObservableNextTest > testSingleSourceManyIterators FAILED
    java.lang.AssertionError: 2th iteration next expected:<7> but was:<9>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at io.reactivex.internal.operators.observable.BlockingObservableNextTest.testSingleSourceManyIterators(BlockingObservableNextTest.java:309)
```

The operator itself is quite flaky: you receive an event if you have demand at the same time there is a value available. If you happen to process it slower, the producer may send and drop values because no one is waiting for it. For this reason, it is not possible to test this operator synchronously (without hacking into the operator): a take will block the emitter and an emitter will drop if there is no take.

**Comment by akarnokd** [comment]
This is a timing related bug which occasionally happens on Travis or locally.
