### ISSUE TITLE
how to resolve this problem for "Caused by java.util.ConcurrentModificationException"

### ISSUE THREAD

**Issue by maoai-xianyu** [ReactiveX/RxJava#4374]
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.trello.rxlifecycle.components.support.RxAppCompatActivity.(RxAppCompatActivity.java)
       at java.lang.Class.newInstanceImpl(Class.java)
       at java.lang.Class.newInstance(Class.java:1208)
       at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2114)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248)
       at android.app.ActivityThread.access$800(ActivityThread.java:136)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5020)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.util.ConcurrentModificationException
       at java.util.Hashtable$HashIterator.nextEntry(Hashtable.java:727)
       at java.util.Hashtable$EntryIterator.next(Hashtable.java:778)
       at java.util.Hashtable$EntryIterator.next(Hashtable.java:776)
       at rx.plugins.RxJavaPlugins.getPluginImplementationViaProperty(RxJavaPlugins.java:177)
       at rx.plugins.RxJavaPlugins.getObservableExecutionHook(RxJavaPlugins.java:130)
       at rx.Observable.(Observable.java)
       at com.trello.rxlifecycle.components.support.RxAppCompatActivity.(RxAppCompatActivity.java)
       at java.lang.Class.newInstanceImpl(Class.java)
       at java.lang.Class.newInstance(Class.java:1208)
       at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2114)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248)
       at android.app.ActivityThread.access$800(ActivityThread.java:136)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5020)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by artem-zinnatullin** [comment]
This is problem in RxLifecycle and not in RxJava, please file a bug there and close it here :)

> at com.trello.rxlifecycle.components.support.RxAppCompatActivity.(RxAppCompatActivity.java)

**Comment by akarnokd** [comment]
There are other libraries that modify the System properties concurrently. We tried to remedy this in an RxJava version so please make sure you use an up to date version (1.1.9 as of now).

**Comment by artem-zinnatullin** [comment]
Ah right, it's system property modification while iterating, then it should be fixed in RxJava 1.1.3

**Comment by maoai-xianyu** [comment]
what? Fix this problem use for 1.1.9 version or  1.1.3 version? Please confirm.

**Comment by akarnokd** [comment]
Always use the latest version, 1.1.9 currently.

**Comment by maoai-xianyu** [comment]
OK. Thanks. I try it. Hope it is OK.
