### ISSUE TITLE
CompletableTest > timerTestScheduler FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4470]
```
io.reactivex.completable.CompletableTest > timerTestScheduler FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 1000 milliseconds
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2499)
        at java.lang.Class.getDeclaredField(Class.java:1951)
        at java.util.concurrent.PriorityBlockingQueue.<clinit>(PriorityBlockingQueue.java:945)
        at io.reactivex.schedulers.TestScheduler.<init>(TestScheduler.java:31)
        at io.reactivex.completable.CompletableTest.timerTestScheduler(CompletableTest.java:1141)
```

**Comment by akarnokd** [comment]
Could be due Travis utilization. Closing for now.
