### ISSUE TITLE
Chain of Causes for CompositeException In Order Received =>

### ISSUE THREAD

**Issue by hekaidaqaz** [ReactiveX/RxJava#4539]
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5120)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
at dalvik.system.NativeStart.main(Native Method)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:186)
at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:205)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
... 9 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred.
... 16 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
at com.tencent.wxop.stat.a.c.a(Unknown Source)
at com.tencent.wxop.stat.a.c.<init>(Unknown Source)
at com.tencent.wxop.stat.n.uncaughtException(Unknown Source)
at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
at rx.internal.schedulers.ScheduledAction.signalError(ScheduledAction.java:68)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
... 9 more
Caused by: java.lang.NullPointerException
at com.uto.passenger.view.fragment.MainContentView$4$1.onNext(MainContentView.java:271)
at com.uto.passenger.view.fragment.MainContentView$4$1.onNext(MainContentView.java:261)
at com.uto.passenger.subscribers.ProgressSubscriber.onNext(ProgressSubscriber.java:182)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
... 9 more
Caused by: java.lang.NullPointerException
at com.uto.passenger.view.base.BaseFragment.showToast(BaseFragment.java:138)
at com.uto.passenger.view.base.BaseFragment.checkCode(BaseFragment.java:104)
at com.uto.passenger.view.fragment.MainContentView.access$300(MainContentView.java:73)
at com.uto.passenger.view.fragment.MainContentView$4$1.onFail(MainContentView.java:276)
at com.uto.passenger.subscribers.ProgressSubscriber.onError(ProgressSubscriber.java:166)
at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:205)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
... 12 more
```

Above when I encounter problems of exception, don't know what is problem

**Comment by akarnokd** [comment]
```
Caused by: java.lang.NullPointerException
at com.uto.passenger.view.fragment.MainContentView$4$1.onNext(MainContentView.java:271)
at com.uto.passenger.view.fragment.MainContentView$4$1.onNext(MainContentView.java:261)
at com.uto.passenger.subscribers.ProgressSubscriber.onNext(ProgressSubscriber.java:182)
```

```
Caused by: java.lang.NullPointerException
at com.uto.passenger.view.base.BaseFragment.showToast(BaseFragment.java:138)
at com.uto.passenger.view.base.BaseFragment.checkCode(BaseFragment.java:104)
at com.uto.passenger.view.fragment.MainContentView.access$300(MainContentView.java:73)
at com.uto.passenger.view.fragment.MainContentView$4$1.onFail(MainContentView.java:276)
at com.uto.passenger.subscribers.ProgressSubscriber.onError(ProgressSubscriber.java:166)
```

**Comment by hekaidaqaz** [comment]
This must be in the main thread

**Comment by akarnokd** [comment]
Some reference in your code is null, maybe because the activity/fragment gets destroyed before the sequence emits a value or error. You should probably check for null first in your code before calling other methods.

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.

**Comment by desgraci** [comment]
@akarnokd Had the same issue, was on the IO thread before calling the subscriber, on my onError I touched the UI and I wasn't getting the notification for that, but this composite error, I think that was what @hekaidaqaz was trying to mention on his comment. Was able to reproduce it on io.reactivex:rxandroid:1.2.0.
