### ISSUE TITLE
FlowableConcatMapEagerTest > testAsynchronousRun FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4620]
```
io.reactivex.internal.operators.flowable.FlowableConcatMapEagerTest > testAsynchronousRun FAILED
    java.lang.AssertionError: Value counts differ; Expected: 2000, Actual: 1184 (latch = 1, values = 1184, errors = 0, completions = 0)
        at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:132)
        at io.reactivex.observers.BaseTestConsumer.assertValueCount(BaseTestConsumer.java:389)
        at io.reactivex.internal.operators.flowable.FlowableConcatMapEagerTest.testAsynchronousRun(FlowableConcatMapEagerTest.java:583)
```

**Comment by akarnokd** [comment]
Closing via #4751
