### ISSUE TITLE
Exception in RxJava and cannot debug the root cause

### ISSUE THREAD

**Issue by masterlittle** [ReactiveX/RxJava#4655]
I am getting this exception in my app. There is just one timer in the whole app and I have applied BackPressureDrop just after interval() and am logging the error in my subscribers' onError() but this crash keeps on repeating. Please help!!

```
Fatal Exception: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5300)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by rx.exceptions.OnErrorNotImplementedException
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
       at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:276)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5300)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by rx.exceptions.MissingBackpressureException
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:162)
       at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
       at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
       at rx.Scheduler$Worker$1.call(Scheduler.java:134)
       at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:187)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by akarnokd** [comment]
This indicates you didn't apply the `onBackpressureDrop` at the right place:

```
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:162)
       at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
       at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
```

Could you post the code you are using?

**Comment by masterlittle** [comment]
Here. Also how can I know where in my app is the error coming from because I'm not receiving the location of the class of the crash in the stackTrace.

public class CreateTimerObservable {

```
private CreateTimerObservable() {
}

public static Subscription createTimer(long expiryTime, @NonNull Subscriber<Long> subscriber) {
    return Observable.interval(1, 10, TimeUnit.SECONDS)
            .onBackpressureDrop()
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(subscriber);
}
```

}

**Comment by akarnokd** [comment]
Use `RxJavaHooks.enableAssemblyTracking()` and more info is appended to the crash.

**Comment by masterlittle** [comment]
Is this code correct and would it help in debugging?

public static Subscription createTimer(long expiryTime, @NonNull Subscriber<Long> subscriber) {
        RxJavaHooks.enableAssemblyTracking();
        try {
            return Observable.interval(10, TimeUnit.SECONDS)
                    .onBackpressureDrop()
                    .doOnError(Crashlytics::logException)
                    .retry()
                    .observeOn(AndroidSchedulers.mainThread())
                    .onErrorReturn(throwable -> 1L)
                    .subscribe(subscriber);
        } finally {
            RxJavaHooks.resetAssemblyTracking();
        }
    }

**Comment by akarnokd** [comment]
No because here you already know where your operators are. Call `RxJavaHooks.enableAssemblyTracking()` early in your application and make the crash happen.

**Comment by masterlittle** [comment]
Ohh. So I should enable the hook as soon as the app starts? When do I rest the hook then? Or should I set it onCreate() on each activity?

**Comment by akarnokd** [comment]
Enable it in `onCreate` and disable it in `onDestroy` for example.

**Comment by masterlittle** [comment]
Ohh nice.. Thanks a lot. This should be a great help.

**Comment by masterlittle** [comment]
Hi, I have added the RxJavahooks to the code but I'm not getting any additional trace. Here is the complete log file of the crash.

[(https://drive.google.com/open?id=0B_0j5CZdCOUDbHo2Rm10bXlqLUk)](https://drive.google.com/open?id=0B_0j5CZdCOUDbHo2Rm10bXlqLUk)

**Comment by akarnokd** [comment]
You have an `interval().subscribeOn().observeOn()` chain in your codebase that overflows. Indeed the log doesn't show anything; do you have a `RxJavaHooks.reset()` somewhere that gets called? Plus, somewhere you have only `subscribe(Action1)` that doesn't handle the error you are receiving.

I can't help you further without looking at some actual code.

**Comment by masterlittle** [comment]
```
private class ConfirmPickedOrdersSubscriber extends Subscriber<String> {
        @Override
        public void onCompleted() {

        }

        @Override
        public void onError(Throwable throwable) {
            iOmsPickedOrderDetailsActivity.hideLoader();
            iOmsPickedOrderDetailsActivity.enableConfirmButton();

            if (throwable instanceof HttpException) {
                iOmsPickedOrderDetailsActivity.hideLoader();
                ErrorHandlerMapper errorHandlerMapper = null;
                try {
                    ResponseBody responseBody = ((HttpException) throwable).response().errorBody();
                    errorHandlerMapper = new ObjectMapper().readValue(responseBody.string(), ErrorHandlerMapper.class);
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
                ConfirmPickedOrdersErrorHandler confirmPickedOrdersErrorHandler = new ConfirmPickedOrdersErrorHandler();
                if (errorHandlerMapper != null) {
                    confirmPickedOrdersErrorHandler.processError(((HttpException) throwable).code(),
                            getClass().getSimpleName(),
                            errorHandlerMapper.getMessage());
                }
            }
        }

        @Override
        public void onNext(String message) {
            if (iOmsPickedOrderDetailsActivity != null) {
                iOmsPickedOrderDetailsActivity.enableConfirmButton();
                iOmsPickedOrderDetailsActivity.hideLoader();
                iOmsPickedOrderDetailsActivity.showSuccessBox(message);
                Observable.interval(2, TimeUnit.SECONDS)
                        .subscribeOn(Schedulers.computation())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(aLong -> {
                            if (iOmsPickedOrderDetailsActivity != null) {
                                iOmsPickedOrderDetailsActivity.goBack();
                            }
                        });

            }
        }
    }

```

I had this code which I seem to have missed. goBack() just finishes the activity. So i call interval in onNext() but am not unsubscribing it in onDestroy which may have kept the subscription alive. I think this must be the problem but only thing is I have implemented onError() in it. Also I'm using a new computation(0 thread when interval implicitly creates one. Stupid me!!

**Comment by akarnokd** [comment]
``` java
        @Override
        public void onNext(String message) {
            if (iOmsPickedOrderDetailsActivity != null) {
                iOmsPickedOrderDetailsActivity.enableConfirmButton();
                iOmsPickedOrderDetailsActivity.hideLoader();
                iOmsPickedOrderDetailsActivity.showSuccessBox(message);
                Observable.interval(2, TimeUnit.SECONDS)

                     .onBackpressureDrop()   // <----------------------------------------------

                     .subscribeOn(Schedulers.computation())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(aLong -> {
                            if (iOmsPickedOrderDetailsActivity != null) {
                                iOmsPickedOrderDetailsActivity.goBack();
                            }
                        }

                        , e -> e.printStackTrace()       // <------------------------------------

                        );

            }
        }
```

**Comment by masterlittle** [comment]
Ohh yes. Missed this. Thanks! Should I remove the subscribeOn() or is it correct?

**Comment by akarnokd** [comment]
Completely unnecessary at that point.

**Comment by masterlittle** [comment]
Thanks

**Comment by ZacSweers** [comment]
I think this can be closed now
