### ISSUE TITLE
MaybeAmbTest > innerErrorRace FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4750]
```
io.reactivex.internal.operators.maybe.MaybeAmbTest > innerErrorRace FAILED
    java.lang.AssertionError: io.reactivex.exceptions.MissingBackpressureException: Could not deliver window due to lack of requests
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.reactivex.TestHelper.assertError(TestHelper.java:148)
        at io.reactivex.internal.operators.maybe.MaybeAmbTest.innerErrorRace(MaybeAmbTest.java:104)
```

**Comment by akarnokd** [comment]
This could be a window test that didn't finish or wasn't cancel properly and showed up in this test's RxJavaPlugins.onError hook.

**Comment by akarnokd** [comment]
Closing via #4755
