### ISSUE TITLE
java.lang.NoClassDefFoundError: rx.internal.util.SubscriptionList

### ISSUE THREAD

**Issue by zun0817** [ReactiveX/RxJava#4785]
java.lang.NoClassDefFoundError: rx.internal.util.SubscriptionList , 

How to solve ?

**Comment by akarnokd** [comment]
Could you give us some more context?

**Comment by zun0817** [comment]
10-31 16:13:29.185 3958-3958/com.amplify.alfred E/CrashReport: sys default last handle start!
10-31 16:13:29.185 3958-3958/com.amplify.alfred E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  java.lang.NoClassDefFoundError: rx.internal.util.SubscriptionList
                                                                      at rx.Subscriber.<init>(Subscriber.java:81)
                                                                      at rx.Subscriber.<init>(Subscriber.java:46)
                                                                      at com.amplify.alfred.http.ProgressSubscriber.<init>(ProgressSubscriber.java:43)
                                                                      at com.amplify.alfred.fragment.LoginFragment.onClick(LoginFragment.java:230)
                                                                      at com.amplify.alfred.fragment.LoginFragment$$ViewBinder$3.doClick(LoginFragment$$ViewBinder.java:46)
                                                                      at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                      at android.view.View.performClick(View.java:4476)
                                                                      at android.view.View$PerformClick.run(View.java:18799)
                                                                      at android.os.Handler.handleCallback(Handler.java:730)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                      at android.os.Looper.loop(Looper.java:177)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:525)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by zun0817** [comment]
compile 'io.reactivex:rxjava:1.1.5'
    compile 'io.reactivex:rxandroid:1.2.0'
    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.0.2'

**Comment by akarnokd** [comment]
Are you using proguard?

**Comment by zun0817** [comment]
Yeah, I'm using proguard.

```
-dontwarn rx.internal.**
-keep class rx.internal.**{*;}
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-dontwarn retrofit.**
-keep class retrofit.** { *; }
-keepattributes Signature
-keepattributes Exceptions
-keepclasseswithmembers class * {
    @retrofit.http.* <methods>;
}
-keep class com.google.inject.** { *; }
-keep class org.apache.http.** { *; }
-keep class javax.inject.** { *; }
-keep class retrofit.** { *; }
-keep class in.srain.*
-dontwarn org.apache.http.**
-dontwarn retrofit.**
```

**Comment by zun0817** [comment]
How to solve this problem?

**Comment by akarnokd** [comment]
I'm not experienced with ProGuard. Search for RxJava ProGuard rules and @artem-zinnatullin 's project should work for example.

**Comment by Mauin** [comment]
To check if ProGuard is the issue try running a build without ProGuard and see if that succeeds. @zun0817

**Comment by zun0817** [comment]
I have tried, and reported the same exception, my test machine system version is Android 4.3

**Comment by zun0817** [comment]
Android5.0 Above version,This problem will not happen

**Comment by zun0817** [comment]
I have tried, and reported the same exception, my test machine system version is Android 4.3,but Android5.0 Above version,This problem will not happen. @Mauin

**Comment by zun0817** [comment]
I want to ask my question how to solve? @Mauin

**Comment by akarnokd** [comment]
Maybe there is a library conflict in your project or RxJava's jar is damaged. Could you just create a project with nothing but referencing SubscriptionList?

**Comment by artem-zinnatullin** [comment]
If problem is not happening on Android 5.0 and above it almost 100% means
that you use MultiDex and don't manually load secondary dex files. Please
find documentation about MultiDex and use multidex-support library to load
dex files properly on Android below 5.0.

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
