### ISSUE TITLE
IncompatibleClassChangeError while using RxJava+ Retrofit 2  occurs sometimes

### ISSUE THREAD

**Issue by anup316** [ReactiveX/RxJava#4797]
I am having an activity where i am replacing the container with several fragments. Every fragments has a network call to fetch data with the help of retrofit. 

I get this error sometimes when i do the call and update the view. I checked the logs and i found that the call was done but then it crashed. Is it because that the call response is coming earlier than the transaction is still executing? I get this sometimes,  and after cleaning the build it does not happen. 

Stack trace
```
Fatal Exception: java.lang.IncompatibleClassChangeError: Class 'com.mgrm.schoolapp.viewattendance.-$Lambda$3' does not implement interface 'rx.functions.Func1' in call to 'java.lang.Object rx.functions.Func1.call(java.lang.Object)' (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
       at rx.Observable.compose(Observable.java:294)
       at com.mgrm.schoolapp.viewattendance.AttendanceChartInteractorImpl.fetchYearlyAttendance(AttendanceChartInteractorImpl.java:34)
       at com.mgrm.schoolapp.viewattendance.AttendanceChartPresenterImpl.start(AttendanceChartPresenterImpl.java:45)
       at com.mgrm.schoolapp.viewattendance.AttendanceChartFragment.onStart(AttendanceChartFragment.java:105)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2113)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1151)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

When the network response delays for few seconds , the error never occurs but when the response is too fast such as 150ms then it crashes. I am testing it in genymotion emulator. DO let me know if you have any idea? .

**Comment by JakeWharton** [comment]
Are you using instant run? This isn't a library problem as evidenced by the
fact that your code is what's failing so that just leaves whatever build
tools you're using.

**Comment by anup316** [comment]
Java 8 with jack enabled. I am currently using the latest build tool 25.0.0.  The problem is that this issue occurs sometimes and the same code runs when i rebuild the project couple of times.

**Comment by JakeWharton** [comment]
That sounds suspiciously like instant run.

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.

**Comment by koooooooooo** [comment]
Really bat that it is closed.
Appeared with buildToolsVersion "25.0.2" same

**Comment by JZHeadley** [comment]
I just had a similiar issue and disabling jack appeared to fix it.

**Comment by anup316** [comment]
Yes apparantely it is working without JACK as the JACK compiler does not
create the indermediate classes.

On Sun, Jul 30, 2017 at 6:54 AM, J. Zephyr Headley <notifications@github.com
