### ISSUE TITLE
2.x: NPE - the mapper function returned a null value; Can't find where in my app crash originates

### ISSUE THREAD

**Issue by nevi-me** [ReactiveX/RxJava#4804]
Thanks for the great library!

I upgraded RxJava to 2.x on my Android app a few days ago, and ever since, I keep getting a `NullPointerException: the mapper function returned a null value`. The problem is that the stack trace on the exception only points to `io.reactivex` and `java.lang.Thread` amongst others, so I can't trace where in my app I'm getting the error.

Does anyone have suggestions on what could be causing the error? Exception is thrown by `ObjectHelper`. The exception is thrown from a computation scheduler pool, and the Android debugger doesn't lead me anywhere to my app as mentioned.

```
11-04 03:52:24.575 19231-20317/app E/UncaughtException: java.lang.NullPointerException: The mapper function returned a null value.
                                                                                    at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
                                                                                    at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
                                                                                    at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)
                                                                                    at io.reactivex.internal.operators.observable.ObservableSampleTimed$SampleTimedObserver.run(ObservableSampleTimed.java:109)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:154)
                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818)
11-04 03:52:25.000 19231-20317/app E/AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-6
                                                                             Process: app, PID: 19231
                                                                             java.lang.NullPointerException: The mapper function returned a null value.
                                                                                 at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
                                                                                 at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
                                                                                 at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)
                                                                                 at io.reactivex.internal.operators.observable.ObservableSampleTimed$SampleTimedObserver.run(ObservableSampleTimed.java:109)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                 at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:154)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)
```

**Comment by digitalbuddha** [comment]
I believe your issue is due to a change between rx1 and rx2.  Rxjava2 does
not support emitting a null value. See the section in nulls here:
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0

**Comment by nevi-me** [comment]
Thanks @digitalbuddha, I saw that when I was going through the documentation. I presume a good suspect would be `Iterable.map()` where instead of returning a value I either don't return anything, or return a null without noticing.

I'm checking all my instances where I transform Observables. I suppose what would help is if I could find where the problem's being triggered 😃

**Comment by digitalbuddha** [comment]
Couple of other suggestions are to return an Optional.of(value) or Optional.absent.  You can also return new Object instead of returning null.

**Comment by nevi-me** [comment]
Actually, my problems might run deeper. I use Kotlin, and since I can pass nullables around, I normally write some code as 

```
Observable.just(object).subscribe(Consumer<Object?> {
  override fun accept(object: Object?) {
    // or more conventional in Kotlin: accept(object: Any?)
  }
})
```

So I have subscriptions that emit null values in my code.

This was all happening in the background, so I couldn't find the suspect, but I found what was causing my crashes.

I'll use Optional in my Java 8 projects, but for the Android app I'm compiling with Java 7, so I'll return Object, and remove the nullable types in my Kotlin code.

Thanks for the help. I'll close the issue.

**Comment by ivnsch** [comment]
@nevi-me @digitalbuddha the solution for Koltin on Android is then to return `Object()`... this, basically, removes the type safety of the observable, and it needs type checks / casts all the way down the chain... right?

Edit: And it's also not possible to return an empty list .............?
 `io.reactivex.exceptions.OnErrorNotImplementedException: List is empty.`

I also tried adding a library that providers full optionals, i.e. return a custom `Option.None`, but that also doesn't work!

**Comment by nevi-me** [comment]
@i-schuetz back then I wasn't familiar with a lot of things. I now use `Maybe` where the value is optional

**Comment by ivnsch** [comment]
@nevi-me is `Maybe` an appropriate substitute? I also saw it but wasn't sure. The documentations says "Represents a deferred computation and emission of a maybe value or exception"...?

How would you represent `Some` and `None`? `just` and `never` perhaps?

Or for things like `isDefined()` -> `blockingGet() != null`...?
