### ISSUE TITLE
How to stop sending data from Flowable.fromIterable.

### ISSUE THREAD

**Issue by yubaokang** [ReactiveX/RxJava#4817]
```java
java.net.UnknownHostException: Unable to resolve host "nshop.goujiawang.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:440)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
	at java.net.InetAddress.getAllByName(InetAddress.java:215)
	at okhttp3.Dns$1.lookup(Dns.java:39)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:31)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:31)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:156)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:175)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```
```java
upload = Flowable.fromIterable(view.getUploadFiles())
                .filter(new Predicate<String>() {
                    @Override
                    public boolean test(String s) {
                        L.i("-------------1111");
                        return !TextUtils.isEmpty(s);
                    }
                })
                .map(new Function<String, RequestBody>() {
                    @Override
                    public RequestBody apply(String s) throws Exception {
                        L.i("-------------2222");
                        return UpLoadUtils.getRequestBody(s);
                    }
                })
                .observeOn(Schedulers.io())
                .flatMap(new Function<RequestBody, Publisher<BaseRes<UploadImagData>>>() {
                    @Override
                    public Publisher<BaseRes<UploadImagData>> apply(RequestBody requestBody) throws Exception {
                        L.i("-------------3333");
                        return RServices.get().uploadImg(view.getJSessionId(), requestBody);
                    }
                })
                .observeOn(AndroidSchedulers.mainThread())
                .doOnError(new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        L.i("-------------4444");
                        upload.dispose();
                        view.dismissDialog();
                        T.show(context, context.getString(R.string.network_not_well));
                    }
                })
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(new ResourceSubscriber<BaseRes<UploadImagData>>() {
                    @Override
                    public void onNext(BaseRes<UploadImagData> baseRes) {
                        view.showDialogProgress("正在上传图片", "第" + ++current + "张");
                        picPaths.add(baseRes.getResult().getId());
                    }

                    @Override
                    public void onError(Throwable t) {
                        L.i("-------------5555");
//                        upload.dispose();
                        view.dismissDialog();
                        T.show(context, context.getString(R.string.network_not_well));
                    }

                    @Override
                    public void onComplete() {
                        submitMaterialQuality(picPaths);
                    }
                });
```
Android 6.0.1 & RxJava2

I close network,and execute 'upload' 10 times. this error happened.
I used doOnError to catch the error, if  I execute less times, it would not happened.but much times,it happened.I think if catching error and stop sending data,it would not happened.
how to stop Flowable sending data?

This problem bothering me for a long time, can helping me?

**Comment by akarnokd** [comment]
The error is with some name lookup inside Okio: `java.net.UnknownHostException: Unable to resolve host "nshop.goujiawang.com": No address associated with hostname` and doesn't appear to be related to RxJava.

> how to stop Flowable sending data?

Please read about `takeUntil` and `takeWhile`.

**Comment by Mauin** [comment]
If you "close", as in turn off the network then you're going to run into network errors like the one you posted above.

Since your `doOnError` and `onError` callback are very similar as well, I don't see much difference. When the network call runs into an error due to network issues, the Flowable will emit `onError` and thus no data will be transferred anymore (in the case above no data is transferred at all, because the Host cannot be found).

**Comment by yubaokang** [comment]
@Mauin  @akarnokd 
Continuous calls ......
log: 

``` java
11-07 16:30:04.876 $5.test(L:78): -------------1111
11-07 16:30:04.877 $4.apply(L:85): -------------2222
11-07 16:30:04.887 $5.test(L:78): -------------1111
11-07 16:30:04.888 $4.apply(L:85): -------------2222
11-07 16:30:04.889 $5.test(L:78): -------------1111
11-07 16:30:04.889 $4.apply(L:85): -------------2222
11-07 16:30:04.890 $5.test(L:78): -------------1111
11-07 16:30:04.891 $4.apply(L:85): -------------2222
11-07 16:30:04.892 $5.test(L:78): -------------1111
11-07 16:30:04.893 $4.apply(L:85): -------------2222
11-07 16:30:04.894 $5.test(L:78): -------------1111
11-07 16:30:04.894 $4.apply(L:85): -------------2222
11-07 16:30:04.895 $5.test(L:78): -------------1111
11-07 16:30:04.899 22345-22598/ $3.apply(L:93): -------------3333
11-07 16:30:05.220 22345-22598/ $3.apply(L:93): -------------3333
11-07 16:30:05.223 $2.accept(L:101): -------------4444
11-07 16:30:05.476 $5.test(L:78): -------------1111
11-07 16:30:05.477 $4.apply(L:85): -------------2222
11-07 16:30:05.478 22345-22812/ $3.apply(L:93): -------------3333
11-07 16:30:05.478 $5.test(L:78): -------------1111
11-07 16:30:05.478 $4.apply(L:85): -------------2222
11-07 16:30:05.479 $5.test(L:78): -------------1111
11-07 16:30:05.479 $4.apply(L:85): -------------2222
11-07 16:30:05.480 $5.test(L:78): -------------1111
11-07 16:30:05.481 $4.apply(L:85): -------------2222
11-07 16:30:05.482 $5.test(L:78): -------------1111
11-07 16:30:05.483 $4.apply(L:85): -------------2222
11-07 16:30:05.484 $5.test(L:78): -------------1111
11-07 16:30:05.484 $4.apply(L:85): -------------2222
11-07 16:30:05.485 $5.test(L:78): -------------1111
11-07 16:30:05.706 22345-22812/ $3.apply(L:93): -------------3333
11-07 16:30:05.713 $2.accept(L:101): -------------4444
11-07 16:30:05.814 $4.apply(L:85): -------------2222
11-07 16:30:05.819 $4.apply(L:85): -------------2222
11-07 16:30:06.003 22345-22803/ $3.apply(L:93): -------------3333
11-07 16:30:06.016 $2.accept(L:101): -------------4444
11-07 16:30:06.140 $5.test(L:78): -------------1111
11-07 16:30:06.140 $4.apply(L:85): -------------2222
11-07 16:30:06.141 22345-22598/ $3.apply(L:93): -------------3333
11-07 16:30:06.141 $5.test(L:78): -------------1111
11-07 16:30:06.142 $4.apply(L:85): -------------2222
11-07 16:30:06.144 $5.test(L:78): -------------1111
11-07 16:30:06.145 $4.apply(L:85): -------------2222
11-07 16:30:06.147 $5.test(L:78): -------------1111
11-07 16:30:06.148 $4.apply(L:85): -------------2222
11-07 16:30:06.149 $5.test(L:78): -------------1111
11-07 16:30:06.150 $4.apply(L:85): -------------2222
11-07 16:30:06.151 $5.test(L:78): -------------1111
11-07 16:30:06.152 $4.apply(L:85): -------------2222
11-07 16:30:06.152 $5.test(L:78): -------------1111
11-07 16:30:06.329 22345-22598/ $3.apply(L:93): -------------3333
11-07 16:30:06.350 $2.accept(L:101): -------------4444
11-07 16:30:06.494 $5.test(L:78): -------------1111
11-07 16:30:06.495 $4.apply(L:85): -------------2222
11-07 16:30:06.495 22345-22812/ $3.apply(L:93): -------------3333
11-07 16:30:06.496 $5.test(L:78): -------------1111
11-07 16:30:06.496 $4.apply(L:85): -------------2222
11-07 16:30:06.497 $5.test(L:78): -------------1111
11-07 16:30:06.497 $4.apply(L:85): -------------2222
11-07 16:30:06.498 $5.test(L:78): -------------1111
11-07 16:30:06.499 $4.apply(L:85): -------------2222
11-07 16:30:06.499 $5.test(L:78): -------------1111
11-07 16:30:06.500 $4.apply(L:85): -------------2222
11-07 16:30:06.501 $5.test(L:78): -------------1111
11-07 16:30:06.501 $4.apply(L:85): -------------2222
11-07 16:30:06.502 $5.test(L:78): -------------1111
11-07 16:30:06.655 22345-22812/ $3.apply(L:93): -------------3333
11-07 16:30:06.655 $2.accept(L:101): -------------4444
11-07 16:30:06.828 $5.test(L:78): -------------1111
11-07 16:30:06.829 $4.apply(L:85): -------------2222
11-07 16:30:06.830 22345-22803/ $3.apply(L:93): -------------3333
11-07 16:30:06.830 $5.test(L:78): -------------1111
11-07 16:30:06.831 $4.apply(L:85): -------------2222
11-07 16:30:06.832 $5.test(L:78): -------------1111
11-07 16:30:06.833 $4.apply(L:85): -------------2222
11-07 16:30:06.834 $5.test(L:78): -------------1111
11-07 16:30:06.835 $4.apply(L:85): -------------2222
11-07 16:30:06.836 $5.test(L:78): -------------1111
11-07 16:30:06.837 $4.apply(L:85): -------------2222
11-07 16:30:06.838 $5.test(L:78): -------------1111
11-07 16:30:06.838 $4.apply(L:85): -------------2222
11-07 16:30:06.839 $5.test(L:78): -------------1111
11-07 16:30:07.030 22345-22803/ $3.apply(L:93): -------------3333
11-07 16:30:07.063 $2.accept(L:101): -------------4444
11-07 16:30:07.358 $5.test(L:78): -------------1111
11-07 16:30:07.359 $4.apply(L:85): -------------2222
11-07 16:30:07.360 22345-22598/ $3.apply(L:93): -------------3333
11-07 16:30:07.360 $5.test(L:78): -------------1111
11-07 16:30:07.361 $4.apply(L:85): -------------2222
11-07 16:30:07.362 $5.test(L:78): -------------1111
11-07 16:30:07.364 $4.apply(L:85): -------------2222
11-07 16:30:07.365 $5.test(L:78): -------------1111
11-07 16:30:07.366 $4.apply(L:85): -------------2222
11-07 16:30:07.368 $5.test(L:78): -------------1111
11-07 16:30:07.369 $4.apply(L:85): -------------2222
11-07 16:30:07.371 $5.test(L:78): -------------1111
11-07 16:30:07.372 $4.apply(L:85): -------------2222
11-07 16:30:07.373 $5.test(L:78): -------------1111
11-07 16:30:07.516 $5.test(L:78): -------------1111
```

and crash

``` java
 FATAL EXCEPTION: RxCachedThreadScheduler-1
Process: , PID: 22345
java.net.ConnectException: Failed to connect to /192.168.19.116:8099
    at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
    at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.execute(RealCall.java:60)
    at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
    at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)
    at io.reactivex.Observable.subscribe(Observable.java:10151)
    at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
    at io.reactivex.Observable.subscribe(Observable.java:10151)
    at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:31)
    at io.reactivex.Flowable.subscribe(Flowable.java:12172)
    at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:31)
    at io.reactivex.Flowable.subscribe(Flowable.java:12172)
    at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:156)
    at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
    at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:175)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by yubaokang** [comment]
add one premise, I had closed network.

**Comment by Mauin** [comment]
@yubaokang So the app really crashes? It's expected that the exception occurs when network is not available. But it should be handled in `doOnError` or in the `onError` callback, not crash the app.

**Comment by akarnokd** [comment]
This exception is again unrelated to RxJava. You seem to have a network problem in your local environment or there is a bug in `RServices.get().uploadImg` you are not showing that doesn't play well with network resources.

In addition, `doOnError` doesn't handle the exception it just peeks into that and you can perform side-effects at that point. To handle an error, use `onErrorResumeNext`, `onErrorReturn`, `retry` or `retryWhen`.

**Comment by yubaokang** [comment]
@Mauin It crashes......

**Comment by Mauin** [comment]
As @akarnokd mentioned, this is not related to RxJava but it seems like you're not handling errors coming from the HTTP Client correctly.

**Comment by yubaokang** [comment]
@akarnokd but if executes one time ,It is well.and if not use rxjava, it also well. just use rxjava crash.

**Comment by yubaokang** [comment]
When I call continuously, can appear sometimes crash, now I try will not appear again, really strange.

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
