### ISSUE TITLE
1.x: Deadlock in CachedObservable.toBlocking().single().

### ISSUE THREAD

**Issue by orangeven** [ReactiveX/RxJava#4896]
Hi, 

I am experiencing a mysterious deadlock with RxJava. After long analyze I am able to reproduce the problem with a simple code example:
```java
Observable<String> rxTest = Observable.just("Test!").cache();
rxTest
   .map(test -> test + rxTest.toBlocking().single())
   .subscribe(s -> System.out.println(s));
```
The deadlock happens with RxJava 1.2.3. But with 1.0.2 the code is working. 

The example code is simplified to show the problem. In the real production code we try to avoid using toblocking() inside a RxOperator. But sometime the observable will be passed as parameter to the other class, let's call it class Foo. The class Foo will do some operations with the observable and return the final value without observable by calling toBlocking().single(). The class works fine usually. 
But if the Class Foo is used inside the other Observable Operator, then there is trouble. 

Here is the stack trace. 
```
"main" #1 prio=5 os_prio=31 tid=0x00007fe865001800 nid=0x1703 waiting on condition [0x0000700000217000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076b6b0ea8> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at rx.internal.util.BlockingUtils.awaitForComplete(BlockingUtils.java:49)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:461)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at my.test.RxJavaTest.lambda$deadlockOnCachedObservableToBlocking$4(RxJavaTest.java:29)
	at my.test.RxJavaTest$$Lambda$5/112280004.call(Unknown Source)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
	at rx.internal.operators.CachedObservable$ReplayProducer.replay(CachedObservable.java:403)
	at rx.internal.operators.CachedObservable$CacheState.dispatch(CachedObservable.java:220)
	at rx.internal.operators.CachedObservable$CacheState.onNext(CachedObservable.java:191)
	at rx.internal.operators.CachedObservable$CacheState$1.onNext(CachedObservable.java:171)
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
	at rx.Subscriber.setProducer(Subscriber.java:209)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.Observable.subscribe(Observable.java:10086)
	at my.test.RxJavaTest.deadlockOnCachedObservableToBlocking(RxJavaTest.java:34)
	... 
```

**Comment by akarnokd** [comment]
This is expected as you are using `toBlocking()` as well as `single`. `single` requires at least 2 elements (or 1 + completion) but since you block the cache in the emission of its first item via `map` the dataflow can't progress.

If you want to merge in a single value from other sequence, use `flatMap`:

```java
Observable<String> rxTest = Observable.just("Test!").cache();

rxTest.flatMap(v -> rxTest.single().map(w -> v + w))
.subscribe(System.out::println);
```

**Comment by orangeven** [comment]
thanks for the quick answer. :) 

the interesting thing is: once I remove the cache() from the observable. everything works perfect. 
```java
Observable<String> rxTest = Observable.just("Test!");
rxTest
   .map(test -> test + rxTest.toBlocking().single())
   .subscribe(s -> System.out.println(s));
```
Was is different with CachedObservable?

**Comment by akarnokd** [comment]
Now you have two independent emissions, cache was only a single one and deadlocked because of `toBlocking()`.

**Comment by orangeven** [comment]
sorry, I did get your point. can you please explain a little bit more? thanks

**Comment by akarnokd** [comment]
Cache shares the underlying source while it is active and feeds two subscribers, one of it blocking out the other. Without cache, you have 2 independent flows and the blocking consumer one can freely complete.

**Comment by orangeven** [comment]
I just go through the [Blocking-Observable-Operators](https://github.com/ReactiveX/RxJava/wiki/Blocking-Observable-Operators) and find a small different between first() and single()

> first( ) — block until the Observable emits an item, then return the first item emitted by the Observable
single( ) — if the Observable completes after emitting a single item, return that item, otherwise throw an exception

single() expects as you said exact 2 events: onNext and onComplete while first() expects only 1 event: onNext. 

So I changed toBlocking.single() to toBlocking.first(), than everything works fine, also together with CachedObservable. Deadlock is resolved. 

Thanks
