### ISSUE TITLE
FlowablePublishFunctionTest > inputOutputSubscribeRace FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#4902]
```
io.reactivex.internal.operators.flowable.FlowablePublishFunctionTest > inputOutputSubscribeRace FAILED
    java.lang.AssertionError: Value count differs; Expected: 1 [1], Actual: 0 [] (latch = 1, values = 0, errors = 0, completions = 0)
        at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:133)
        at io.reactivex.observers.BaseTestConsumer.assertValues(BaseTestConsumer.java:404)
        at io.reactivex.observers.BaseTestConsumer.assertResult(BaseTestConsumer.java:613)
        at io.reactivex.internal.operators.flowable.FlowablePublishFunctionTest.inputOutputSubscribeRace(FlowablePublishFunctionTest.java:410)
```

**Comment by akarnokd** [comment]
CLosing via #4943
