### ISSUE TITLE
`2.x` strange CalledFromWrongThreadException in my Callable<String>

### ISSUE THREAD

**Issue by buptfarmer** [ReactiveX/RxJava#4922]
Here is my code [myRxJavaExample https://github.com/buptfarmer/edu/blob/master/app/src/main/java/com/chensiwen/edugame/RxJavaExampleActivity.java](https://github.com/buptfarmer/edu/blob/master/app/src/main/java/com/chensiwen/edugame/RxJavaExampleActivity.java)
I am using
```
    compile 'io.reactivex.rxjava2:rxjava:2.0.1'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
```

Basically we will met the CalledFromWrongThreadException when we update UI in a non-ui thread, my rxJava example shows different result; as the code below:

getStringCallable() has **NO** Thread.sleep() in it, update the textview in a non-ui thread, but without the CalledFromWrongThreadException. however, getStringCallable() has the Thread.sleep() met the CalledFromWrongThreadException as expected. 
I don't understand why.
Please give me some help. Thanks.

```    private Callable<String> getStringCallable(final int index) {
        binding.rxTest1.append("getStringCallable!");
        binding.rxTest1.append("\n");
        return new Callable<String>() {
            @Override
            public String call() throws Exception {
                binding.rxTest1.append("call!");
                //try {
                //    Thread.sleep(500);
                //}catch (InterruptedException e) {
                //    e.printStackTrace();
                //}
                binding.rxTest1.append("" + Thread.currentThread().getId());
                binding.rxTest1.append("\n");
                binding.rxTest1.setText(binding.rxTest1.getText() + "set text \n");
                return String.valueOf(index);
            }
        };
    }
```
```
    private Callable<String> getStringCallable2(final int index) {
        binding.rxTest2.append("getStringCallable!");
        binding.rxTest2.append("\n");
        return new Callable<String>() {
            @Override
            public String call() throws Exception {
                binding.rxTest2.append("call!");
                try {
                    Thread.sleep(500);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                binding.rxTest2.append("" + Thread.currentThread().getId());
                binding.rxTest2.append("\n");
                binding.rxTest2.setText(binding.rxTest2.getText() + "set text \n");
                return String.valueOf(index);
            }
        };
    }
```

**Comment by akarnokd** [comment]
How do you build an `Observable` from these callables? What is the exact stacktrace of the exception?

The canonical way of doing background work is:

```java
Observable.fromCallable(() -> "generated string")
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
.subscribe(string -> textField.setText(string));
```

**Comment by buptfarmer** [comment]
@akarnokd 
```
        public void onClickTest2(View view) {
            Log.d(TAG, "onClickTest2: ");
            // why this will crash, with java.util.concurrent.ExecutionException: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
            mRepeatedOb = Observable.fromFuture(executor.submit(getStringCallable2(2)));
            binding.rxTest2.append("clicked!");
            binding.rxTest2.append("\n");
            mRepeatedOb.subscribeOn(Schedulers.newThread())
                    //.observeOn(AndroidSchedulers.mainThread())
                    .subscribe(getObserver());
        }
```
I build the `observable` from future which submitted on a executor

**Comment by buptfarmer** [comment]
Here is my full exception stack
```
12-16 16:33:58.374 8857-8857/com.chensiwen.edugame D/RxJavaExampleActivity: onClickTest2: 
12-16 16:33:58.879 8857-2647/com.chensiwen.edugame W/System.err: java.util.concurrent.ExecutionException: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-16 16:33:58.879 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:93)
12-16 16:33:58.879 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:163)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromFuture.subscribeActual(ObservableFromFuture.java:41)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10179)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.Scheduler$1.run(Scheduler.java:134)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-16 16:33:58.880 8857-2647/com.chensiwen.edugame W/System.err: Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6735)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1088)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.ViewGroup.invalidateChild(ViewGroup.java:4693)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.View.invalidateInternal(View.java:11828)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.View.invalidate(View.java:11792)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.View.invalidate(View.java:11776)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView.updateAfterEdit(TextView.java:7829)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView.handleTextChanged(TextView.java:7852)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:9799)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:964)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:515)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:272)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:33)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView.append(TextView.java:3698)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView.append(TextView.java:3685)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at com.chensiwen.edugame.RxJavaExampleActivity$2.call(RxJavaExampleActivity.java:91)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at com.chensiwen.edugame.RxJavaExampleActivity$2.call(RxJavaExampleActivity.java:82)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 16:33:58.881 8857-2647/com.chensiwen.edugame W/System.err: 	... 3 more
12-16 16:33:58.882 8857-2647/com.chensiwen.edugame W/System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6735)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1088)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.ViewGroup.invalidateChild(ViewGroup.java:4693)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.View.invalidateInternal(View.java:11828)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.View.invalidate(View.java:11792)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.view.View.invalidate(View.java:11776)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView.updateAfterEdit(TextView.java:7829)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView.handleTextChanged(TextView.java:7852)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:9799)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:964)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:515)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:272)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:33)
12-16 16:33:58.883 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView.append(TextView.java:3698)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at android.widget.TextView.append(TextView.java:3685)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at com.chensiwen.edugame.RxJavaExampleActivity$3.onError(RxJavaExampleActivity.java:133)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:68)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromFuture.subscribeActual(ObservableFromFuture.java:45)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10179)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.Scheduler$1.run(Scheduler.java:134)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 16:33:58.884 8857-2647/com.chensiwen.edugame W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by buptfarmer** [comment]
when click RX_TEST_1 , no crash, but still odd. 
when click RX_TEST_2, crash but still odd that the the first line of the `call()` `binding.rxTest2.append("call!");` did not crash. it just crash after the `Thread.sleep()`

![image](https://cloud.githubusercontent.com/assets/4084663/21256531/d1b84810-c3ad-11e6-9449-4bafddcc494c.png)

**Comment by akarnokd** [comment]
I don't know when and how Android detects the off-main-thread access. I assume `binding.rxTest2` is some UI widget you shouldn't access from another thread so don't. Why do you have that `Callable` anyway?

**Comment by buptfarmer** [comment]
@akarnokd 
I want to do some long-time work such has http request in my `Callable`  , this is the pre test.  
I want to make sure the `Callable` is in the non-ui thread, so that will not block the main ui. 
But the test result is confusing to me.

**Comment by akarnokd** [comment]
If you apply `subscribeOn(Schedulers.io())` you get off the main thread. I still don't understand why you update the UI widget from the background thread. Send the data down to the main thread and create a value class if you have to deliver more than one type of result.

**Comment by buptfarmer** [comment]
> I still don't understand why you update the UI widget from the background thread. 

To verify it is in background thread, I should check the `Thread.getId()` .  
I thought update UI from background thread will check that too.  just kind of making sure of that.  
Maybe I misunderstand the android UI thread checking mechanism.

**Comment by akarnokd** [comment]
http://stackoverflow.com/questions/11411022/how-to-check-if-current-thread-is-not-main-thread

> `Looper.myLooper() == Looper.getMainLooper()`
> if this returns true, then you're on the UI thread!

**Comment by buptfarmer** [comment]
Yes, I know about this. 
And in my case, I updated the UI from background thread which build from `Observable.fromFuture()` , and its `Looper.myLooper() == Looper.getMainLooper()`,  it got to be wrong.  As it is a background thread with different thread id, it should has different Looper with main looper.

**Comment by buptfarmer** [comment]
Furthermore, after some `Thread.sleep()` the looper of the background thread has changed.  
it is unbelievable .

**Comment by akarnokd** [comment]
I don't think this is related to RxJava. Please post this question with all the additional detail on StackOverflow because there are way more Android developers hanging around.

**Comment by buptfarmer** [comment]
I cannot agree with you.  
If I simply update UI from a thread which is created by `new Thread()` or `Executors.newSingleThreadExecutor();  executor.submit()` , it will crash at the first line of the `call()` no matter I put some `Thread.sleep()` in it or not.  
this line of code 
``` 
Observable<String> mRepeatedOb = Observable.fromFuture(executor.submit(getStringCallable(1)));
``` 
must did something tricky.  

However, I will post this question on stackoverflow.

**Comment by buptfarmer** [comment]
Thanks anyway.  @akarnokd
