### ISSUE TITLE
2.0 TimeoutException in MaybeTimeoutMaybe

### ISSUE THREAD

**Issue by vRallev** [ReactiveX/RxJava#4925]
We're using version `2.0.2` in our app and saw a few crashes with following stack trace
```
java.util.concurrent.TimeoutException
	at io.reactivex.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutMainMaybeObserver.otherComplete(MaybeTimeoutMaybe.java:132)
	at io.reactivex.internal.operators.maybe.MaybeTimeoutMaybe$TimeoutOtherMaybeObserver.onSuccess(MaybeTimeoutMaybe.java:160)
	at io.reactivex.internal.operators.maybe.MaybeTimer$TimerDisposable.run(MaybeTimer.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

Since no method from our code is in the stack, I have no idea how to reproduce it. Is this a bug? Is there a way to stop the app from crashing and to ignore the exception?

**Comment by akarnokd** [comment]
That exception is only fired if a Maybe operation is timed out before it signals its events or gets disposed from downstream. Could you share how you are using `Maybe.timeout`? It looks like some other operator terminates the sequence in some way and this timeout lands in the default error handler. Temporarily, you could suppress these by using `RxJavaPlugins.setOnErrorHandler(Functions.<Throwable>emptyConsumer());`

**Comment by vRallev** [comment]
We have many places where this could happen and it's hard to say where it happens. I guess simple Maybe.create().bla().timeout(..) won't trigger this exceptions. Here are some other samples we use:
```java
Maybe
        .merge(maybe1, maybe2)
        .firstElement()
        .timeout(5_000, TimeUnit.MILLISECONDS)
```
```java
          String something = Maybe
              .fromCallable(new Callable<String>() {
                @Override
                public String call() throws Exception {
                  return ""; // is slow
                }
              })
              .subscribeOn(Schedulers.io())
              .timeout(2_000, TimeUnit.MILLISECONDS)
              .onErrorComplete(new Predicate<Throwable>() {
                @Override
                public boolean test(Throwable throwable) throws Exception {
                  return true;
                }
              })
              .blockingGet();
```
```java
      Something.getMaybe()
          .ignoreElement() // Completable
          .timeout(3000, TimeUnit.MILLISECONDS)
          .onErrorComplete(new Predicate<Throwable>() {
            @Override
            public boolean test(Throwable throwable) {
              return true;
            }
          })
          .subscribe(new Action() {
            @Override
            public void run() throws Exception {
               // code
            }
          });
```

And the last one is a Transformer
```java
    public static <T> MaybeTransformer<T, T> timeoutWithCleanupMaybe(final long timeout, @NonNull final TimeUnit timeUnit, @NonNull final Consumer<T> cleanUpConsumer) {
        return new MaybeTransformer<T, T>() {
            @Override
            public MaybeSource<T> apply(Maybe<T> upstream) {
                final Maybe<T> cached = upstream.cache();
                return cached
                        .timeout(timeout, timeUnit)
                        .doOnError(new Consumer<Throwable>() {
                            @Override
                            public void accept(Throwable throwable) {
                                cached.subscribe(cleanUpConsumer);
                            }
                        });
            }
        };
    }
```

The Transformer looks like the best candidate.

**Comment by akarnokd** [comment]
If you can make this happen relatively often, I suggest using [the debug support](https://github.com/akarnokd/RxJava2Extensions#debug-support) from the RxJava 2 Extensions library. It will attach extra information and show you the likely culprit.

**Comment by vRallev** [comment]
It looks to happen rarely and internally we weren't able to reproduce it. I'll suppress the exception on production builds and hopefully we find a hint internally. Thanks for the quick help. 

Feel free to close the issue, if you don't think it's a bug.

**Comment by akarnokd** [comment]
CLosing for now. Let us know if you have further details on the issue.
