### ISSUE TITLE
BaseLinkedQueueProducerNodeRef  ignored flag rx.unsafe-disable

### ISSUE THREAD

**Issue by mstrdev** [ReactiveX/RxJava#4940]
- version 1.2.4

Issue reproduced with android app on device "Lenovo IdeaTab s6000-H". I solve many problems with Unsafe by setting "rx.unsafe-disable" flag. But BaseLinkedQueueProducerNodeRef ignored this flag. And I received this:

```
E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-7
ava.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
   at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.ExceptionInInitializerError
   at rx.internal.operators.CompletableOnSubscribeMergeDelayErrorIterable.call(CompletableOnSubscribeMergeDelayErrorIterable.java:56)
   at rx.internal.operators.CompletableOnSubscribeMergeDelayErrorIterable.call(CompletableOnSubscribeMergeDelayErrorIterable.java:27)
   at rx.Completable.unsafeSubscribe(Completable.java:2037)
   at rx.Completable$31$1.call(Completable.java:2149)
   at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390) 
   at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153) 
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267) 
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
   at java.lang.Thread.run(Thread.java:838) 
Caused by: java.lang.NullPointerException
   at rx.internal.util.unsafe.UnsafeAccess.addressOf(UnsafeAccess.java:113)
   at rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef.<clinit>(BaseLinkedQueue.java:33)
   at rx.internal.operators.CompletableOnSubscribeMergeDelayErrorIterable.call(CompletableOnSubscribeMergeDelayErrorIterable.java:56) 
   at rx.internal.operators.CompletableOnSubscribeMergeDelayErrorIterable.call(CompletableOnSubscribeMergeDelayErrorIterable.java:27) 
   at rx.Completable.unsafeSubscribe(Completable.java:2037) 
   at rx.Completable$31$1.call(Completable.java:2149) 
   at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) 
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390) 
   at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153) 
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267) 
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
   at java.lang.Thread.run(Thread.java:838) 
```

I think that problem with line 33 which directly invoke  Unsafe methods:
```
  protected final static long P_NODE_OFFSET = UnsafeAccess.addressOf(BaseLinkedQueueProducerNodeRef.class, "producerNode");
```

**Comment by akarnokd** [comment]
Thanks. The operator `CompletableOnSubscribeMergeDelayErrorIterable` doesn't properly switch on the unsafe settings. I'll post a fix shortly.

**Comment by akarnokd** [comment]
Closing via #4941
