### ISSUE TITLE
2.x: NPE at ObservableReplay.ReplayObserver.dispose()

### ISSUE THREAD

**Issue by hvisser** [ReactiveX/RxJava#5060]
Stack trace below shows a crash that I unfortunately can't reproduce currently. I've checked the source for `ObservableReplay.ReplayObserver` and it looks like this can only happen if it's being disposed before being subscribed which sounds odd to me? What might be relevant is that `unsubscribeOn()` is used on the observable.

```
java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference
    at io.reactivex.internal.operators.observable.ObservableReplay$ReplayObserver.dispose(ObservableReplay.java:361)
    at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:216)
    at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:79)
    at io.reactivex.internal.operators.observable.ObservableRefCount$2.run(ObservableRefCount.java:126)
    at io.reactivex.disposables.RunnableDisposable.onDisposed(RunnableDisposable.java:28)
    at io.reactivex.disposables.RunnableDisposable.onDisposed(RunnableDisposable.java:18)
    at io.reactivex.disposables.ReferenceDisposable.dispose(ReferenceDisposable.java:42)
    at io.reactivex.internal.operators.observable.ObservableRefCount$ConnectionObserver.dispose(ObservableRefCount.java:181)
    at io.reactivex.internal.disposables.DisposableHelper.setOnce(DisposableHelper.java:79)
    at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onSubscribe(ObservableSubscribeOn.java:58)
    at io.reactivex.internal.operators.observable.ObservableRefCount.doSubscribe(ObservableRefCount.java:113)
    at io.reactivex.internal.operators.observable.ObservableRefCount$1.accept(ObservableRefCount.java:98)
    at io.reactivex.internal.operators.observable.ObservableRefCount$1.accept(ObservableRefCount.java:92)
    at io.reactivex.internal.operators.observable.ObservableReplay.connect(ObservableReplay.java:305)
    at io.reactivex.internal.operators.observable.ObservableRefCount.subscribeActual(ObservableRefCount.java:68)
    at io.reactivex.Observable.subscribe(Observable.java:10514)
    at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
    at io.reactivex.Scheduler$1.run(Scheduler.java:134)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

**Comment by akarnokd** [comment]
Thanks for reporting, this is a bug. What happens is that the asnyc dispose happens before the chain of onSubscribe call reaches the operator. The same happens inside `FlowableReplay`. I'll post a fix shortly.

**Comment by akarnokd** [comment]
See #5064

**Comment by akarnokd** [comment]
Closing via #5064
