### ISSUE TITLE
ParallelFlowable, sequential and exception management

### ISSUE THREAD

**Issue by marcosalis** [ReactiveX/RxJava#5108]
Hi,
I'm stuck on a problem which might or might not be an issue on the current version of the `ParallelFlowable`, or if it is a desired behaviour, it's not specified anywhere in the documentation.
In a few words, I'm having issues propagating errors from a `ParallelFlowable` to a single `Flowable` (when calling `sequential()`).
What I would expect is that any error generated during the execution of operators on the `ParallelFlowable` would be propagated to the subscriber on the Flowable.
What really happens is that the exception is not propagated, and it's thrown even if it's a checked exception.
Here is a code example:

```java
Flowable.just(request1, request2)
                .parallel() // parallel execution is needed
                .runOn(Schedulers.io())
                .map(request -> request.execute()) // execute() can throw an exception
                .sequential()
                .toList()
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(this::success, this::failure);
```
`failure(exception)` is not called, and the exception is actually thrown.

I've also tried this and the exception is still not propagated to the sequential Flowable:

```java
Flowable.just(request1, request2)
                .parallel() // parallel execution is needed
                .runOn(Schedulers.io())
                .flatMap(request -> {
                    try {
                        return Flowable.just(request.execute());
                    } catch (Exception e) {
                        return Flowable.error(e);
                    }
                }
                .sequential()
...
```

I'm using version 2.0.5 of RxJava on Android.

Thank you for your help.

**Comment by akarnokd** [comment]
The underlying problem is that `sequential` can only allow one `onError`. If multiple rails fail, one gets through and the others get sent to `RxJavaPlugins.onError`.

On one hand, this is a general property of RxJava 2 and requires you to setup a [global error handler](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling) based on what you consider fatal and what not.

On the other hand, the internals of the parallel operators don't leave much option. Currently, if a rail fails it cancels the upstream rail  (which cancels the original Flowable in the chain) and emits an onError. When the error reaches the `sequential` operator, the operator cancels the rest of the rails.

For a workaround, I suggest you switch back to a traditional parallel execution:

```java
Flowable<T> a = Flowable.just(request1).subscribeOn(Schedulers.computation()).map(...);
Flowable<T> b = Flowable.just(request2).subscribeOn(Schedulers.computation()).map(...);

Flowable<T> c = Flowable.mergeArrayDelayError(a, b);
```

I need more time to figure out a better way to support your failure mode.

**Comment by marcosalis** [comment]
Thank you @akarnokd for the super fast turnaround on this!
I'll go with `Flowable.mergeArrayDelayError()` for now, since it seems to behave as expected, and I look forward to check out the new solution with `ParallelFlowable`.
In general, when it comes to parallel computations there are three common scenarios to handle a failure and it would be good if developers were able to choose among all of them:
- Make all the computations fail when one of them fails
- Notify all successful computations until the failure, then fail all the others
- Notify all successful computations, before and after the failed computation

**Comment by akarnokd** [comment]
See #5202.

I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.

**Comment by marcosalis** [comment]
@akarnokd I have a slightly related scenario, and I can't figure out a way to achieve what I want. When using the zip operator on an `Observable` or `Single`, there isn't a way to propagate a single error consistently since `mergeArrayDelayError()` or similar all accept a single data type.

In this example, I have two `Single`, executed in parallel on a different thread, which are then passed into a `zip` function and then synchronously executed through a `blockingGet()`.
What I'd expect is that the exception is thrown by this latter method. What happens though is that the exception is passed to the default uncaught exception handler from `RxJavaPlugins.onError()`.

Am I using the wrong approach or is there an issue with error propagation here?
RxJava 2.1.3 on Android.

Here's the (failing) JUnit test:

```
    @Test(expected = InterruptedException.class)
    public void testParallelZip_exceptionNotPropagated() throws Exception {
        Single<Object> allPeopleSource = Single.fromCallable(() -> {
            throw new InterruptedException();
        }).subscribeOn(Schedulers.io());
        Single<String> idsSource = Single.fromCallable(() -> "second_single").subscribeOn(Schedulers.io());

        Single.zip(allPeopleSource, idsSource, (o, s) -> "result").blockingGet();
    }
```

And here's the failure crash log:
```
java.lang.Exception: Unexpected exception, expected<java.lang.InterruptedException> but was<java.lang.RuntimeException>

	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:91)
	at io.reactivex.Single.blockingGet(Single.java:2154)
	at [...].RxUtilsTest.testParallelZip_exceptionNotPropagated(RxUtilsTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 20 more
Caused by: java.lang.InterruptedException
	at com.teamwork.data.util.RxUtilsTest.lambda$testParallelZip_exceptionNotPropagated$1(RxUtilsTest.java:66)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
	at io.reactivex.Single.subscribe(Single.java:2700)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
