### ISSUE TITLE
2.x: ParallelFlowableTest > parallelismAndPrefetchAsync FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#5154]
```
io.reactivex.parallel.ParallelFlowableTest > parallelismAndPrefetchAsync FAILED
    java.lang.AssertionError: Value counts differ; Expected: 1048576, Actual: 619054 (latch = 1, values = 619054, errors = 0, completions = 0)
        at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:146)
        at io.reactivex.observers.BaseTestConsumer.assertValueCount(BaseTestConsumer.java:443)
        at io.reactivex.parallel.ParallelFlowableTest.parallelismAndPrefetchAsync(ParallelFlowableTest.java:741)
```

Could be due to timeout on an overworked container instance.

Also the `BaseTestConsumer` may be extended to:

  - print the cancellation status which `awaitDone` sets
  - make `awaitDone` add an `onError` (requires synchronising the errors list) or a separate timeout flag that get's also printed.

**Comment by akarnokd** [comment]
Closing via #5199
