### ISSUE TITLE
1.x Crash with ArrayIndexOutOfBoundsException in OnSubscribePublishMulticast using RxRelay

### ISSUE THREAD

**Issue by sebaslogen** [ReactiveX/RxJava#5238]
Crash found on production but I can't reproduce it and by looking at the RxJava source code I can't even understand how it's possible to have the crash in the for-each loop.

Version of RxJava: 1.2.7
Version of RxRelay: 1.2.0

Crash log:
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at rx.internal.operators.OnSubscribePublishMulticast.drain(OnSubscribePublishMulticast.java:193)
       at rx.internal.operators.OnSubscribePublishMulticast.onNext(OnSubscribePublishMulticast.java:146)
       at rx.internal.operators.OnSubscribePublishMulticast$ParentSubscriber.onNext(OnSubscribePublishMulticast.java:393)
       at com.jakewharton.rxrelay.NotificationLite.accept(NotificationLite.java:78)
       at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.emitNext(RelaySubscriptionManager.java:236)
       at com.jakewharton.rxrelay.BehaviorRelay.call(BehaviorRelay.java:97)
       at ....updateRoutePlannerState(...)
```

In the RxJava line pointed by the log I can see a for-each loop so I can't imagine how that produces an ArrayIndexOutOfBoundsException
https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/internal/operators/OnSubscribePublishMulticast.java#L193

The line in RxRelay that triggers the method that crashes in RxJava is:
https://github.com/JakeWharton/RxRelay/blob/version-one/src/main/java/com/jakewharton/rxrelay/NotificationLite.java#L78

The device that reproduced the crash in the wild is a: alps-HR933, Android 4.4.2 rooted.

**Comment by akarnokd** [comment]
That doesn't make sense to me. The array is read into a local variable and for-each should simply not loop on an empty array. Could be a compiler/JIT bug on that particular device.

**Comment by sebaslogen** [comment]
Alright, that confirms my suspicions. I close the bug because I don't think there is anything we can do about it.
