### ISSUE TITLE
NPE in defer().flatMap() chain [2.0.6]

### ISSUE THREAD

**Issue by kamehamehajim** [ReactiveX/RxJava#5292]
I get "java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference" running following sample code

`    CompositeDisposable subs = new CompositeDisposable();

    private Integer getInt() {
        if(true)
            throw new IllegalStateException();
        return 0;
    }

    private void test() {
        subs.add(Observable.defer(() -> observer -> {
            observer.onNext(1);
            observer.onComplete();
        }).flatMap(o -> Observable.fromCallable(this::getInt))
                .subscribe(integer -> {}, Throwable::printStackTrace)
        );
    }`

Am I using defer in a wrong way?

**Comment by akarnokd** [comment]
Could you post the entire stacktrace?

**Comment by kamehamehajim** [comment]
```
04-18 23:27:23.310 12259-12259/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.testapp, PID: 12259
                                                   java.lang.RuntimeException: Unable to resume activity {com.example.testapp/com.example.testapp.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3145)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3176)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2517)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:158)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5515)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference
                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:498)
                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:490)
                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmitScalar(ObservableFlatMap.java:224)
                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:146)
                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
                                                       at com.example.testapp.presenters.ListSpecsPresenter.lambda$null$0(ListSpecsPresenter.java:51)
                                                       at com.example.testapp.presenters.ListSpecsPresenter$$Lambda$8.subscribe(Unknown Source)
                                                       at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:39)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10700)
                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10700)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10686)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10615)
                                                       at com.example.testapp.presenters.ListSpecsPresenter.test(ListSpecsPresenter.java:54)
                                                       at com.example.testapp.presenters.ListSpecsPresenter.onAttachView(ListSpecsPresenter.java:34)
                                                       at com.example.testapp.presenters.ListSpecsPresenter.onAttachView(ListSpecsPresenter.java:15)
                                                       at com.example.testapp.ui.SpecListFragment.onResume(SpecListFragment.java:158)
                                                       at android.support.v4.app.Fragment.performResume(Fragment.java:2235)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2898)
                                                       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
                                                       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
                                                       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
                                                       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
                                                       at android.app.Activity.performResume(Activity.java:6548)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3134)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3176) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2517) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:158) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5515) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
```

**Comment by akarnokd** [comment]
Okay, the problem is that you are not supposed to create observables via the lambda (even though they appear to be functional interfaces) because you have to call `onSubscribe` with a `Disposable`. Use `Observable.just()` or `Observable.create()` instead.

**Comment by kamehamehajim** [comment]
```java
    private void test() {
        subs.add(Observable.defer(() -> new ObservableSource<Integer>() {
            @Override
            public void subscribe(Observer<? super Integer> observer) {
                observer.onNext(1);
                observer.onComplete();
            }
        }).flatMap(o -> Observable.fromCallable(this::getInt))
                .subscribe(integer -> {}, Throwable::printStackTrace)
        );
    }
```

Fails too. Am I still doing it wrong? (sorry for badly inserted code, I don't know what's going on)

**Comment by akarnokd** [comment]
```java
public void test() {
    subs.add(Observable.defer(() -> Observable.create(observer -> {
        observer.onNext(1);
        observer.onComplete();
    })).flatMap(o -> Observable.fromCallable(this::getInt))
        .subscribe(integer -> {}, Throwable::printStackTrace)
    );
}
```

**Comment by kamehamehajim** [comment]
Ok, I got it, I should've just called observer.onSubscribe() to provide some kind of disposable. Thanks for quick reply.
