### ISSUE TITLE
exception = java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by coderloveryan** [ReactiveX/RxJava#5298]
2017-04-19 20:31:07,660	ERROR/CrashHandler:	__   __        __            /  /  /
2017-04-19 20:31:07,661	ERROR/CrashHandler:	/  ` |__)  /\  /__` |__|     /  /  / 
2017-04-19 20:31:07,662	ERROR/CrashHandler:	\__, |  \ /~~\ .__/ |  |    .  .  . 
2017-04-19 20:31:07,704	ERROR/CrashHandler:	versionName: 3.1.0
2017-04-19 20:31:07,705	ERROR/CrashHandler:	versionCode: 2017041901
2017-04-19 20:31:07,706	ERROR/CrashHandler:	DeviceInfo[BOARD] : msm8939
2017-04-19 20:31:07,706	ERROR/CrashHandler:	DeviceInfo[BOOTLOADER] : 3.19.0.0000
2017-04-19 20:31:07,707	ERROR/CrashHandler:	DeviceInfo[BRAND] : htc
2017-04-19 20:31:07,707	ERROR/CrashHandler:	DeviceInfo[CPU_ABI] : armeabi-v7a
2017-04-19 20:31:07,708	ERROR/CrashHandler:	DeviceInfo[CPU_ABI2] : armeabi
2017-04-19 20:31:07,708	ERROR/CrashHandler:	DeviceInfo[DEVICE] : htc_a52dtul
2017-04-19 20:31:07,708	ERROR/CrashHandler:	DeviceInfo[DISPLAY] : LRX22G release-keys
2017-04-19 20:31:07,709	ERROR/CrashHandler:	DeviceInfo[FINGERPRINT] : htc/a52dtul_htccn_chs_2/htc_a52dtul:5.0.2/LRX22G/583966.7:user/release-keys
2017-04-19 20:31:07,709	ERROR/CrashHandler:	DeviceInfo[HARDWARE] : qcom
2017-04-19 20:31:07,710	ERROR/CrashHandler:	DeviceInfo[HOST] : ABM031
2017-04-19 20:31:07,710	ERROR/CrashHandler:	DeviceInfo[ID] : LRX22G
2017-04-19 20:31:07,710	ERROR/CrashHandler:	DeviceInfo[MANUFACTURER] : HTC
2017-04-19 20:31:07,710	ERROR/CrashHandler:	DeviceInfo[MODEL] : HTC D826w
2017-04-19 20:31:07,711	ERROR/CrashHandler:	DeviceInfo[PRODUCT] : a52dtul_htccn_chs_2
2017-04-19 20:31:07,711	ERROR/CrashHandler:	DeviceInfo[RADIO] : unknown
2017-04-19 20:31:07,711	ERROR/CrashHandler:	DeviceInfo[SERIAL] : CC53GYG13444
2017-04-19 20:31:07,712	ERROR/CrashHandler:	DeviceInfo[SUPPORTED_32_BIT_ABIS] : [Ljava.lang.String;@1f283846
2017-04-19 20:31:07,712	ERROR/CrashHandler:	DeviceInfo[SUPPORTED_64_BIT_ABIS] : [Ljava.lang.String;@11697a07
2017-04-19 20:31:07,713	ERROR/CrashHandler:	DeviceInfo[SUPPORTED_ABIS] : [Ljava.lang.String;@35814734
2017-04-19 20:31:07,713	ERROR/CrashHandler:	DeviceInfo[TAG] : Build
2017-04-19 20:31:07,714	ERROR/CrashHandler:	DeviceInfo[TAGS] : release-keys
2017-04-19 20:31:07,714	ERROR/CrashHandler:	DeviceInfo[TYPE] : user
2017-04-19 20:31:07,714	ERROR/CrashHandler:	DeviceInfo[UNKNOWN] : unknown
2017-04-19 20:31:07,715	ERROR/CrashHandler:	DeviceInfo[USER] : buildteam
2017-04-19 20:31:07,715	ERROR/CrashHandler:	DeviceInfo[IS_DEBUGGABLE] : false
2017-04-19 20:31:07,716	ERROR/CrashHandler:	DeviceInfo[TIME] : 1439482856000
2017-04-19 20:31:07,716	ERROR/CrashHandler:	DeviceInfo[STAGE] : 2
2017-04-19 20:31:07,717	ERROR/CrashHandler:	UncaughtException, THREAD: Thread[main,5,main] NAME: main ID: 1
2017-04-19 20:31:07,717	ERROR/CrashHandler:	**** STACKTRACE BEGIN ****
2017-04-19 20:31:07,717	ERROR/CrashHandler:	exception = java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
2017-04-19 20:31:07,718	ERROR/CrashHandler:	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:112)
2017-04-19 20:31:07,718	ERROR/CrashHandler:	at android.os.Handler.handleCallback(Handler.java:739)
2017-04-19 20:31:07,718	ERROR/CrashHandler:	at android.os.Handler.dispatchMessage(Handler.java:95)
2017-04-19 20:31:07,718	ERROR/CrashHandler:	at android.os.Looper.loop(Looper.java:155)
2017-04-19 20:31:07,719	ERROR/CrashHandler:	at android.app.ActivityThread.main(ActivityThread.java:5702)
2017-04-19 20:31:07,719	ERROR/CrashHandler:	at java.lang.reflect.Method.invoke(Method.java:-2)
2017-04-19 20:31:07,720	ERROR/CrashHandler:	at java.lang.reflect.Method.invoke(Method.java:372)
2017-04-19 20:31:07,720	ERROR/CrashHandler:	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
2017-04-19 20:31:07,720	ERROR/CrashHandler:	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
2017-04-19 20:31:07,721	ERROR/CrashHandler:	**** STACKTRACE END **** 
2017-04-19 20:31:07,721	ERROR/CrashHandler:	**** CAUSE BEGIN ****
2017-04-19 20:31:07,722	ERROR/CrashHandler:	getCause() = rx.exceptions.OnErrorNotImplementedException
2017-04-19 20:31:07,722	ERROR/CrashHandler:	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
2017-04-19 20:31:07,722	ERROR/CrashHandler:	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
2017-04-19 20:31:07,723	ERROR/CrashHandler:	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
2017-04-19 20:31:07,723	ERROR/CrashHandler:	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
2017-04-19 20:31:07,724	ERROR/CrashHandler:	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
2017-04-19 20:31:07,724	ERROR/CrashHandler:	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:205)
2017-04-19 20:31:07,724	ERROR/CrashHandler:	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
2017-04-19 20:31:07,725	ERROR/CrashHandler:	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
2017-04-19 20:31:07,725	ERROR/CrashHandler:	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
2017-04-19 20:31:07,725	ERROR/CrashHandler:	at android.os.Handler.handleCallback(Handler.java:739)
2017-04-19 20:31:07,726	ERROR/CrashHandler:	at android.os.Handler.dispatchMessage(Handler.java:95)
2017-04-19 20:31:07,726	ERROR/CrashHandler:	at android.os.Looper.loop(Looper.java:155)
2017-04-19 20:31:07,726	ERROR/CrashHandler:	at android.app.ActivityThread.main(ActivityThread.java:5702)
2017-04-19 20:31:07,727	ERROR/CrashHandler:	at java.lang.reflect.Method.invoke(Native Method)
2017-04-19 20:31:07,727	ERROR/CrashHandler:	at java.lang.reflect.Method.invoke(Method.java:372)
2017-04-19 20:31:07,728	ERROR/CrashHandler:	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
2017-04-19 20:31:07,728	ERROR/CrashHandler:	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
2017-04-19 20:31:07,728	ERROR/CrashHandler:	**** CAUSE END ***

**Comment by JakeWharton** [comment]
This is a problem with your code, not the library. Add `onError` implementations to your subscribers!
