### ISSUE TITLE
The following error confuse packaging is complete, run times

### ISSUE THREAD

**Issue by AndroidAndYang** [ReactiveX/RxJava#5314]
```
Process: www.pingyuan.yangplay, PID: 8040
reactivex.exceptions.OnErrorNotImplementedException
 at io.reactivex.internal.functions.Functions$14.accept(Unknown Source)
 at io.reactivex.internal.functions.Functions$14.accept(Unknown Source)
 at io.reactivex.internal.observers.LambdaObserver.onError(Unknown Source)
 at io.reactivex.internal.observers.LambdaObserver.onNext(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmitScalar(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableBuffer$BufferExactObserver.onNext(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(Unknown Source)
 at io.reactivex.observers.SerializedObserver.onNext(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver$InnerObserver.onNext(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.drain(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onSubscribe(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmitScalar(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFromArray$FromArrayDisposable.run(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableBuffer.subscribeActual(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at io.reactivex.Observable.subscribe(Unknown Source)
 at www.pingyuan.yangplay.ui.activity.MainActivity.j(Unknown Source)
```

**Comment by akarnokd** [comment]
You are using `subscribe(Consumer<T>)` instead of `subscribe(Consumer<T>, Consumer<Throwable>)` and your `Consumer<T>` crashes.

**Comment by AndroidAndYang** [comment]
Thanks
