### ISSUE TITLE
blockingGet(); throws exception instead of returning value in onError

### ISSUE THREAD

**Issue by jotish** [ReactiveX/RxJava#5315]
```java
Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: java.lang.InterruptedException
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
       at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:48)
       at io.reactivex.Observable.subscribe(Observable.java:10700)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
       at io.reactivex.Scheduler$1.run(Scheduler.java:138)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.RuntimeException: java.lang.InterruptedException
       at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
       at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:86)
       at io.reactivex.Single.blockingGet(Single.java:2148)
       at com.practo.ray.newsync.clients.SettingsSyncClient.sync(SettingsSyncClient.java:75)
       at com.practo.ray.newsync.DataSyncAdapterService$DataSyncAdapter$6.call(DataSyncAdapterService.java:1315)
       at com.practo.ray.newsync.DataSyncAdapterService$DataSyncAdapter$6.call(DataSyncAdapterService.java:1249)
       at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
       at io.reactivex.Observable.subscribe(Observable.java:10700)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
       at io.reactivex.Scheduler$1.run(Scheduler.java:138)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.InterruptedException
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1279)
       at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:202)
       at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:83)
       at io.reactivex.Single.blockingGet(Single.java:2148)
       at com.practo.ray.newsync.clients.SettingsSyncClient.sync(SettingsSyncClient.java:75)
       at com.practo.ray.newsync.DataSyncAdapterService$DataSyncAdapter$6.call(DataSyncAdapterService.java:1315)
       at com.practo.ray.newsync.DataSyncAdapterService$DataSyncAdapter$6.call(DataSyncAdapterService.java:1249)
       at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
       at io.reactivex.Observable.subscribe(Observable.java:10700)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
       at io.reactivex.Scheduler$1.run(Scheduler.java:138)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

```java
     List<Boolean> result =  Observable.merge(getSettingsSyncObservable())
                                        .onErrorReturnItem(false).toList().blockingGet();
```

Why does `blockingGet();` throw Exception instead of returning an error value `false`?

**Comment by jotish** [comment]
https://github.com/ReactiveX/RxJava/issues/5063 Related

**Comment by akarnokd** [comment]
The blocking inside the `blockingGet` is interrupted, not the source. Why are you using `blockingGet` in the first place instead of composing through?

```
at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
```

Looks like your outer sequence gets disposed and the blocking call gets interrupted to find it unable to deliver the interruption error hence the global catch receives the error.

**Comment by jotish** [comment]
@akarnokd Using `blockingGet` for parallel execution of multiple tasks(List of Sync Observables) and wait for the result of it.  Something like [this](https://solidsoft.wordpress.com/2016/02/26/parallel-execution-of-blocking-tasks-with-rxjava-and-completable/) 

```java
     List<Boolean> result =  Observable.merge(getSettingsSyncObservables())
                                        .onErrorReturnItem(false).toList().blockingGet();
```
What could be the reason for blocking inside the `blockingGet` to get interrupted? Couldn't figure out how to fix this. Outer sequence as in ?

**Comment by akarnokd** [comment]
A cancellation may come due to screen rotation (if you are on Android), a failure from the other `Observable`. Also you seem to run an older version of RxJava 2 because we got rid of the anonymous inner classes a month ago.
