### ISSUE TITLE
NoClassDefFoundError Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension; when migrating to Android O

### ISSUE THREAD

**Issue by alouanemed** [ReactiveX/RxJava#5362]
I'm using RxJava with Retrofit on the newest AndroidStudio 3.0 Canary 1.

I am using Java 8 before migrating to Android O.But after updating Gradle and AS, I am starting to get this error .

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:281)
at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:58)
at io.reactivex.Observable.subscribe(Observable.java:10179)
at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
at io.reactivex.Observable.subscribe(Observable.java:10179)
at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:31)
at io.reactivex.Flowable.subscribe(Flowable.java:12218)
at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:31)
at io.reactivex.Flowable.subscribe(Flowable.java:12218)


```
 How can this be resolved?

Thanks.

**Comment by akarnokd** [comment]
This is not an issue in RxJava but likely a project setup/dependency resolution issue in your case. In general, I suggest asking this type of (Android-related) questions on Stackoverflow.
