### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by vijay-pal** [ReactiveX/RxJava#5410]
```
Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
at rx.internal.schedulers.ScheduledAction.run(MyApplication:62)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@c5c7b27 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@33009e6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:302)
at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:527)
at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:626)
at rx.internal.schedulers.NewThreadWorker.scheduleActual(MyApplication:239)
at rx.internal.schedulers.NewThreadWorker.schedule(MyApplication:224)
at rx.internal.schedulers.NewThreadWorker.schedule(MyApplication:216)
at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(MyApplication:82)
at rx.Subscriber.request(MyApplication:157)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(MyApplication:225)
at rx.internal.schedulers.ScheduledAction.run(MyApplication:55)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

I have updated retrofit library to ` 'com.squareup.retrofit2:retrofit:2.0.2'`, app is working fine at the time of development and debug. After publishing the app on prod this appeared on 'Crashlytics' very frequent. 
I have no  idea about it. Ask me for any help.
These are the dependencies 
`compile 'com.squareup.retrofit2:retrofit:2.0.2'
 compile 'com.squareup.retrofit2:adapter-rxjava:2.0.2'
 compile 'io.reactivex:rxandroid:1.0.1@aar'`

**Comment by akarnokd** [comment]
What exact RxJava version are you using and what is the code look like? This somewhat looks like an unsubscription/emission race due to screen rotation.

**Comment by vijay-pal** [comment]
I am using `rxandroid:1.0.1` with retrofit `retrofit2:adapter-rxjava:2.0.2`, 
And calling http request look like 

```java
subscription = service.getApi()
      .getToolExamList(jsonString)
      .subscribeOn(Schedulers.newThread())
      .observeOn(Schedulers.computation())
      .retryWhen(new RetryWithDelay(Constants.MAX_RETRIES, Constants.MAX_DELAY)).unsubscribeOn(Schedulers.newThread())
      .subscribe(new Observer<String>() {
        @Override
        public void onCompleted() {
          if (listener != null)
            new Handler(Looper.getMainLooper()).post(new Runnable() {
              @Override
              public void run() {
                listener.stopProgressBar();
              }
            });
        }

        @Override
        public void onError(final Throwable error) {
          if (listener != null) {
            new Handler(Looper.getMainLooper()).post(new Runnable() {
              @Override
              public void run() {
                listener.stopProgressBar();
                listener.onError(error, jsonString);
              }
            });
          }
        }

        @Override
        public void onNext(String response) {
          if (listener != null) {
            listener.onResponse(response);
          }

        }
      });
```

And unsubscribes call when Activity destroy by 

```java
  @Override
  public void onDestroy() {
    super.onDestroy();
    if (mPresenter != null) {
      mPresenter.unSubscribe();
    }
  }` 
`@Override
  public boolean isUnSubscribe() {
    return subscription == null || subscription.isUnsubscribed();
  }

  @Override
  public void unSubscribe() {
    if (!isUnSubscribe()) {
      subscription.unsubscribe();
    }
  }
```

**Comment by akarnokd** [comment]
Please use the latest versions of those libraries.

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
