### ISSUE TITLE
RxJava1.3.0 stackoverflow at android4.4

### ISSUE THREAD

**Issue by yangwuan55** [ReactiveX/RxJava#5424]
version:1.3.0
os:android4.4
My app is running is very good at other version of android except for android4.4.
There is the crash log:
```

java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:841)
                                                    Caused by: java.lang.StackOverflowError
                                                       at java.util.concurrent.ConcurrentLinkedQueue.isEmpty(ConcurrentLinkedQueue.java:397)
                                                       at rx.internal.schedulers.CachedThreadScheduler$CachedWorkerPool.get(CachedThreadScheduler.java:90)
                                                       at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker.<init>(CachedThreadScheduler.java:188)
                                                       at rx.internal.schedulers.CachedThreadScheduler.createWorker(CachedThreadScheduler.java:176)
                                                       at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:44)
                                                       at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:30)
                                                       at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                       at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
                                                       at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
                                                       at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                       at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
                                                       at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
                                                       at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
                                                       at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                       at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:202)
                                                       at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:143)
                                                       at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:109)
                                                       at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
                                                       at rx.Subscriber.setProducer(Subscriber.java:209)
                                                       at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
                                                       at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                       at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                       at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                                                       at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                       at rx.Observable.unsafeSubscribe(Observable.java:10256)
                                                       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
                                                       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
                                                       at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                                                       at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
                                                       at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
                                                       at rx.internal.operators.OperatorAny$1.onNext(OperatorAny.java:62)
                                                       at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
                                                       at rx.internal.operators.CachedObservable$ReplayProducer.replay(CachedObservable.java:403)
                                                   	at rx.internal.operators.CachedObservable$CacheState.dispatch(CachedObservable.j


```

**Comment by akarnokd** [comment]
Maybe the default stack size on that platform is low. You can break the stack depth at places by introducing `observeOn` or (somehow) specify the minimum thread stack depth for the application.

**Comment by yangwuan55** [comment]
@akarnokd Thank you! I do the observeOn is useful.
