### ISSUE TITLE
2.x ObservableEmitter.tryOnError(Throwable t) is not thread safe

### ISSUE THREAD

**Issue by jfmichel** [ReactiveX/RxJava#5477]
Hello,

The experimental [ObservableEmitter.tryOnError(Throwable)](https://github.com/ReactiveX/RxJava/blob/8bf04e968584ed49139af9f81854ae28b225e0b0/src/main/java/io/reactivex/internal/operators/observable/ObservableCreate.java#L79) method does not actually guarantee `RXJavaPlugins.onError(Throwable)` will never be called.

`tryOnError` basically checks if the emitter is not disposed before calling the underlying observer's `onError` method. The problem is that `isDisposed` can return false while another thread is disposing it. 

The issue lies in `DisposableHelper` whose [dispose(AtomicReference&lt;Disposable&gt;)](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/disposables/DisposableHelper.java#L118) method guarantee that two threads cannot dispose the same `Disposable` but its [isDisposed(Disposable)](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/disposables/DisposableHelper.java#L39) method cannot be used to protect a critical section as `tryOnError` is using it.

**Comment by akarnokd** [comment]
The race may happen at any position downstream and `tryOnError` only allows you to prevent the plugin error call to happen from within the emitter. The is no serialization between onXXX and the dispose calls because that is generally way too expensive. Therefore, it is always recommended to install a global error handler in an Android app to avoid crashes.

As comparison, the [SingleCreate](https://github.com/ReactiveX/RxJava/blob/8bf04e968584ed49139af9f81854ae28b225e0b0/src/main/java/io/reactivex/internal/operators/single/SingleCreate.java#L62) fires only one event and there is a mutual exclusion with that event and a possible dispose calls - a one time cost per flow.

The question is, how do you have a dispose/emission race?

**Comment by jfmichel** [comment]
Hello, 

I'm working on a legacy project which was not using RXJava before.
I'm using an ObservableEmitter to wrap a callback style SDK into a reactive style one. 
The Observable result is consumed in an AsyncTask (which is currently one of the RX world / non-RX world boundary of the app) by using the `Observable.blockingForEach(Consumer<? super T>)` method.

The race happens when I need to cancel the whole thing :

- the underlying SDK request is canceled, a callback is called and a custom `Throwable` is emitted (with `tryOnError`).
- the `AsyncTask` is canceled allowing its thread to be interrupted
- the `blockingForEach`method catches the `InterruptedException` and disposes the observable

Sometimes `blockingForEach` is disposing the observable but is not far enough in the method to prevent `isDisposed` to returns true. Nevertheless at the time the Throwable is emitted, the observable is disposed and hence `RXJavaPlugins.onError` is called.

I solved the issue by setting up an empty global handler as described in the documentation but it felt like sweeping the problem under the rug and wanted to share the issue with you.

**Comment by akarnokd** [comment]
Do you have a stacktrace when the plugin error handler is called? It indicates were the undeliverable exception state has been reached.

**Comment by jfmichel** [comment]
Yes here is a stacktrace. As I understand it the error occurs when the SDK's onFailure callback fires while the blockingForEach method is disposing the observable due to catching the interrupted exception.

```
Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.lang.Throwable: Canceled
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
       at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:97)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester$3.onFailure(OoyalaAdRequester.java:312)
       at com.ooyala.adtech.AdRequester$3.a(SourceFile:414)
       at com.ooyala.adtech.j$2.onFailure(SourceFile:95)
       at com.ooyala.adtech.j$3$1.onSuccess(SourceFile:168)
       at com.ooyala.adtech.j$3.a(SourceFile:125)
       at com.ooyala.adtech.j.a(SourceFile:186)
       at com.ooyala.adtech.j.a(SourceFile:105)
       at com.ooyala.adtech.j$3.a(SourceFile:163)
       at com.ooyala.adtech.j$4.a(SourceFile:241)
       at com.ooyala.adtech.Request.cancel(SourceFile:46)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester.cancelRequest(OoyalaAdRequester.java:281)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester.cancelRequest(OoyalaAdRequester.java:275)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester.lambda$null$2(OoyalaAdRequester.java:318)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester$$Lambda$6.cancel(Unknown Source)
       at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:49)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.single.SingleCreate$Emitter.dispose(SingleCreate.java:112)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.dispose(SingleSubscribeOn.java:78)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.dispose(SingleObserveOn.java:87)
       at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:217)
       at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:80)
       at io.reactivex.internal.operators.single.SingleTimeout$TimeoutDispose.run(SingleTimeout.java:77)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.Throwable: Cancelled
       at com.myapp.media.ad.ooyala.OoyalaAdRequester.createThrowable(OoyalaAdRequester.java:203)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester.access$1000(OoyalaAdRequester.java:42)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester$3.onFailure(OoyalaAdRequester.java:312)
       at com.ooyala.adtech.AdRequester$3.a(SourceFile:414)
       at com.ooyala.adtech.j$2.onFailure(SourceFile:95)
       at com.ooyala.adtech.j$3$1.onSuccess(SourceFile:168)
       at com.ooyala.adtech.j$3.a(SourceFile:125)
       at com.ooyala.adtech.j.a(SourceFile:186)
       at com.ooyala.adtech.j.a(SourceFile:105)
       at com.ooyala.adtech.j$3.a(SourceFile:163)
       at com.ooyala.adtech.j$4.a(SourceFile:241)
       at com.ooyala.adtech.Request.cancel(SourceFile:46)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester.cancelRequest(OoyalaAdRequester.java:281)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester.cancelRequest(OoyalaAdRequester.java:275)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester.lambda$null$2(OoyalaAdRequester.java:318)
       at com.myapp.media.ad.ooyala.OoyalaAdRequester$$Lambda$6.cancel(Unknown Source)
       at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:49)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.single.SingleCreate$Emitter.dispose(SingleCreate.java:112)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.dispose(SingleSubscribeOn.java:78)
       at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.dispose(SingleObserveOn.java:87)
       at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:217)
       at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:80)
       at io.reactivex.internal.operators.single.SingleTimeout$TimeoutDispose.run(SingleTimeout.java:77)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by akarnokd** [comment]
`at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:97)`

This is `Single.create()` whose `Emitter` also has `tryOnError()`.

**Comment by jfmichel** [comment]
Ho sorry you are right. This is the stacktrace I got before using `tryOnError`.
 
The following stacktrace happens in the same circumstances when calling `tryOnError` :

```
io.reactivex.exceptions.UndeliverableException: java.lang.Throwable: Cancelled
      at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
      at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:310)
      at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:125)
      at io.reactivex.internal.operators.observable.BlockingObservableIterable$BlockingObservableIterator.hasNext(BlockingObservableIterable.java:91)
      at io.reactivex.Observable.blockingForEach(Observable.java:4792)
      at com.myapp.media.item.LiveMediaItem.fillCurrentQueue(LiveMediaItem.java:132)
```

Unfortunately it doesn't show the `tryOnError` call but I managed to write a small test that shows it :

```
io.reactivex.exceptions.UndeliverableException: java.lang.Throwable: Canceled
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.onError(ObservableObserveOn.java:125)
	at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:85)
	at com.myapp.UndeliverableExceptionTest$Runner.onCanceled(UndeliverableExceptionTest.java:32)
	at com.myapp.UndeliverableExceptionTest$Runner.cancel(UndeliverableExceptionTest.java:38)
	at com.myapp.UndeliverableExceptionTest$Runner.access$100(UndeliverableExceptionTest.java:11)
	at com.myapp.UndeliverableExceptionTest$1.run(UndeliverableExceptionTest.java:60)
Caused by: java.lang.Throwable: Canceled
	... 4 more
Exception in thread "Thread-13" io.reactivex.exceptions.UndeliverableException: java.lang.Throwable: Canceled
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.onError(ObservableObserveOn.java:125)
	at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:85)
	at com.myapp.UndeliverableExceptionTest$Runner.onCanceled(UndeliverableExceptionTest.java:32)
	at com.myapp.UndeliverableExceptionTest$Runner.cancel(UndeliverableExceptionTest.java:38)
	at com.myapp.UndeliverableExceptionTest$Runner.access$100(UndeliverableExceptionTest.java:11)
	at com.myapp.UndeliverableExceptionTest$1.run(UndeliverableExceptionTest.java:60)
Caused by: java.lang.Throwable: Canceled
	... 4 more
```

The test is ugly but seems to do the trick on my computer

```java
public class UndeliverableExceptionTest {

    private class Runner extends Thread {

        private volatile ObservableEmitter<Integer> mEmitter;

        public void setEmitter(ObservableEmitter<Integer> emitter) {
            mEmitter = emitter;
        }

        private volatile boolean running = true;

        @Override
        public void run() {
            while (running) {
                if (mEmitter != null) {
                    mEmitter.onNext(1);
                }
            }
            onCanceled();
        }

        private void onCanceled() {
            mEmitter.tryOnError(new Throwable("Canceled"));
        }

        private void cancel() {
            running = false;
            interrupt();
            onCanceled();
        }
    }

    @Test
    public void testUndeliverableException() {
        for (int i = 0; i < 10; ++i) {
            final Runner runner = new Runner();

            Observable<Integer> observable = Observable.create(emitter -> {
                runner.setEmitter(emitter);
                runner.start();
            });

            new Thread() {
                @Override
                public void run() {
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    runner.cancel();
                }
            }.start();

            try {
                observable.observeOn(Schedulers.computation())
                        .subscribeOn(Schedulers.computation())
                        .blockingForEach(integer -> {
                        });
            } catch (Exception ignored) {
            } finally {
                System.out.println("test " + i + " done");
            }
        }
    }
}
```

**Comment by akarnokd** [comment]
Don't emit the cancelled throwable. By definition, it happens when the downstream cancels and is no longer willing to accept events.

**Comment by jfmichel** [comment]
That's the obvious thing to do in this test example but you can imagine that some unrelated and unsolicited failure event pops up at the wrong time without knowing that the downstream is not accepting events anymore. It's the purpose of the `isDisposed` method right ?

I understand that fixing this might cost more that its benefit and I guess I can live with an empty error handler.

Anyway thank you for your support and quick answers.
