### ISSUE TITLE
SocketTimeoutException cause CompositeException$CompositeExceptionCausalChain

### ISSUE THREAD

**Issue by cxmmxc** [ReactiveX/RxJava#5488]
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
      at android.os.Handler.handleCallback(Handler.java:742)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:5529)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
   Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
      at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
      at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:276)
      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)
      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
      at android.os.Handler.handleCallback(Handler.java:742) 
      at android.os.Handler.dispatchMessage(Handler.java:95) 
      at android.os.Looper.loop(Looper.java:154) 
      at android.app.ActivityThread.main(ActivityThread.java:5529) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
   Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
      at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192) 
      at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120) 
      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:276) 
      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219) 
      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
      at android.os.Handler.handleCallback(Handler.java:742) 
      at android.os.Handler.dispatchMessage(Handler.java:95) 
      at android.os.Looper.loop(Looper.java:154) 
      at android.app.ActivityThread.main(ActivityThread.java:5529) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
   Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
      at com.tencent.bugly.crashreport.crash.e.a(BUGLY:187)
      at com.tencent.bugly.crashreport.crash.e.b(BUGLY:334)
      at com.tencent.bugly.crashreport.crash.e.uncaughtException(BUGLY:372)
      at com.umeng.analytics.pro.as.uncaughtException(CrashHandler.java:37)
      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:118)
      at android.os.Handler.handleCallback(Handler.java:742) 
      at android.os.Handler.dispatchMessage(Handler.java:95) 
      at android.os.Looper.loop(Looper.java:154) 
      at android.app.ActivityThread.main(ActivityThread.java:5529) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
   Caused by: java.net.SocketTimeoutException: failed to connect to /192.168.100.16 (port 80) after 15000ms
      at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
      at libcore.io.IoBridge.connect(IoBridge.java:122)
      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
      at java.net.Socket.connect(Socket.java:884)
      at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
      at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:221)
      at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
      at com.lingdanet.safeguard.customer.net.HeaderInterceptor.intercept(HeaderInterceptor.java:57)
      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  	at okhttp3.logging
```

this is my HeaderIntercept

```
@Override
    public Response intercept(Chain chain) throws IOException{
        Request request = chain.request();
        Request.Builder builder = request
                .newBuilder();
        String token = SPUtils.getInstance().getString(Constant.TOKEN, "");
//        String token = SafeguardCustomerApplication.getInstance().getToken();
        LogUtils.d(TAG, "token = " + token);
        if(headers != null && !TextUtils.isEmpty(token)) {
            LogUtils.d(TAG, "headers != null" + token);
            headers.put(AUTHORIZATION, token);
        }
        if (headers != null && headers.size() > 0) {
            Set<String> keys = headers.keySet();
            for (String headerKey : keys) {
                builder.addHeader(headerKey, headers.get(headerKey)).build();
            }
        }
        Response repsonse = chain.proceed(builder.build());
        if (null != repsonse) {
            String curToken = repsonse.header(AUTHORIZATION);
            LogUtils.d(TAG, "cuToken = " + curToken);
            if ((!TextUtils.isEmpty(curToken)) && (!TextUtils.equals(token, curToken))) {
                token = curToken;
                SPUtils.getInstance().put(Constant.TOKEN, token);
            }
        }

        return repsonse;
    }
```

```
 Response repsonse = chain.proceed(builder.build());
```
the error point to this line

**Comment by akarnokd** [comment]
The primary error is the inability to connect to an endpoint:

`Caused by: java.net.SocketTimeoutException: failed to connect to /192.168.100.16 (port 80) after 15000ms`

The secondary error is that you don't have proper error handling in your `subscribe()` method but the stacktrace is truncated and you don't seem to use the latest version of RxJava.

**Comment by akarnokd** [comment]
Looks like this question has been answered. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
