### ISSUE TITLE
retrofit2 + rxjava 请求地址 404 崩溃

### ISSUE THREAD

**Issue by Blisterfritters** [ReactiveX/RxJava#5502]
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
       at rx.observers.SerializedObserver.onError(SerializedObserver.java:152)
       at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:78)
       at rx.internal.operators.OperatorTakeUntil$1.onError(OperatorTakeUntil.java:50)
       at rx.observers.Subscribers$5.onError(Subscribers.java:230)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
       at android.os.Handler.handleCallback(Handler.java:739) 
       at android.os.Handler.dispatchMessage(Handler.java:95) 
       at android.os.Looper.loop(Looper.java:135) 
       at android.app.ActivityThread.main(ActivityThread.java:5254) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187) 
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) 
       at rx.observers.SerializedObserver.onError(SerializedObserver.java:152) 
       at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:78) 
       at rx.internal.operators.OperatorTakeUntil$1.onError(OperatorTakeUntil.java:50) 
       at rx.observers.Subscribers$5.onError(Subscribers.java:230) 
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273) 
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216) 
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
       at android.os.Handler.handleCallback(Handler.java:739) 
       at android.os.Handler.dispatchMessage(Handler.java:95) 
       at android.os.Looper.loop(Looper.java:135) 
       at android.app.ActivityThread.main(ActivityThread.java:5254) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
       at android.util.Log.getStackTraceString(Log.java:335)
       at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:59)
       at com.android.internal.os.RuntimeInit.access$200(RuntimeInit.java:43)
       at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:85)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:118)
       at android.os.Handler.handleCallback(Handler.java:739) 
       at android.os.Handler.dispatchMessage(Handler.java:95) 
       at android.os.Looper.loop(Looper.java:135) 
       at android.app.ActivityThread.main(ActivityThread.java:5254) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    Caused by: retrofit2.adapter.rxjava.HttpException: HTTP 404 
       at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:43)
       at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:38)
       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
       at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
       at rx.Subscriber.setProducer(Subscriber.java:209)
       at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
       at rx.Subscriber.setProducer(Subscriber.java:205)
       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
       at rx.Observable.unsafeSubscribe(Observable.java:10200)
       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
       at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)

**Comment by akarnokd** [comment]
> [...] please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

[Google](https://www.google.hu/search?q=rx.exceptions.OnErrorFailedException%3A+Error+occurred+when+trying+to+propagate+error+to+Observer.onError&oq=rx.exceptions.OnErrorFailedException%3A+Error+occurred+when+trying+to+propagate+error+to+Observer.onError&aqs=chrome..69i57j69i61l3.533j0j7&sourceid=chrome&ie=UTF-8)
[StackOverflow](https://stackoverflow.com/search?q=OnErrorFailedException)

> If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).

[StackOverflow](https://stackoverflow.com/search?q=Retrofit+404)
