### ISSUE TITLE
Throw exception when use lift before map

### ISSUE THREAD

**Issue by happyjosh** [ReactiveX/RxJava#5515]
I can't check dispose in lift when use lift before map

```java
Observable.just("111")
    .lift(new ObservableOperator<Integer, String>() {
        @Override
        public Observer<? super String> apply(@NonNull final Observer<? super Integer> observer) throws Exception {
            return new Observer<String>() {
                @Override
                public void onSubscribe(@NonNull Disposable d) {

                }

                @Override
                public void onNext(@NonNull String s) {
                    if (observer instanceof Disposable && ((Disposable) observer).isDisposed()) {
                        return;
                    }

                    observer.onNext(Integer.parseInt(s));
                }

                @Override
                public void onError(@NonNull Throwable e) {
                    if (observer instanceof Disposable && ((Disposable) observer).isDisposed()) {
                        return;
                    }

                    observer.onError(e);
                }

                @Override
                public void onComplete() {
                    if (observer instanceof Disposable && ((Disposable) observer).isDisposed()) {
                        return;
                    }

                    observer.onComplete();
                }
            };
        }
    })
    .map(new Function<Integer, Integer>() {
        @Override
        public Integer apply(@NonNull Integer s) throws Exception {
            return s + 100;
        }
    })
    .subscribe(new DisposableObserver<Integer>() {
        @Override
        public void onNext(@NonNull Integer integer) {
            System.out.println("i:" + integer);
        }

        @Override
        public void onError(@NonNull Throwable e) {

        }

        @Override
        public void onComplete() {

        }
    });
```
ExceptionMessage:
```java
Exception in thread "main" java.lang.NullPointerException
	at io.reactivex.internal.observers.BasicFuseableObserver.isDisposed(BasicFuseableObserver.java:157)
	at com.jph.testapp.MainClass$3$1.onNext(MainClass.java:33)
	at com.jph.testapp.MainClass$3$1.onNext(MainClass.java:25)
	at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
	at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableLift.subscribeActual(ObservableLift.java:57)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at com.jph.testapp.MainClass.test(MainClass.java:66)
	at com.jph.testapp.MainClass.main(MainClass.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

version : compile 'io.reactivex.rxjava2:rxjava:2.1.0'

**Comment by akarnokd** [comment]
Have you read the [wiki about writing operators](https://github.com/ReactiveX/RxJava/wiki/Writing-operators-for-2.0#operator-targeting-lift)?

Also why do you write an operator for a mapping scenario: `.map(Integer::parseInt)`?

**Comment by happyjosh** [comment]
@akarnokd It's just a simple demo for my real logic ,Is there problem of the use way?

**Comment by akarnokd** [comment]
You have to honor the `Observable` protocol: `onSubscribe onNext* (onError | onComplete)?` when interacting with an `Observer`.

**Comment by happyjosh** [comment]
@akarnokd Miss the onSubscribe，sorry,my fault.
