### ISSUE TITLE
Caused by: java.lang.NullPointerException                                                                             at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onNext(ObservableConcatMap.java:128)

### ISSUE THREAD

**Issue by youngonlyforyou** [ReactiveX/RxJava#5591]
```java
public class BluetoothActivity extends AppCompatActivity {
   @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_bluetooth);
        Observable.just("a")
                .concatMap(b->getResponse(b))
                .concatMap(b->getResponse(b))
                .subscribe(new Consumer<Object>() {
                    @Override
                    public void accept(Object o) throws Exception {
                    }

                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                    }
                });
}
public Observable<Object> getResponse(Object o){
        Log.d("program","getResponse():"+o.toString());
        return new Observable<Object>() {
            @Override
            protected void subscribeActual(Observer<? super Object> observer) {
                observer.onNext("b");
                observer.onComplete();
            }

        };
    }
}
```

Log:
```
09-06 18:55:58.312 20589-20589/? E/dalvikvm: /system/framework/pm.jar odex has stale dependencies
09-06 18:55:58.472 20589-20589/? E/memtrack: Couldn't load memtrack module (No such file or directory)
09-06 18:55:58.472 20589-20589/? E/android.os.Debug: failed to load memtrack module: -2
09-06 18:55:58.632 1478-20601/? E/ActivityThread: Failed to find provider info for com.leadcore.sdb
09-06 18:56:06.622 20618-20618/? E/dalvikvm: /system/framework/am.jar odex has stale dependencies
09-06 18:56:06.832 20618-20618/? E/memtrack: Couldn't load memtrack module (No such file or directory)
09-06 18:56:06.832 20618-20618/? E/android.os.Debug: failed to load memtrack module: -2
09-06 18:56:09.082 20638-20638/com.example.z.myplayer E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
09-06 18:56:09.252 20638-20638/com.example.z.myplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.example.z.myplayer, PID: 20638
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.z.myplayer/com.example.z.myplayer.BluetoothActivity}: java.lang.NullPointerException
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                         Caused by: java.lang.NullPointerException
                                                                            at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onNext(ObservableConcatMap.java:128)
                                                                            at com.example.z.myplayer.BluetoothActivity$5.subscribeActual(BluetoothActivity.java:170)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10903)
                                                                            at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarXMapObservable.subscribeActual(ObservableScalarXMap.java:166)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10903)
                                                                            at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:52)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10903)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10889)
                                                                            at io.reactivex.Observable.subscribe(Observable.java:10818)
                                                                            at com.example.z.myplayer.BluetoothActivity.onCreate(BluetoothActivity.java:79)
                                                                            at android.app.Activity.performCreate(Activity.java:5356)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:136) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5135) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
09-06 18:56:09.402 1478-20662/? E/ActivityThread: Failed to find provider info for com.leadcore.sdb
09-06 18:56:09.662 20660-20660/? E/dalvikvm: /system/framework/am.jar odex has stale dependencies
09-06 18:56:09.822 20660-20660/? E/memtrack: Couldn't load memtrack module (No such file or directory)
09-06 18:56:09.822 20660-20660/? E/android.os.Debug: failed to load memtrack module: -2
```

**Comment by youngonlyforyou** [comment]
activity crash ..............app crash ..........

**Comment by akarnokd** [comment]
The problem is that you use `new Observable()` where you should follow the observable protocol and call `onSubscribe`:

```java
public Observable<Object> getResponse(Object o){
        Log.d("program","getResponse():"+o.toString());
        return new Observable<Object>() {
```

You should use `Observable.create()`  instead:

```java
public Observable<Object> getResponse(Object o){
    Log.d("program","getResponse():"+o.toString());
    return Observable.<Object>create(new ObservableOnSubscribe<Object>() {
        @Override 
        public void subscribe(ObservableEmitter<Object> observer) {
             observer.onNext("b");
             observer.onComplete();
        }
    });
```

**Comment by youngonlyforyou** [comment]
thx very much ,my friend. I have solved the problem      ：）   ：）
