### ISSUE TITLE
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by a8453770** [ReactiveX/RxJava#5597]
09-12 14:45:10.220 22214-22214/com.emuzi.wallet E/UncaughtException: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                         at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:146)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5748)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                         at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)
                                                                         at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                         at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273)
                                                                         at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
                                                                         at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                         at android.os.Handler.handleCallback(Handler.java:733) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                         at android.os.Looper.loop(Looper.java:146) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5748) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                         at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187) 
                                                                         at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) 
                                                                         at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273) 
                                                                         at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216) 
                                                                         at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
                                                                         at android.os.Handler.handleCallback(Handler.java:733) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                         at android.os.Looper.loop(Looper.java:146) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5748) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                         at android.util.Log.getStackTraceString(Log.java:454)
                                                                         at android.util.Log.e(Log.java:356)
                                                                         at com.google.firebase.crash.internal.zzh.uncaughtException(Unknown Source)
                                                                         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                         at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:118)
                                                                         at android.os.Handler.handleCallback(Handler.java:733) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                         at android.os.Looper.loop(Looper.java:146) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5748) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: com.emuzi.wallet.module.LogoutException
                                                                         at com.emuzi.wallet.service.CheckLogoutOperator$1.onNext(CheckLogoutOperator.java:46)
                                                                         at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:41)
                                                                         at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:38)
                                                                         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
                                                                         at rx.Subscriber.setProducer(Subscriber.java:209)
                                                                         at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                         at rx.Observable.unsafeSubscribe(Observable.java:10200)
                                                                         at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                         at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:841)
                                                                      Caused by: android.view.WindowManager$BadTokenException:

**Comment by akarnokd** [comment]
You didn't implement `onError` in your `subscribe()` call:

    source.subscribe(v -> { }, e -> e.printStackTrace()) 

for example.

Relevant exceptions:

Caused by: com.emuzi.wallet.module.LogoutException
Caused by: android.view.WindowManager$BadTokenException:

**Comment by a8453770** [comment]
thank you , this is my implement onError in subscribe() call
```java
 @Override
    public Subscriber<? super T> call(Subscriber<? super T> subscriber) {
        return new Subscriber<T>() {
            @Override
            public void onCompleted() {
                subscriber.onCompleted();
            }

            @Override
            public void onError(Throwable e) {
                if (subscriber != null) {
                       subscriber.onError(e);
                }
            }

            @Override
            public void onNext(T t) {
                if (subscriber != null ) {
                    if (t instanceof Response && ((Response) t).result == -2) {
                        subscriber.onError(new LogoutException());
                        subscriber.unsubscribe();
                    } else if (t instanceof NetworkErrorException) {
                        subscriber.onError(new NetworkErrorException());
                        subscriber.unsubscribe();
                    } else if (t instanceof SocketTimeoutException) {
                        subscriber.onError(new SocketTimeoutException());
                        subscriber.unsubscribe();
                    }else {
                        subscriber.onNext(t);
                    }
                }
            }
        };
    }
```

**Comment by a8453770** [comment]
@akarnokd

**Comment by akarnokd** [comment]
That is an operator and not an end susbscriber.

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.

**Comment by a8453770** [comment]
hi  I added the method, but it was wrong

     public static <T> void subscribe(BaseActivity activity,
                                     Observable<T> observable,
                                     Action1<T> onNext,
                                     Action1<Throwable> onError,
                                     Action0 onComplete) {
        observable.compose(activity.bindToLifecycle())
                 .compose(applySchedulers())
                .subscribe(onNext, onError, onComplete);

    }

**Comment by akarnokd** [comment]
What does your `Action1<Throwable>` do?

**Comment by a8453770** [comment]
in my BaseActivity  
```java
protected void handleError(Throwable t) {
        if (t instanceof LogoutException) {
            reLogin();
        } else if (t instanceof SocketException) {
            showCenterToast(R.string.networkServiceError);
        } else if (t instanceof NetworkErrorException) {
            showCenterToast(R.string.networkServiceError);
        } else if (t instanceof TimeoutException) {
            showCenterToast(R.string.time_out);
        } else if (t instanceof UnknownHostException) {
            showCenterToast(R.string.networkUnknownError);
        } else if (t instanceof SocketTimeoutException) {
            showCenterToast(R.string.time_out);
        } else {
            showCenterToast(R.string.service_not_use);
        }
         hideProgressDialog();
    }
```

**Comment by akarnokd** [comment]
So what is the **new** exception you are getting? Also please use three backticks (ASCII code 96) to get ```formatted code``` that is easier to read.

**Comment by a8453770** [comment]
Sorry  It my code problem,I've solved it. Thank you
