### ISSUE TITLE
 Uncaught remote exception!  (Exceptions are not yet supported across processes.)___java.lang.StackOverflowError

### ISSUE THREAD

**Issue by youngonlyforyou** [ReactiveX/RxJava#5606]
```java
private SingleSource upload(byte[] binData) {         // send 17366  byte
       // . binData = onePageData *138   
       .......     
       ......
      Single single = Single.just("").subscribeOn(Schedulers.io());
       for (int i = 0; i < pageArray.length; i++){ .         // pageArray.length =138
            onePageData = pageArray[i];
            single = single.flatMap(d ->uploadPage(onePageData));
        };
        return single;
}
private SingleSource uploadPage(byte[] pageData) { .      //send 128 byte
       ........
       .........
      loadaddress ={1,2,3} .....
      finalLoaddata = pageData + something .     // {1,2,3}   ->  {14,1,2,3,10}
       Single single = Single.just("").subscribeOn(Schedulers.io());
               single = single
                    .flatMap(s ->getResponse(loadaddress))
                    .flatMap(s -> getResponse(finalLoaddata))
                    .delay(4, TimeUnit.MILLISECONDS);
        return single;
}
public SingleSource getResponse(byte[] cmd) {                    //send 128 byte
   ...............
   ..............
   return new SingleSource() {
       Single single = Single.just("").subscribeOn(Schedulers.io());
                for (int i = 0; i < cmdList.length; i++) {                   // length=7 =128 byte /20 byte 
                    byte[] byte20 = cmdList[i];
                    single = single.flatMap(d-> sendBleData(ioCharacteristic,byte20));
                }
                single.subscribe(ret -> {},
                        error -> observer.onError(new Throwable()));
}
public SingleSource sendBleData(BluetoothGattCharacteristic characteristic, byte[] data) {
   return new SingleSource() {
            @Override
            public void subscribe(SingleObserver observer) {
               // TODO write characteristic here;
                ...................
                ...................
                 characteristic.setValue(data);
                mGatt.writeCharacteristic(characteristic);
            }
        };

}
```

```
09-18 01:35:24.915 26727-26789/com.microduino.mdashboard E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                                       java.lang.StackOverflowError
                                                                           at java.util.concurrent.atomic.AtomicReference.compareAndSet(AtomicReference.java:85)
                                                                           at io.reactivex.internal.disposables.DisposableHelper.setOnce(DisposableHelper.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:66)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                       	at io.reac
09-18 01:35:25.095 26727-26789/com.microduino.mdashboard E/AndroidRuntime: FATAL EXCEPTION: Binder_3
                                                                           Process: com.microduino.mdashboard, PID: 26727
                                                                           java.lang.StackOverflowError
                                                                               at java.util.concurrent.atomic.AtomicReference.compareAndSet(AtomicReference.java:85)
                                                                               at io.reactivex.internal.disposables.DisposableHelper.setOnce(DisposableHelper.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:66)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                               at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:67)
                                                                           	at io.reactivex.in
09-18 01:35:25.235 2405-7723/? E/BluetoothServiceJni: An exception was thrown by callback 'btgattc_notify_cb'.
09-18 01:35:25.235 2405-7723/? E/BluetoothServiceJni: android.os.DeadObjectException
                                                          at android.os.BinderProxy.transact(Native Method)
                                                          at android.bluetooth.IBluetoothGattCallback$Stub$Proxy.onNotify(IBluetoothGattCallback.java:836)
                                                          at com.android.bluetooth.gatt.GattService.onNotify(GattService.java:833)
                                                          at dalvik.system.NativeStart.run(Native Method)
09-18 01:35:25.245 2405-7723/? E/BtGatt.ContextMap: Context not found for ID 5
09-18 01:35:25.255 799-922/? E/InputDispatcher: channel '42202540 com.microduino.mdashboard/com.microduino.mdashboard.SeriesActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-18 01:35:25.585 26889-26889/com.microduino.mdashboard E/PushFactory: getPushInstance not found push instance.
```

**Comment by akarnokd** [comment]
Marked as invalid because it's a dump of stacktrace, non-working code, no explanation what you try to do and use of some technology built around Rx. Btw this pattern makes it overflow the stack because the chain gets too long:

```java
for (int i = 0; i < pageArray.length; i++){ .         // pageArray.length =138
            onePageData = pageArray[i];
            single = single.flatMap(d ->uploadPage(onePageData));
        };
```

Why are you using `Single` on a multi-piece data available upfront?!

```java
Flowable.fromArray(pageArray)
.flatMapSingle(d -> uploadPage(d), 1)
```

**Comment by youngonlyforyou** [comment]
i use this code :
      Flowable.fromArray(pageArray)
                     .flatMapSingle(d -> uploadPage(d), 1)
when after     singleObserable.onSuccess()
can not enter  uploadPage( )   this method ............
so we use    fori ()

**Comment by akarnokd** [comment]
I don't understand.
