### ISSUE TITLE
2.1.5: question about catch exception in parallel

### ISSUE THREAD

**Issue by b7woreo** [ReactiveX/RxJava#5688]
dependencies
```
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.1.5'
```

code example:
``` java
    Flowable.fromIterable(Arrays.asList(1, 2, 3))
        .parallel()
        .runOn(Schedulers.io())
        .flatMap(i ->
                     Single.fromCallable(() -> {
                       try {
                         Thread.sleep(1000);
                       } catch (InterruptedException e) {

                       }

                       throw new NullPointerException();
                     })
                         .toFlowable()
        )
        .sequential()
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(i -> {
          Log.d("TEST", "i = " + i);
        }, throwable -> {
          Log.d("TEST", "error");
        });
```
```
```

Above code will lead crash, it only catch first error. If use ```sequentialDelayError``` operator, it will right.
But ```sequentialDelayError``` delaying errors from all rails till all terminate, so can I  direct receive error and terminate observe.

**Comment by akarnokd** [comment]
What's your question?

**Comment by b7woreo** [comment]
I want to terminate observe immediately when occur error, not like ```sequentialDelayError```. but ```sequential``` operator will lead crash. This is a bug?

Log:
```
W: java.lang.NullPointerException
W:     at com.example.administrator.myapplication.MainActivity.lambda$null$0(MainActivity.java:33)
W:     at com.example.administrator.myapplication.MainActivity$$Lambda$6.call(Unknown Source:0)
W:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
W:     at io.reactivex.Single.subscribe(Single.java:2779)
W:     at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
W:     at io.reactivex.Flowable.subscribe(Flowable.java:12994)
W:     at io.reactivex.Flowable.subscribe(Flowable.java:12940)
W:     at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
W:     at io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnSubscriber.run(ParallelRunOn.java:247)
W:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
W:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
W:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W:     at java.lang.Thread.run(Thread.java:764)
D: error
```

**Comment by akarnokd** [comment]
The problem is that all of your parallel rails crash but only one sequential `onError` can happen. The rest of the errors go into the global error consumer. See [error handling](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling) for further details.

**Comment by b7woreo** [comment]
Thanks
