### ISSUE TITLE
 rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError

### ISSUE THREAD

**Issue by a8453770** [ReactiveX/RxJava#5722]
11-10 17:23:57.101 23946-23946/com.emuzi.wallet E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.emuzi.wallet, PID: 23946
                                                                  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                   Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                      at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)
                                                                      at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                      at rx.internal.operators.OperatorOnBackpressureDrop$2.onError(OperatorOnBackpressureDrop.java:86)
                                                                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273)
                                                                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
                                                                      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)?
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)?
                                                                      at android.os.Looper.loop(Looper.java:154)?
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)?
                                                                      at java.lang.reflect.Method.invoke(Native Method)?
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)?
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)?
                                                                   Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                      at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)?
                                                                      at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)?
                                                                      at rx.internal.operators.OperatorOnBackpressureDrop$2.onError(OperatorOnBackpressureDrop.java:86)?
                                                                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273)?
                                                                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)?
                                                                      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)?
                                                                      at android.os.Handler.handleCallback(Handler.java:751)?
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)?
                                                                      at android.os.Looper.loop(Looper.java:154)?
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)?
                                                                      at java.lang.reflect.Method.invoke(Native Method)?
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)?
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)?
                                                                   Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                      at android.util.Log.printlns(Log.java:584)
                                                                      at android.util.Log.e(Log.java:360)
                                                                      at com.google.firebase.crash.FirebaseCrash$zzc.uncaughtException(Unknown Source)
                                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                                                                      at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:118)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)?
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)?
                                                                      at android.os.Looper.loop(Looper.java:154)?
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)?
                                                                      at java.lang.reflect.Method.invoke(Native Method)?
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)?
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)?
                                                                   Caused by: com.emuzi.wallet.module.LogoutException
                                                                      at com.emuzi.wallet.service.CheckLogoutOperator$1.onNext(CheckLogoutOperator.java:46)
                                                                      at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:41)
                                                                      at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:38)
                                                                      at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
                                                                      at rx.Subscriber.setProducer(Subscriber.java:209)
                                                                      at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                      at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                      at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                      at rx.Observable.unsafeSubscribe(Observable.java:10200)
                                                                      at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                      at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                      at java.lang.Thread.run(Thread.java:762)

**Comment by akarnokd** [comment]
Please provide some context or code that reproduces your problem.

Relevant error: com.emuzi.wallet.module.LogoutException

**Comment by a8453770** [comment]
I found the problem because of the end of the Activity lifecycle, and also called OnNext.
