### ISSUE TITLE
 retrofit2.adapter.rxjava2.HttpException: HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by fakhriamir** [ReactiveX/RxJava#5750]
```
.map { group ->
                    val groupType = if (group.isPromoted) WebService.GroupType.PROMOTED
                    else WebService.GroupType.SIMPLE

                    val groupId = group.id
                    Tools.webservice.groupGames(groupType, groupId)
                            .subscribeOn(Schedulers.io())
                            .observeOn(Schedulers.computation())
                            .map { games -> cacheGroupGames(groupId, games) }
                            .observeOn(AndroidSchedulers.mainThread())
                            .map { cachedGroupGames(groupId) }
                            .mergeWith(Observable.just(cachedGroupGames(groupId)))
                            .doOnNext { games ->
                                groupList.find { a -> a.id == groupId }
                                        ?.games = realm.copyFromRealm(games)
                            }
                }
```

: retrofit2.adapter.rxjava2.HttpException: HTTP 500 Internal Server Error
at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
at io.reactivex.Observable.subscribe(Observable.java:10901)
at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
at io.reactivex.Observable.subscribe(Observable.java:10901)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

**Comment by akarnokd** [comment]
This is not an RxJava problem but a network/retrofit problem. I suggest you ask questions on StackOverflow instead.

**Comment by chhatrasal09** [comment]
Hi,
I am also facing the same issue. HTTP 500 is Internal Server Error, means server is sending this error. But RxJava should not throw an exception and crash the app, instead the exception should be handled and thrown to onError(Throwable) method. @akarnokd
