### ISSUE TITLE
java.lang.ClassCastException: libcore.util.NativeAllocationRegistry$CleanerRunner cannot be cast to io.reactivex.ObservableSource

### ISSUE THREAD

**Issue by Zhuinden** [ReactiveX/RxJava#5852]
**Version:** RxJava 2.1.6

----

I actually got `short[] cannot be cast to io.reactivex.ObservableSource` and `StringBuilder cannot be cast to io.reactivex.ObservableSource` too, from the same amount of code. I don't use `short[]` anywhere so that was a surprise!

The native allocation registry really was out of the blue, though. But that problem came from a combination of `repeatWhen`, `switchMap` and `toList`, with me trying to `toList()` the `repeat` which kinda native-crashed everything.

------

Anyways, so I figured I'd fix that problem, now I have

       java.lang.ClassCastException: short[] cannot be cast to io.reactivex.SingleSource

Specifically 

```
02-15 00:44:32.185 15614-15614/: java.lang.ClassCastException: short[] cannot be cast to io.reactivex.SingleSource
02-15 00:44:32.188 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.onNext(ObservableFlatMapSingle.java:100)
02-15 00:44:32.190 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate$RetryBiObserver.onNext(ObservableRetryBiPredicate.java:66)
02-15 00:44:32.191 15614-15614/:     at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:108)
02-15 00:44:32.193 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRepeatWhen$RepeatWhenObserver.onNext(ObservableRepeatWhen.java:100)
02-15 00:44:32.195 15614-15614/:     at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
02-15 00:44:32.196 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111)
02-15 00:44:32.198 15614-15614/:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
02-15 00:44:32.200 15614-15614/:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
02-15 00:44:32.202 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.203 15614-15614/:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
02-15 00:44:32.203 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.204 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
02-15 00:44:32.205 15614-15614/:     at io.reactivex.Single.subscribe(Single.java:2801)
02-15 00:44:32.206 15614-15614/:     at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
02-15 00:44:32.207 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.208 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRepeatWhen$RepeatWhenObserver.subscribeNext(ObservableRepeatWhen.java:150)
02-15 00:44:32.209 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRepeatWhen.subscribeActual(ObservableRepeatWhen.java:60)
02-15 00:44:32.210 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.212 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate$RetryBiObserver.subscribeNext(ObservableRetryBiPredicate.java:100)
02-15 00:44:32.213 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate.subscribeActual(ObservableRetryBiPredicate.java:39)
02-15 00:44:32.214 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.215 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableFlatMapSingle.subscribeActual(ObservableFlatMapSingle.java:48)
02-15 00:44:32.216 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.217 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableDelay.subscribeActual(ObservableDelay.java:50)
02-15 00:44:32.218 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.219 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableTakeUntil.subscribeActual(ObservableTakeUntil.java:41)
02-15 00:44:32.220 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.222 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
02-15 00:44:32.223 15614-15614/:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
02-15 00:44:32.224 15614-15614/:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
02-15 00:44:32.224 15614-15614/:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
02-15 00:44:32.225 15614-15614/:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-15 00:44:32.226 15614-15614/:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
02-15 00:44:32.227 15614-15614/:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-15 00:44:32.227 15614-15614/:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-15 00:44:32.228 15614-15614/:     at java.lang.Thread.run(Thread.java:761)
02-15 00:44:32.229 15614-15614/: java.lang.ClassCastException: short[] cannot be cast to io.reactivex.SingleSource
02-15 00:44:32.230 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.onNext(ObservableFlatMapSingle.java:100)
02-15 00:44:32.230 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate$RetryBiObserver.onNext(ObservableRetryBiPredicate.java:66)
02-15 00:44:32.231 15614-15614/:     at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:108)
02-15 00:44:32.232 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRepeatWhen$RepeatWhenObserver.onNext(ObservableRepeatWhen.java:100)
02-15 00:44:32.233 15614-15614/:     at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59)
02-15 00:44:32.233 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111)
02-15 00:44:32.233 15614-15614/:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
02-15 00:44:32.234 15614-15614/:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
02-15 00:44:32.234 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.234 15614-15614/:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
02-15 00:44:32.235 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.235 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
02-15 00:44:32.235 15614-15614/:     at io.reactivex.Single.subscribe(Single.java:2801)
02-15 00:44:32.236 15614-15614/:     at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
02-15 00:44:32.236 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.237 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRepeatWhen$RepeatWhenObserver.subscribeNext(ObservableRepeatWhen.java:150)
02-15 00:44:32.237 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRepeatWhen.subscribeActual(ObservableRepeatWhen.java:60)
02-15 00:44:32.237 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.238 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate$RetryBiObserver.subscribeNext(ObservableRetryBiPredicate.java:100)
02-15 00:44:32.239 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate.subscribeActual(ObservableRetryBiPredicate.java:39)
02-15 00:44:32.239 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.239 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableFlatMapSingle.subscribeActual(ObservableFlatMapSingle.java:48)
02-15 00:44:32.240 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.240 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableDelay.subscribeActual(ObservableDelay.java:50)
02-15 00:44:32.241 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.242 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableTakeUntil.subscribeActual(ObservableTakeUntil.java:41)
02-15 00:44:32.242 15614-15614/:     at io.reactivex.Observable.subscribe(Observable.java:10981)
02-15 00:44:32.243 15614-15614/:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
02-15 00:44:32.243 15614-15614/:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
02-15 00:44:32.243 15614-15614/:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
02-15 00:44:32.243 15614-15614/:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
02-15 00:44:32.244 15614-15614/:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-15 00:44:32.244 15614-15614/:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
02-15 00:44:32.244 15614-15614/:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-15 00:44:32.245 15614-15614/:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-15 00:44:32.245 15614-15614/:     at java.lang.Thread.run(Thread.java:761)
```

Code sample:

``` kotlin
        ApiService.gameDetails(gameId) // Single<T> 
            .subscribeOn(Schedulers.io())
            .toObservable()
            .repeatWhen { it.delay(30, TimeUnit.SECONDS) }
            .retry({ retryCount, t ->
                   retryCount <= 2 && isNetworkException(t)
            })
            .flatMapSingle { gameDetails ->
                ApiService.players(gameDetails.matchId) // Single<T>
                    .subscribeOn(Schedulers.io())
                    .toObservable()
                    .flatMapIterable { players -> players.playerList }
                    .filter { player -> !player.notPlaying }
                    .toList()
            }
            .observeOn(AndroidSchedulers.mainThread())
            .subscribeBy(
                onNext = { players ->
                    // irrelevant
                },
                onError = {
                    it.printStackTrace()
                }
            )
```

How the heck am I getting a class cast exception for `short[]`? :smile:

**Comment by Zhuinden** [comment]
On one side-note, in the end, I fixed it with following setup:

``` kotlin
        Observable.interval(0L, 30L, TimeUnit.SECONDS)
            .flatMap {
                ApiService.gameDetails(gameId)
                    .scheduleOn(Schedulers.io())
                    .retry(retryHandler)
                    .toObservable()
            }
            .flatMapSingle { gameDetails ->
                ApiService.players(gameDetails.matchId)
                    .scheduleOn(Schedulers.io())
                    .retry(retryHandler)
                    .toObservable()
                    .flatMapIterable { players -> players.playerList }
                    .filter { player -> !player.notPlaying }
                    .toList()
            }
            .observeOn(AndroidSchedulers.mainThread())
            .subscribeBy(
                onNext = { players ->
                    // irrelevant
                },
                onError = {
                    it.printStackTrace()
                }
            )
```

But I think this is probably still an issue inside Rx, because it crashes in Rx internals..

**Comment by akarnokd** [comment]
This is not an issue inside RxJava but a consequence of likely bad compiler. What Kotlin version are you using? Have you tried with plain Java code? How often does the error appear? Is it the same bad type or different every time?

**Comment by Zhuinden** [comment]
Kotlin 1.2.10.

Once I replaced the `repeatWhen + flatMapSingle` that I inherited from other parts of the codebase, replaced with `observable.interval + flatMap` (which I would have written on my own in the first place), the issue is gone.

I haven't tried with Java code. I only got `StringBuffer`, `short[]` and that very strange libcore thing which I  don't know where it came from.

**Comment by akarnokd** [comment]
This looks like a compiler bug:

- https://youtrack.jetbrains.com/issue/KT-17171

Could be the same problem, could be a new one. I suggest you report your case, with a minimal working example reproducing the problem, on https://youtrack.jetbrains.com/ . They will also likely ask you for the generated bytecode.

**Comment by Zhuinden** [comment]
Interesting. I'll look into it later then if I can reproduce it in a clinical scenario. 

Anyways, thanks for the info, I guess it's not Rx internals causing the quarrels after all :smile:
