### ISSUE TITLE
InterruptedException with scanWith and ConnectableFlowable

### ISSUE THREAD

**Issue by BraisGabin** [ReactiveX/RxJava#5961]
I'm getting this error:
```
io.reactivex.exceptions.OnErrorNotImplementedException: java.lang.InterruptedException
    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
    at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
    at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onError(FlowableSubscribeOn.java:102)
    at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:221)
    at io.reactivex.internal.operators.flowable.FlowableReplay$UnboundedReplayBuffer.replay(FlowableReplay.java:672)
    at io.reactivex.internal.operators.flowable.FlowableReplay$InnerSubscription.request(FlowableReplay.java:538)
    at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.requestUpstream(FlowableSubscribeOn.java:133)
    at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onSubscribe(FlowableSubscribeOn.java:90)
    at io.reactivex.internal.operators.flowable.FlowableReplay$ReplayPublisher.subscribe(FlowableReplay.java:1239)
    at io.reactivex.internal.operators.flowable.FlowableReplay.subscribeActual(FlowableReplay.java:161)
    at io.reactivex.Flowable.subscribe(Flowable.java:14291)
    at io.reactivex.Flowable.subscribe(Flowable.java:14237)
    at io.reactivex.internal.operators.flowable.FlowableAutoConnect.subscribeActual(FlowableAutoConnect.java:48)
    at io.reactivex.Flowable.subscribe(Flowable.java:14291)
    at io.reactivex.Flowable.subscribe(Flowable.java:14237)
    at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
    at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
    at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:86)
    at io.reactivex.Single.blockingGet(Single.java:2492)
    at com.example.brais.myapplication.MainActivity$onCreate$flowable$1.call(MainActivity.kt:24)
    at com.example.brais.myapplication.MainActivity$onCreate$flowable$1.call(MainActivity.kt:12)
    at io.reactivex.internal.operators.flowable.FlowableScanSeed.subscribeActual(FlowableScanSeed.java:45)
    at io.reactivex.Flowable.subscribe(Flowable.java:14291)
    at io.reactivex.internal.operators.flowable.FlowableReplay.connect(FlowableReplay.java:233)
    at io.reactivex.internal.operators.flowable.FlowableAutoConnect.subscribeActual(FlowableAutoConnect.java:50)
    ... 10 more
Caused by: java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1022)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1328)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
    at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:83)
    ... 17 more
```

You can reproduce that error with this code:

```kotlin
var disposable: Disposable? = null

val single = Single.just("")
        .delay(5, TimeUnit.SECONDS)

val flowable = Flowable.never<String>()
        .scanWith({ single.blockingGet() }, { _, _ -> "" })
        .replay()
        .autoConnect()
        .subscribeOn(Schedulers.io()) // moving this line up fix the problem

Single.just("")
        .subscribeOn(Schedulers.computation())
        .subscribe(Consumer {
            disposable = flowable
                    .subscribe()
        })

Single.just("")
        .delay(100, TimeUnit.MILLISECONDS)
        .subscribe(Consumer {
            disposable!!.dispose()
            flowable.subscribe()
        })
```

I found a way to workaround this problem just moving the `.subscribeOn(Schedulers.io())` before the `.replay()`.

Edit: tested with `v2.1.12`

**Comment by akarnokd** [comment]
What is the problem here? You are using `blockingGet` which will block and gets interrupted because of `disposable!!.dispose()`.

**Comment by BraisGabin** [comment]
I expect that the `scanWith` doesn't realise about the dispose because it's behind a `ConnectableFlowable`.

And even if that's not true. If all the stream was disposed I expect to get a fresh start when I subscribe to it the second time.

**Comment by akarnokd** [comment]
[autoConnect](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/flowables/ConnectableFlowable.html#autoConnect--) connects at most once. If the upstream fails, it will not start over.

> I expect that the scanWith doesn't realise about the dispose because it's behind a

You trigger the first subscription on a background thread which now becomes target for task cancellation. This includes the initial value generation part where you block and thus the underlying thread will be interrupted.

Also calling `subscribe` from within `subscribe` and using `blockingX` is discouraged.

**Comment by BraisGabin** [comment]
But I have the `initialValue` inside a `Single`. So I don't know any other way to get that value to feed my `scan` than `blokingGet()`.

I think that a `scanWith(Single, accumulator)` would be usefull to solve this problem. You can convert a Callable to a Single easily with a `Single.fromCallable`. But the only way I can think to convert a Single to a Callable is `blokingGet()`.

PROs: it'd be easier to manage the threading and it seems more "reactive".

**Comment by akarnokd** [comment]
Use `startWith` then `scan` with a `BiFunction`. Alternatively use `flatMapFlowable` to get the success item and have it as the initial value with `scan` running the `Flowable` inside.

**Comment by BraisGabin** [comment]
> Alternatively use flatMapFlowable to get the success item and have it as the initial value with scan running the Flowable inside.

Thank you so much man! That's it! I didn't think about that option.

I really think that a `scanWith(Single, accumulator)` would be helpful but using the `flatMapFlowable` completely solve my problem. Thanks again!

**Comment by akarnokd** [comment]
`scanWith(Single, ...)` would be no more efficient than the suggested flatMap based approach.

**Comment by ConCaRo** [comment]
> 

I got the same issue with @BraisGabin , and moving `.subscribeOn(Schedulers.io())` before the `.replay()` works well, but I cannot understand why?. The subscribeOn always make the Observable do the same thread with `Schedulers.io()`?
