### ISSUE TITLE
 Caused by: java.lang.RuntimeException: java.lang.InterruptedException

### ISSUE THREAD

**Issue by SergeyBurlaka** [ReactiveX/RxJava#5970]
Thanks for using RxJava but before you post an issue, please consider the following points:

uses     implementation 'io.reactivex.rxjava2:rxjava:2.1.9'

I am trying parsing via rxJava 

```kotlin
override fun restore(): Observable<List<Pair<String, String>?>> {
return backupRemoteSource.getBackup()
                .flatMap { urlBackup ->
                    Observable.create<Boolean> { emitter ->
                        var isRestore = true
                        try {
                            val url = URL(urlBackup)
                            url.openConnection()
                            InputStreamReader(url.openStream(), "UTF-8").use {
                                val jsonReader = JsonReader(it)

                                jsonReader.beginArray()

                                var tour: Tour? = null

                                /* tours */
                                while (jsonReader.hasNext() ) {

                                    /* tour item*/
                                    jsonReader.beginObject()
                                    while (jsonReader.hasNext() && isRestore) {

                                        val name = jsonReader.nextName()

                                        when (name) {

                                            "tourInfo" -> {

                                                tour = tourMapper.fromRx(gsonParser.fromJson<TourBackup>(jsonReader, TourBackup::class.java))
                                                        .flatMap {


                                                            tourLocalSource.save(it)
                                                        }.blockingFirst()

                                                Log.i(tag, "\n@saved tour")
                                            }

                                      jsonReader.endArray()
                                            }
                                        }

                                    }
                                    jsonReader.endObject()
                                }
                                jsonReader.endArray()

                                emitter.onNext(true)
                            }
                        } catch (error: InterruptedException) {
                            emitter.onError(BackupException(error.message ?: "unknown exception"))
                        } catch (error: NoSuchFileException) {
                            emitter.onError(BackupException(error.message ?: "unknown exception"))
                        } catch (error: IOException) {
                            emitter.onError(BackupException(error.message ?: "unknown exception"))
                        }

                        emitter.setCancellable({
                            Log.d(tag,"cancel restore")
                            isRestore = false
                        })
                    }

                }
....}
```
then i call:

```kotlin
  fun restore() {
     
        disposables.add(backUpRepo.restore()
                .compose(RxUtils.ioToMainTransformer())
                .subscribe()
    }
```
but when calling 

`disposables.dispose()`

i get crash:

```
`04-23 14:57:27.456 28001-28063/com.jellyworkz.udark.debug E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
    Process: com.jellyworkz.udark.debug, PID: 28001
    io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: java.lang.InterruptedException`


....

    Caused by: java.lang.RuntimeException: java.lang.InterruptedException
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
        at io.reactivex.internal.observers.BlockingBaseObserver.blockingGet(BlockingBaseObserver.java:74)
        at io.reactivex.Observable.blockingFirst(Observable.java:4987)
        at com.jellyworkz.udark.backup.source.BackupRepositoryImpl$restore$1$1.subscribe(BackupRepositoryImpl.kt:113)
```

Where do i wrong?

**Comment by akarnokd** [comment]
Signalling an error after disposing a `create` source usually ends with a crash. You should do an `isDisposed` check before calling `emitter.onError` or call `emitter.tryOnError` to avoid such crashes.

[Further reading](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling)

**Comment by akarnokd** [comment]
Also please do not cross post: https://stackoverflow.com/questions/49980858/caused-by-java-lang-runtimeexception-java-lang-interruptedexception

**Comment by SergeyBurlaka** [comment]
Used `emitter.tryOnError` and it is works greate.
 @akarnokd, thanks!
