### ISSUE TITLE
2.x: RxJava combine with RxLifecycle throw CancellationException

### ISSUE THREAD

**Issue by artshell** [ReactiveX/RxJava#6063]
RxJava 2.1.14

java.util.concurrent.CancellationException
at io.reactivex.internal.operators.single.SingleTakeUntil$TakeUntilOtherSubscriber.onNext(SingleTakeUntil.java:145)
        at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:133)
        at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java:63)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:570)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:565)
        at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:268)
        at io.reactivex.subjects.SerializedSubject.onNext(SerializedSubject.java:105)
        at com.ukec.stuliving.ui.activity.BaseLifecycleActivity.onPause(BaseLifecycleActivity.java:65)
        at android.app.Activity.performPause(Activity.java:6996)

```java
    @Override
    protected void onPause() {
        mTakeSubject.onNext(ActivityEvent.PAUSE);
        super.onPause();
    }
```

**Comment by akarnokd** [comment]
What is the problem, the context, the code to reproduce the issue? What documentation have you looked at? Why do you think posting just stacktrace is enough for an external party to diagnose your problem?

Please provide the additional details of your problem.

**Comment by artshell** [comment]
I'am sorry, can't reproduce the issue, please close the issue.
