### ISSUE TITLE
[RxJava_1.1.6]   java.lang.VerifyError: Verifier rejected class rx.internal.util.RxRingBuffer: int rx.internal.util.RxRingBuffer.available(): [0xFFFFFFFF] register index out of range (2 >= 2) (declaration of 'rx.internal.util.RxRingBuffer' appears in

### ISSUE THREAD

**Issue by SpringBegin** [ReactiveX/RxJava#6138]
hi，I have a RxJava problem in my project,  I can't find the reason, please me, thank you  

version: RxJava_1.1.6 & RxAndroid_1.2.1
Android version： Android O （Android 8.1）

 **- questions: app_crash**
```
java.lang.VerifyError	Verifier rejected class rx.internal.util.RxRingBuffer: int rx.internal.util.RxRingBuffer.available(): [0xFFFFFFFF] register index out of range (2 >= 2) (declaration of 'rx.internal.util.RxRingBuffer' appears in xxx.apk)
Observable.java	6394
java.lang.VerifyError: Verifier rejected class rx.internal.util.RxRingBuffer: int rx.internal.util.RxRingBuffer.available(): [0xFFFFFFFF] register index out of range (2 >= 2) (declaration of 'rx.internal.util.RxRingBuffer' appears in xxx.apk)
	at rx.Observable.observeOn(Observable.java:6394)
	at com.xx.xxx.utils.SimpleScheduler.handleTask(SimpleScheduler.java:42)
```

**Part of the code：**

```java
 private static void handleTask(final Runnable runnable, long delayMillis, boolean runOnMainThread) {
        Observable.just(0)
                .delay(delayMillis, TimeUnit.MILLISECONDS)
                .observeOn(runOnMainThread ? AndroidSchedulers.mainThread() : AndroidSchedulers.from(getWorkLooper()))
                .filter(new Func1<Integer, Boolean>() {
                    @Override
                    public Boolean call(Integer integer) {
                        runnable.run();
                        return null;
                    }
                })
                .subscribe(new Subscriber<Integer>() {
                    @Override
                    public void onCompleted() {
                        unsubscribe();
                    }

                    @Override
                    public void onError(Throwable throwable) {

                    }

                    @Override
                    public void onNext(Integer integer) {

                    }
                });

    }
```

**Comment by akarnokd** [comment]
> please me

I don't think we can please you:

- RxJava 1 is no longer supported.
- The same class files are used on all platforms and unless the jar file is corrupted, this should not happen.
- It is possible your tooling messes up the RxJava classes upon build; see if you have your tooling up to date. See if ProGuard/Retrolambda appears along such errors on the internet.
- This is an Android specific issue, please consider asking this question on StackOverflow.
