### ISSUE TITLE
2.x: RxJavaPlugin crash in ObservableObserveOn (with kotlin)

### ISSUE THREAD

**Issue by Rajin9601** [ReactiveX/RxJava#6157]
When `RxJavaPlugin#setOnObservableSubscribe` is used with `observeOn`, sometimes it crashes.

## Crash Example

```kotlin
RxJavaPlugins.setOnObservableSubscribe { observable, observer ->
            object : Observer<Any> {
                override fun onComplete() {
                    observer.onComplete()
                }

                override fun onSubscribe(d: Disposable) {
                    observer.onSubscribe(d)
                }

                override fun onNext(t: Any) {
                    observer.onNext(t)
                }

                override fun onError(e: Throwable) {
                    logException(e)
                    observer.onError(e)
                }
            }
        }
```

Crash log

```
08-14 11:01:57.077 5495-5495/@@@ E/AndroidRuntime: FATAL EXCEPTION: main
    Process: @@@, PID: 5495
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter t
        at @@@.onNext(@@@RxJavaPlugins.kt)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainFused(ObservableObserveOn.java:227)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:250)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6464)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
```

RxJava version : 2.1.14

## Problem

The problem is that in `ObserveOnObserver#drainFused`, there is a code that calls onNext with null.

https://github.com/ReactiveX/RxJava/blob/835ab00699d39c092ef6e90cf1868722b9180fe1/src/main/java/io/reactivex/internal/operators/observable/ObservableObserveOn.java#L227

This gets to observer created from the RxJavaPlugins, and kotlin tries to cast null to Any, which crashes the app. Because `Observer#onNext` has NonNull annotation, there is no way for library user to avoid this problem in kotlin.

What I cannot understand is why `ObservableObserveOn#drainFused` calls onNext with null even though it has NonNull annotation. 

Thanks in advance.

**Comment by akarnokd** [comment]
Do not pass the Disposable received in onSubscribe directly to the downstream.

**Comment by akarnokd** [comment]
See the **important** note here https://github.com/ReactiveX/RxJava/blob/2.x/docs/Writing-operators-for-2.0.md#stable-prefetching

**Comment by Rajin9601** [comment]
Thank you. Didn't know about operator fusion. I'll close this issue.
