### ISSUE TITLE
2.x: Value loss with BehaviorSubject

### ISSUE THREAD

**Issue by thuytrinh** [ReactiveX/RxJava#6161]
RxJava version: `2.2.0`
Java version: `java version "1.8.0_181"`
Kotlin version: `1.2.60`

Basically the following test simulates a sort of like producer-consumer-like logic. There's a `requestPublisher` which emits a bunch of events as numbers. `requestPublisher` is the producer here. Then there's a consumer `processRequest` which will wait till the `whenConnected` emits true to process the requests from `resultPublisher`. The `processRequest` consumer will transform a request as a number into a string.

**Expected**: The number of results that `resultObserver` has received should be `requestCount`.
**Actual**: Sometimes the number of results that `resultObserver` has received is smaller than `requestCount`.

```kotlin
package thuy.androidsamples

import io.reactivex.Observable
import io.reactivex.Single
import io.reactivex.observers.BaseTestConsumer
import io.reactivex.schedulers.Schedulers
import io.reactivex.subjects.BehaviorSubject
import org.junit.Test
import java.util.concurrent.TimeUnit

class SubjectTest {
  @Test
  fun test() {
    (1..50).forEach { r ->
      val requestCount = 100 * r
      println("Testing round $r with request count: $requestCount")
      tryToReproduceValueLostIssue(requestCount)
    }
  }

  private fun tryToReproduceValueLostIssue(requestCount: Int) {
    // Arrange
    val requestPublisher = BehaviorSubject.create<Int>().toSerialized()
    // requestPublisher.subscribe { println("[DISPATCHED] $it") }
    val resultPublisher = BehaviorSubject.create<String>()
    val resultObserver = resultPublisher.test()

    val whenConnected = BehaviorSubject.createDefault(false)
    fun <T> Observable<T>.waitTillConnected(): Observable<T> =
      flatMap { x ->
        whenConnected
          .filter { it }
          .firstOrError()
          .map { x }
          .toObservable()
      }

    val processRequest = requestPublisher
      .observeOn(Schedulers.io())
      .waitTillConnected()
      // .doOnNext { println("[STARTED] $it") }
      .flatMap { x ->
        Single
          .fromCallable {
            // Sleep to simulate a slight hiccup while dealing with a request.
            TimeUnit.MILLISECONDS.sleep(600)
            "$x ✓"
          }
          // .doOnNext { println("[FINISHED] $it") }
          .toObservable()
      }

    // Act
    processRequest.subscribe(resultPublisher::onNext)

    whenConnected.onNext(true)

    (1..requestCount).forEach {
      TimeUnit.MILLISECONDS.sleep(100)
      requestPublisher.onNext(it)
    }

    // Assert
    val timeout: Long = 2
    resultObserver.awaitCount(requestCount, BaseTestConsumer.TestWaitStrategy.SLEEP_10MS, TimeUnit.MINUTES.toMillis(timeout))
    resultObserver.assertValueCount(requestCount)
  }
}
```

In my testing, the test above will fail:

```
Testing round 1 with request count: 100
Testing round 2 with request count: 200
Testing round 3 with request count: 300

java.lang.AssertionError: Value counts differ; Expected: 300, Actual: 250 (latch = 1, values = 250, errors = 0, completions = 0, timeout!)

	at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:190)
	at io.reactivex.observers.BaseTestConsumer.assertValueCount(BaseTestConsumer.java:516)
	at thuy.androidsamples.SubjectTest.tryToReproduceValueLostIssue(SubjectTest.kt:66)
	at thuy.androidsamples.SubjectTest.test(SubjectTest.kt:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

I suspect there's something related to backpressure which I'm not quite familiar with or maybe there's a bug with `BehaviorSubject`.

**Comment by akarnokd** [comment]
You sleep 600 milliseconds between items. With 300 items, that's 180 seconds or 3 minutes. Generating 300 items takes 30 seconds and the wait for items starts after that, so effectively the test ends after 150 seconds. 150 allowed/180 needed * 300 expected = 250 actual items. Of course generating 400 items with the same sleeping will require even more time.

So this is not a bug in RxJava but in your test setup and the setup has no backpressure-related aspect either.
