### ISSUE TITLE
Error in non-eager disposer of the using operator is not received by the onError handler

### ISSUE THREAD

**Issue by bric3** [ReactiveX/RxJava#6189]
<details><summary>Thanks for using RxJava but before you post an issue, please consider the following points:</summary>

  - [x] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `2.x`) that would be great.

  - [x] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

  - [x] RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

  - [x] If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).

  - [x] Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

  - [x] Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.
</details>

Tried with RxJava 2.1.17 and 2.2.1

I'm not sure this is a bug or a mis-usage or something one has to live with of the `using(...)` operator. But it seems that an exception called in the disposer is not handed over to `onError`, if the `using` operator is configured to dispose the resource **after** the terminal event (`eager` is set to false).

```java
    Single.using(() -> okHttpClient.newCall(request).execute(),
                 response -> Single.just("whatever code"),
                 response -> {
                     throw new IOException("broken pipe"); // supposing it's happening in response.close();
                 },
                 true)
          .subscribeOn(Schedulers.io())
          .subscribe(async::resume,
                     throwable -> /* handle exception */);
```

In this case the `IOException` is raised after subscribe callbacks are called. This code may _complete_ without error, but the disposal logs the _undeliverable error_.

```
io.reactivex.exceptions.UndeliverableException: java.io.IOException: broken pipe
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.single.SingleUsing$UsingSingleObserver.disposeAfter(SingleUsing.java:190)
        ...
```

Of course setting the eager flag to `true` or employing the `using` operator without this flag makes the error to be handled via the `onError` _receiver_. But that does not work if the resource has to be disposed after the `onComplete` execution, of course one can customise the RxJavaPlugins, but that feels a bit wrong beyond simple logging.

I wonder if this could be meaningful to make the error handler receive errors raised during disposal.
I find the behaviour kinda logical when RxJava event lifecycle is understood but novices may find the this a bit puzzling. That's why I'm asking.

**Comment by akarnokd** [comment]
By definition, non eager using() disposes after termination or cancellation so an exception can't go into the consumer anymore.

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
