### ISSUE TITLE
Rx Java 2.2.1 UndeliverableException is thrown even after using tryOnError in SingleEmitter

### ISSUE THREAD

**Issue by Ranjith49** [ReactiveX/RxJava#6213]
In our case , 
We have a use case of fetching remote Ad from an API (Single)  and map it to observable .
We wait for 5 seconds , and then timeout the source

SingleEmitter on Error here tries to do post error to downstream using "tryOnError".
Even the observable is terminated due to timeout , we still get the "UndeliverableException"

```
Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.lang.Exception: Native Ad Failed to load. i: 3
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
       at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutObserver.onError(ObservableTimeoutTimed.java:112)
       at io.reactivex.internal.observers.DeferredScalarDisposable.error(DeferredScalarDisposable.java:100)
       at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onError(SingleToObservable.java:77)
       at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
       at in.startv.hotstar.rocky.ads.nativeads.RxNativeAdsFetcher.onAdFailedToLoad(RxNativeAdsFetcher.java:92)
       at com.google.android.gms.internal.zzjg.onAdClosed(Unknown Source)
```

**Code** : 

```java
rxNativeAdsFetcher
                .fetch(AdUtils.getNativeAdUnitId(adConfig, placementId), placementId, null)
                .toObservable()
                .timeout(5, TimeUnit.SECONDS);
```

**Single Creation :** 

```java
public Single<Ad> fetch(String id, String pId, Map<String, String> params) {
        return Single.create(this);
    }

 @Override
    public void onAdFailedToLoad(int i) {
        Timber.d("native_ad on error placement id = %s", placementId);

        super.onAdFailedToLoad(i);
        emitter.tryOnError(e);
    }

@Override
    public void subscribe(SingleEmitter<NativeAd> emitter) throws Exception {
      this.emitter = emitter;
   }

```
   
Can any one please let me know why this is happening , although I call tryonError?
Is it a race condition by time the dispose state is propagated to the upstream , upstream tried to deliver the event to downstream and error happened ?

**Comment by akarnokd** [comment]
What is the version you are using?

> Is it a race condition by time the dispose state is propagated to the upstream , upstream tried to deliver the event to downstream and error happened ?

Operators, such as `timeout` will route undeliverable errors even if you used `tryOnError` somewhere upstream. This may happen with races between emission and cancellation by timeout, but the window for it is pretty narrow. Does this happen if you timeout with 4 or 6 seconds?

In general, it is always recommended to install a global error handler to avoid crashes on Android: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

**Comment by Ranjith49** [comment]
@akarnokd 
Version used is 2.2.1
Yes In our case  timeout is at 5 seconds

**Comment by akarnokd** [comment]
Does this happen if you timeout with 4 or 6 seconds?

**Comment by akarnokd** [comment]
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.
