### ISSUE TITLE
UndeliverableException with a flatMap

### ISSUE THREAD

**Issue by danielesegato** [ReactiveX/RxJava#6251]
My app is experiencing this crashes

`d.b.c.f` is io.reactivex.exceptions.UndeliverableException deobfuscated

```
Fatal Exception: d.b.c.f: java.net.UnknownHostException: Unable to resolve host "<redacted>": No address associated with hostname
       at io.reactivex.plugins.RxJavaPlugins.onError(SourceFile:8)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onError(SourceFile:19)
       at io.reactivex.internal.observers.DeferredScalarDisposable.error(SourceFile:4)
       at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onError(SourceFile:4)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SourceFile:2)
       at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SourceFile:2)
       at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onError(SourceFile:13)
       at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(SourceFile:11)
       at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(SourceFile:12)
       at io.reactivex.Observable.subscribe(SourceFile:116)
       at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(SourceFile:1)
       at io.reactivex.Observable.subscribe(SourceFile:116)
       at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(SourceFile:1)
       at io.reactivex.Single.subscribe(SourceFile:35)
       at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SourceFile:1)
       at io.reactivex.Single.subscribe(SourceFile:35)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SourceFile:1)
       at io.reactivex.Scheduler$DisposeTask.run(SourceFile:2)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:2)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:1)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.net.UnknownHostException: Unable to resolve host "<redacted>": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
       at java.net.InetAddress.getAllByName(InetAddress.java:752)
       at okhttp3.Dns$1.lookup(SourceFile:1)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(SourceFile:27)
       at okhttp3.internal.connection.RouteSelector.nextProxy(SourceFile:3)
       at okhttp3.internal.connection.RouteSelector.next(SourceFile:4)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:39)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:13)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:6)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:5)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:11)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:2)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:22)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:11)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:2)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:22)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:11)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:13)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:11)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:2)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:25)
       at okhttp3.RealCall.execute(SourceFile:8)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(SourceFile:5)
       at retrofit2.OkHttpCall.execute(SourceFile:18)
       at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(SourceFile:4)
       at io.reactivex.Observable.subscribe(SourceFile:116)
       at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(SourceFile:1)
       at io.reactivex.Observable.subscribe(SourceFile:116)
       at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(SourceFile:1)
       at io.reactivex.Single.subscribe(SourceFile:35)
       at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SourceFile:1)
       at io.reactivex.Single.subscribe(SourceFile:35)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SourceFile:1)
       at io.reactivex.Scheduler$DisposeTask.run(SourceFile:2)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:2)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:1)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

and similar ones.

I'm aware of this: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

But after some struggle I've finally narrowed down where this could happen in my code and I think this is more a bug in flatMap then something I should handle by setting a custom behavior on RxJavaPlugin error handling.

It's basically a portion of code like this:
```kotlin
Observable.fromIterable(list)
                .flatMap {
                    when (it) {
                        Option.A -> api.getA()
                        Option.B -> api.getB()
                        // ...
                        Option.N -> api.getN()
                    }
                            .map { mapToSomething(it) }
                            .subscribeOn(Schedulers.io())
                            .toObservable()
                }
```

And since this:
```
       at io.reactivex.plugins.RxJavaPlugins.onError(SourceFile:8)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onError(SourceFile:19)
```

Can only mean that I end up in the else here:
```java
        @Override
        public void onError(Throwable t) {
            if (parent.errors.addThrowable(t)) {
                if (!parent.delayErrors) {
                    parent.disposeAll();
                }
                done = true;
                parent.drain();
            } else {
                RxJavaPlugins.onError(t);
            }
        }
```
the only reason `parent.errors.addThrowable(t)` return `false` is if the parent throwable has been terminated.

I don't think my code should need to do more then just handle the subscription error, this shouldn't crash.
I expected an error to cause the disposal of all the Observables that flatMap was subscribed to, apparently that doesn't happen or there's a bug in retrofit2 - rxjava2 adapter.

versions:
```groovy
    implementation 'io.reactivex.rxjava2:rxjava:2.1.14'
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.2.0'
    implementation 'com.github.akarnokd:rxjava2-extensions:0.20.3'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.4.0'
```

**Comment by akarnokd** [comment]
There is no bug in `flatMap`. You have to decide what to do with multiple errors: wait for all or get the first (or some) and ignore the rest in the global error handler. RxJava can't decide what is important for you and has the courtesy of not just ignoring additional errors.

**Comment by danielesegato** [comment]
@akarnokd how?
the Observable return the first error in my subscribe callback.

how am I supposed to decide what to do?

**Comment by akarnokd** [comment]
> how am I supposed to decide what to do?

Given the options, *you are* in the best option to decide this given your context, constraints and requirements.

**Comment by danielesegato** [comment]
The only option I see is to override `RxJavaPlugins.setErrorHandler()`, which is what I did now.
I'd rather manage it locally to that observable. Doesn't look right to be forced to use that method. Specially on libraries.

**Comment by akarnokd** [comment]
> I'd rather manage it locally to that observable.

It makes no sense. You can't do much with those extra exceptions other than waiting for them all, logging and/or ignoring them. You can't keep signaling on the observable as the protocol doesn't allow it.

Let's assume the protocol allowed multiple error signals. How would you do if there are no more coming of them? Probably by waiting for complete signal. But then, you'd probably hold onto the error signals so that the normal values come first, then handle all accumulated error signals at once. That's what `delayErrors = true` argument on many operators do for you. 

So you either collect them all or ignore the excess which is by definition context-free.

**Comment by danielesegato** [comment]
`delayErrors` is useless when your observables are never ending and it's sub-optimal anyway when what you want to do with the other exceptions is ignore them.

say flatMap received 3 values and subscribed to 3 observables: A, B, C
when receiving an error from B, shouldn't it dispose of A and C = no error received there?

from a library perspective you can't use a static method like `RxJavaPlugins.setErrorHandler()` and even from an app seems a bit like an hack.

I totally agree that I'm in the best option to decide with my context. But I really have no way of doing so because on `RxJavaPlugins.setErrorHandler()` I've no context and in my flatmap, where errors actually happens, I can't do anything else other then setting it to `delayErrors` which is simply wrong in some situations.

Unless I'm not aware of something, which might totally be the case :)

**Comment by akarnokd** [comment]
> when receiving an error from B, shouldn't it dispose of A and C = no error received there?

Some sources (mostly blocking IO ones) respond to dispose with crashes. This includes Retrofit 2 which decided to pass along any such crashes. All you can do is to ignore them via the global error handler.
