### ISSUE TITLE
2.1.6 PublishProcessor.debounce() is interrupting previous operation.

### ISSUE THREAD

**Issue by Malachiasz** [ReactiveX/RxJava#6256]
RxJava 2.1.6 in Android.

I have processor which offers a search text which is followed by debounce in order not to do search request each time a character of search phrase changes. I realized it doesn't work, when I type characters faster than BETWEEN_SEARCHES_INTERVAL = 300 millis. What is happening is that OkHttp throws interrupted exception from inside of searchRepository.searchInNetwork() method.

```
tRestFSOperation: java.io.InterruptedIOException: thread interrupted
tRestFSOperation:     at okio.Timeout.throwIfReached(Timeout.java:145)
tRestFSOperation:     at okio.Okio$2.read(Okio.java:137)
```

I guess that debounce is interrupting the thread on which previous emission is running. I think it's unintended behaviour. At least it's not documented.

```
    fun subscribeToSearch() {
        if (disposables.size() == 0) {
            disposables.add(
                searchPublishProcessor
                    .debounce(BETWEEN_SEARCHES_INTERVAL, TimeUnit.MILLISECONDS, Schedulers.io())
                    // .throttleLast(BETWEEN_SEARCHES_INTERVAL, TimeUnit.MILLISECONDS, Schedulers.io())
                    .distinctUntilChanged()
                    .filter { it.searchPhrase.isNotBlank() }
                    .flatMap {
                        searchForPhraseInFolder(it)
                    }
                    .subscribeOn(Schedulers.io())
                    .onErrorReturn { e: Throwable ->
                        Timber.w(e, "Error in search request")
                        SearchState.Builder(searchState)
                            .setState(LoadingState.ERROR)
                            .setException(Unique(e))
                            .build()

                    }
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe({ newSearchState: SearchState? -> publishState(newSearchState!!) },
                        { e: Throwable? ->
                            Timber.e(e, "Error while search")
                            CrashInfo.submitHandledCrash(e, "SearchViewModel.search() broken")
                        }))
        }
    }

    private fun searchForPhraseInFolder(it: SearchQuery): Flowable<SearchState>? {
        return Flowable.fromCallable { searchRepository.searchInNetwork(it.searchPhrase, it.folderResourceId) }
            .map { resources: List<Resource> ->
                SearchState.Builder(searchState)
                    .setResources(resources)
                    .setState(if (resources.isEmpty()) LoadingState.EMPTY else LoadingState.DONE)
                    .build()
            }
            .startWith(
                SearchState.Builder(searchState)
                    .setState(LoadingState.LOADING)
                    .build()
            )
            .subscribeOn(Schedulers.io())
    }
```

**Comment by akarnokd** [comment]
This can happen if the processing of the item after debounce takes too long. You should move the computation to another thread from the debouncer thread to avoid this, for example, by moving the `subscribeOn` next to the api call:

```kotlin
.flatMap {
    searchForPhraseInFolder(it)
       .subscribeOn(Schedulers.io())
}
// .subscribeOn(Schedulers.io())
```

**Comment by Malachiasz** [comment]
Thank you for explanation. What about writing it in java docs of the debounce() method?

**Comment by akarnokd** [comment]
PR welcome.
