### ISSUE TITLE
Map and flatMap operator chaining is not stack-safe

### ISSUE THREAD

**Issue by pakoito** [ReactiveX/RxJava#6322]
### Expected behavior
Chaining large numbers of map and flatMap operators is stack-safe

### Actual behavior
StackOverflow on `ObservableMap.subscribeActual`

### Steps to reproduce
```java
Range.create(0, 5000)
  .toList()
  .fold(Observable.just(0), { observable, x ->
    observable.map { x }
  }).block()
  .shouldBe(5000)
```

Yields a StackOverflow error:

```
    java.lang.StackOverflowError
        at java.lang.String.indexOf(String.java:1503)
        at java.lang.ClassLoader.checkName(ClassLoader.java:871)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:1036)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.reactivex.Observable.subscribe(Observable.java:12088)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12084)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12084)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12084)
        ...
```

### RxJava version
2.2.1

### JVM version (e.g. `java -version`)
1.7 with Kotlin in the project, 1.8 in the system

**Comment by akarnokd** [comment]
This is a known limitation and can't be resolved on our end. Method chaining is essentially eating up the stack. You have to restart the stack by introducing asynchrony for example or do a complete different flow.

**Comment by pakoito** [comment]
Thanks for the fast reply :D
