### ISSUE TITLE
Caused by java.lang.IndexOutOfBoundsException: Index: 1, Size: 0

### ISSUE THREAD

**Issue by tarunkonda123** [ReactiveX/RxJava#6333]
Caused by java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
a XXX.subscribeActual(Unknown Source:259)
at io.reactivex.Observable.subscribe(Unknown Source:14)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(Unknown Source:6)
at io.reactivex.Scheduler$DisposeTask.run(Unknown Source:9)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

**Comment by akarnokd** [comment]
Crucial information is missing, such as what is XXX and line 259 and code demonstrating the problem.

**Comment by tarunkonda123** [comment]
it's my packagename+classname

**Comment by tarunkonda123** [comment]
. Crashed: RxNewThreadScheduler-11
       at io.reactivex.plugins.RxJavaPlugins.initComputationScheduler(Unknown Source:20)
       at io.reactivex.Observable.subscribe(Unknown Source:22)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(Unknown Source:6)
       at io.reactivex.Scheduler$DisposeTask.run(Unknown Source:9)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

--

Fatal Exception: b.b.c.f: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
       at io.reactivex.plugins.RxJavaPlugins.initComputationScheduler(Unknown Source:20)
       at io.reactivex.Observable.subscribe(Unknown Source:22)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(Unknown Source:6)
       at io.reactivex.Scheduler$DisposeTask.run(Unknown Source:9)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by akarnokd** [comment]
> it's my packagename+classname

How do you expect us to help you if you don't provide the necessary details? We can't look into your machine and this very much looks like **you have a logical error in your own code**.

**Comment by coolajitsahu** [comment]
yes

**Comment by ever5390** [comment]
In my case, this error, show you because i was try setear a type object  List<AnyObject>.
Something there:
List<"AnyObjennt"> paramList = new ArrayList<"AnyObject">();
paramList.set(0, element);  // Wrong!!!!! , java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
paramList.add(0, element); Good!!!
