### ISSUE TITLE
NullPointer for at ReplaySubject$SizeBoundReplayBuffer.trim 

### ISSUE THREAD

**Issue by Nokuap** [ReactiveX/RxJava#6336]
Version 2.2.2
So i have ReplaySubject.createWithSize(1)  and when i call onNext sometimes(very rarely) this exception appear for few users.

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.concurrent.atomic.AtomicReference.get()' on a null object reference
       at io.reactivex.subjects.ReplaySubject$SizeBoundReplayBuffer.trim(SourceFile:851)
       at io.reactivex.subjects.ReplaySubject$SizeBoundReplayBuffer.add(SourceFile:864)
       at io.reactivex.subjects.ReplaySubject.onNext(SourceFile:349)
       at com.quantfury.business.repository.InstrumentPriceRepository.onNewInstrumentPrice(SourceFile:228)
       at com.quantfury.business.repository.InstrumentPriceRepository.access$onNewInstrumentPrice(SourceFile:50)
       at com.quantfury.business.repository.InstrumentPriceRepository$restartPrices$1$1.run(SourceFile:215)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:38)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:26)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

**Comment by akarnokd** [comment]
Do not call `onNext` concurrently. http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subjects/ReplaySubject.html
