### ISSUE TITLE
NegativeArraySizeException when onBackpressureBuffer(Integer.MAX_VALUE) used

### ISSUE THREAD

**Issue by geekthanos** [ReactiveX/RxJava#6360]
When I use the following code with RxJava2 version 2.2.4:

               onBackpressureBuffer(Integer.MAX_VALUE,
                        ()->{Logger.error("Buffer has overflowed. " +
                                "This means we are experiencing a data loss event!");});

I get the following error:

va.lang.NegativeArraySizeException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.Flowable.subscribe(Flowable.java:14643)
	at io.reactivex.Flowable.subscribe(Flowable.java:14583)
	at io.reactivex.internal.operators.flowable.FlowableZip$ZipCoordinator.subscribe(FlowableZip.java:126)
	at io.reactivex.internal.operators.flowable.FlowableZip.subscribeActual(FlowableZip.java:79)
	at io.reactivex.Flowable.subscribe(Flowable.java:14636)
	at io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14636)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:14636)
Caused by: java.lang.NegativeArraySizeException: null
	at java.util.concurrent.atomic.AtomicReferenceArray.<init>(AtomicReferenceArray.java:94)
	at io.reactivex.internal.queue.SpscArrayQueue.<init>(SpscArrayQueue.java:51)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.<init>(FlowableOnBackpressureBuffer.java:80)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer.subscribeActual(FlowableOnBackpressureBuffer.java:46)
	at io.reactivex.Flowable.subscribe(Flowable.java:14636)
	at io.reactivex.Flowable.subscribe(Flowable.java:14583)
	at io.reactivex.internal.operators.flowable.FlowableZip$ZipCoordinator.subscribe(FlowableZip.java:126)
	at io.reactivex.internal.operators.flowable.FlowableZip.subscribeActual(FlowableZip.java:79)
	at io.reactivex.Flowable.subscribe(Flowable.java:14636)
	at io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:37)
[error] a.a.OneForOneStrategy - Actually not, but can't throw other exceptions due to RS
java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
	at io.reactivex.Flowable.subscribe(Flowable.java:14645)

**Comment by akarnokd** [comment]
The `onBackpressureBuffer` tries to create a power-of-2 array, which would be `Integer.MAX_VALUE + 1` that overflows to negative. You can't create arrays that (absolute) long in **Java** anyway and the use case shown makes no sense. Do you want to buffer everything or drop some items beyond some capacity?

**Comment by geekthanos** [comment]
@akarnokd Thank you. This was a test to make sure we buffer a lot of data and thought of informing the team. We want to buffer in case of back pressure and not lose data. Would the default onBackpressureBuffer() do that? The documentation doesn't mentioning about dropping beyond capacity but in the code it looks like the capacity is 128 and will drop after that.

**Comment by akarnokd** [comment]
The no-argument `onBackpressureBuffer` buffers an unbounded amount of items and doesn't drop. http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#onBackpressureBuffer--

**Comment by geekthanos** [comment]
But in the code, I see it points to default size which is 128. How is it unbounded?

**Comment by akarnokd** [comment]
Where? An SpscLinkedArrayQueue is effectively unbounded as it can link up any number of arrays as its backing storage. Those arrays require a size ("island size") which is set to the default buffer size.

**Comment by geekthanos** [comment]
ok got it. Thank you.
