### ISSUE TITLE
FlowableConcatMapTest.boundaryFusionDelayError failed with queue full error.

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6409]
The test is deterministic so it should never fail with the prefetch queue full.

Originally appeared in #5852

```
io.reactivex.internal.operators.flowable.FlowableConcatMapTest > boundaryFusionDelayError FAILED
java.lang.AssertionError: Error(s) present: [io.reactivex.exceptions.MissingBackpressureException: Queue is full?!] (latch = 0, values = 1, errors = 1, completions = 0)
at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:189)
at io.reactivex.observers.BaseTestConsumer.assertNoErrors(BaseTestConsumer.java:274)
at io.reactivex.observers.BaseTestConsumer.assertResult(BaseTestConsumer.java:797)
at io.reactivex.internal.operators.flowable.FlowableConcatMapTest.boundaryFusionDelayError(FlowableConcatMapTest.java:105)
Caused by:
io.reactivex.exceptions.MissingBackpressureException: Queue is full?!
```

**Comment by akarnokd** [comment]
This hasn't happened since, not sure how it coult. Closing for now.
