### ISSUE TITLE
Exception in Single.fromCallable not sent to RxJavaPlugins.onError

### ISSUE THREAD

**Issue by runningcode** [ReactiveX/RxJava#6438]
The following code does _not_ propagate an error to the `RxJavaPlugins.onError` handler. The exception is silently swallowed.

```
Single.fromCallable {
  throw RuntimeException("Crash")
}
  .subscribeOn(Schedulers.io())
  .observeOn(Schedulers.computation())
  .subscribe(object : SingleObserver<Any> {
    override fun onSuccess(t: Any) {
    }

    override fun onSubscribe(d: Disposable) {
    }

    override fun onError(e: Throwable) {
      throw e as RuntimeException
    }
})
Thread.sleep(5000);
```

But the following code _does_ propagate the error to the `RxJavaPlugins.onError` handler. Here we are using `Observable.fromCallable` instead of `Single.fromCallable`.
```
Observable.fromCallable {
  throw RuntimeException("Crash")
}
  .subscribeOn(Schedulers.io())
  .observeOn(Schedulers.computation())
  .subscribe(object : Observer<Any> {
     override fun onNext(t: Any) {
     }

     override fun onComplete() {
     }

     override fun onSubscribe(d: Disposable) {
     }

     override fun onError(e: Throwable) {
       throw e as RuntimeException
     }
})
```

The following code also _does_ propagate the error to the `RxJavaPlugins.onError` handler. Notice the removal of the `.observeOn(Schedulers.computation())` in comparison to the first code sample.
```
Single.fromCallable {
  throw RuntimeException("Crash")
}
  .subscribeOn(Schedulers.io())
  .subscribe(object : SingleObserver<Any> {
    override fun onSuccess(t: Any) {
    }

    override fun onSubscribe(d: Disposable) {
    }

    override fun onError(e: Throwable) {
      throw e as RuntimeException
    }
})
```

Using RxJava 2.2.7.

Is this expected behavior? Could it be related to the use of a `Disposables.empty()` inside `Single.fromCallable` instead of `DeferredScalarDisposable`?

**Comment by akarnokd** [comment]
Please read the [Getting started](https://github.com/ReactiveX/RxJava#simple-background-computation).

**Comment by runningcode** [comment]
I can't find it in getting started, why is it expected that an error from a `Single.fromCallable` is swallowed and not sent anywhere but an error from `Observable.fromCallable` is sent to `RxJavaPlugins.onError`?

**Comment by akarnokd** [comment]
Your code exits before it can print anything. It is clearly marked in the example on the line: `Thread.sleep(2000);`.

**Comment by runningcode** [comment]
This is a simplified version of what we have running in our production android app. The app continues to run for hours after the exception is thrown and silently swallowed.

Either way, why is the behavior different for a `Single` vs an `Observable` though?

**Comment by runningcode** [comment]
I added a `Thread.sleep(5000)` to the repro case.

**Comment by akarnokd** [comment]
If you implement `SingleObserver` or any observer, you are not allowed to throw from `onSuccess` or `onError`.

**Comment by akarnokd** [comment]
http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/SingleObserver.html:

> The implementations of the onXXX methods should avoid throwing runtime exceptions other than the following cases:
>
> - If the argument is null, the methods can throw a NullPointerException. Note though that RxJava prevents nulls to enter into the flow and thus there is generally no need to check for nulls in flows assembled from standard sources and intermediate operators.
> - If there is a fatal error (such as VirtualMachineError).

**Comment by runningcode** [comment]
Sorry to keep this going. If we throw a `NullPointerException` or `OutOfMemoryError` inside the `onError` method of the `SingleObserver`, the exception is still silently swallowed.

This example _does not_ crash the app but I would expect it to do so.
```
Single.fromCallable {
  throw RuntimeException("Crash")
}
  .subscribeOn(Schedulers.io())
  .observeOn(Schedulers.computation())
  .subscribe(object : SingleObserver<Any> {
  override fun onSuccess(t: Any) {
  }

  override fun onSubscribe(d: Disposable) {
  }

  override fun onError(e: Throwable) {
    throw OutOfMemoryError()
  }
})
Thread.sleep(5000)
```

**Comment by akarnokd** [comment]
Violating the protocol leads to undefined behavior. **Do not crash `onError`.**. Why don't you use the callback-based subscribe() method? It lets your code crash and will report it to the global error handler.

**Comment by runningcode** [comment]
Thanks for the response. I understand that we're not supposed to crash onError and this is a violation of protocol, but in unexpected cases like `VirtualMachineException` or `OutOfMemoryErrors`, an exception in onError should crash the app and not be swallowed.
Is this what you mean by the callback based subscribe method? This also does not crash the app:
```
Single.fromCallable {
  throw RuntimeException("Crash")
}
  .subscribeOn(Schedulers.io())
  .observeOn(Schedulers.computation())
  .subscribe({}, { throw OutOfMemoryError() })
Thread.sleep(5000)
```

Anyways, I totally understand that RxJava is being used wrong here. I'm trying to guard against unexpected cases like `VirtualMachineError`s and `OutOfMemoryError`s being silently swallowed.
My question the following: is it expected that an `OutOfMemoryError` in a `Single` is silently swallowed, but an `OutOfMemoryError` inside an observable is not silently swallowed?

**Comment by akarnokd** [comment]
If you don't trust your code, use try-catch. We can't protect against all types of failures and fatal exceptions can't be usually handled without most likely crashing even further.

Also the consumer version prints a hefty exception list for me, so it does call the **default** global handler that forwards it to the uncaught exception handler:


```
io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:49)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
  ComposedException 1 :
	java.lang.RuntimeException
		at hu.akarnokd.rxjava2.OnErrorCrash.lambda$0(OnErrorCrash.java:12)
		at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
		at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
  ComposedException 2 :
	java.lang.RuntimeException: java.lang.RuntimeException
		at hu.akarnokd.rxjava2.OnErrorCrash.lambda$2(OnErrorCrash.java:15)
		at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
		at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
		at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
		at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.RuntimeException
		at hu.akarnokd.rxjava2.OnErrorCrash.lambda$0(OnErrorCrash.java:12)
		at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
		at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)

Exception in thread "RxComputationThreadPool-1" io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:49)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
  ComposedException 1 :
	java.lang.RuntimeException
		at hu.akarnokd.rxjava2.OnErrorCrash.lambda$0(OnErrorCrash.java:12)
		at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
		at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
  ComposedException 2 :
	java.lang.RuntimeException: java.lang.RuntimeException
		at hu.akarnokd.rxjava2.OnErrorCrash.lambda$2(OnErrorCrash.java:15)
		at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
		at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
		at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
		at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.RuntimeException
		at hu.akarnokd.rxjava2.OnErrorCrash.lambda$0(OnErrorCrash.java:12)
		at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
		at io.reactivex.Single.subscribe(Single.java:3603)
		at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
		at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by runningcode** [comment]
Thanks for you patience in explaining this issue to me. I completely understand that we should use try-catch for code that we don't trust.

However my question this this: I'm curious what the difference between `Single` and `Observable` is in how we should handle errors. Why is it expected that `Single` might swallow certain exceptions which `Observable` sends to the `UncaughtExceptionHandler`?


What do you mean by the consumer version prints out an exception? For me it was silently swallowed, unless we are talking about a different consumer version.
Is this the code you ran? 
https://github.com/runningcode/rx-single-error/blob/master/src/main/java/Main.java#L15

**Comment by akarnokd** [comment]
Fatal exceptions are not routed to the global error handler: https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/observers/ConsumerSingleObserver.java#L64
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/exceptions/Exceptions.java#L66

> I'm curious what the difference between Single and Observable

Single uses one-shot scheduling and Observable uses worker scheduling. Workers have different safeguards due to historical reasons and due to certain former users.
