### ISSUE TITLE
`debounce` results in `InterruptedException` being thrown

### ISSUE THREAD

**Issue by derolf** [ReactiveX/RxJava#6457]
rxjava-2.2.8:

The following sample simulates a blocking operation that takes some time. Note that I also get that exception with code that waits for locks (without the artificial Thread.sleep).

```Kotlin
package studies

import io.reactivex.Flowable
import java.util.concurrent.TimeUnit

fun main() {
  Flowable.interval(100, TimeUnit.MILLISECONDS)
    .debounce(50, TimeUnit.MILLISECONDS)
    .map {
      Thread.sleep(1000)
      it
    }
    .blockingForEach { println(it) }
}
```

The result is:

```
0
Exception in thread "main" java.lang.RuntimeException: java.lang.InterruptedException: sleep interrupted
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.operators.flowable.BlockingFlowableIterable$BlockingFlowableIterator.hasNext(BlockingFlowableIterable.java:83)
	at io.reactivex.Flowable.blockingForEach(Flowable.java:5682)
	at studies.BackpressureKt.main(backpressure.kt:17)
	at studies.BackpressureKt.main(backpressure.kt)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at studies.BackpressureKt$main$1.apply(backpressure.kt:14)
	at studies.BackpressureKt$main$1.apply(backpressure.kt)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
	at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
	at io.reactivex.internal.operators.flowable.FlowableDebounceTimed$DebounceTimedSubscriber.emit(FlowableDebounceTimed.java:156)
	at io.reactivex.internal.operators.flowable.FlowableDebounceTimed$DebounceEmitter.emit(FlowableDebounceTimed.java:191)
	at io.reactivex.internal.operators.flowable.FlowableDebounceTimed$DebounceEmitter.run(FlowableDebounceTimed.java:186)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Here is the stack I get when putting a breakpoint into `Thread.interrupt()`:

```
interrupt:915, Thread (java.lang)
cancel:174, FutureTask (java.util.concurrent)
cancel:279, ScheduledThreadPoolExecutor$ScheduledFutureTask (java.util.concurrent)
dispose:117, ScheduledRunnable (io.reactivex.internal.schedulers)
dispose:124, DisposableHelper (io.reactivex.internal.disposables)
dispose:197, FlowableDebounceTimed$DebounceEmitter (io.reactivex.internal.operators.flowable)
onNext:93, FlowableDebounceTimed$DebounceTimedSubscriber (io.reactivex.internal.operators.flowable)
run:93, FlowableInterval$IntervalSubscriber (io.reactivex.internal.operators.flowable)
run:38, ScheduledDirectPeriodicTask (io.reactivex.internal.schedulers)
call:511, Executors$RunnableAdapter (java.util.concurrent)
runAndReset$$$capture:308, FutureTask (java.util.concurrent)
runAndReset:-1, FutureTask (java.util.concurrent)
 - Async stack trace
<init>:151, FutureTask (java.util.concurrent)
<init>:219, ScheduledThreadPoolExecutor$ScheduledFutureTask (java.util.concurrent)
scheduleAtFixedRate:570, ScheduledThreadPoolExecutor (java.util.concurrent)
schedulePeriodicallyDirect:110, NewThreadWorker (io.reactivex.internal.schedulers)
schedulePeriodicallyDirect:165, ComputationScheduler (io.reactivex.internal.schedulers)
subscribeActual:55, FlowableInterval (io.reactivex.internal.operators.flowable)
subscribe:14827, Flowable (io.reactivex)
subscribeActual:45, FlowableDebounceTimed (io.reactivex.internal.operators.flowable)
subscribe:14827, Flowable (io.reactivex)
subscribeActual:37, FlowableMap (io.reactivex.internal.operators.flowable)
subscribe:14827, Flowable (io.reactivex)
iterator:42, BlockingFlowableIterable (io.reactivex.internal.operators.flowable)
blockingForEach:5681, Flowable (io.reactivex)
main:14, BackpressureKt (studies)
main:-1, BackpressureKt (studies)
```

**Comment by akarnokd** [comment]
Please do not cross post issues from StackOverflow. https://stackoverflow.com/questions/55606278/using-onbackpressurelatest-to-drop-intermediate-messages-in-blocking-flowable

**Comment by derolf** [comment]
So, does that mean that the behavior to throw an exception is intended? It is not mentioned anywhere in the documentation.
