### ISSUE TITLE
Flowable publish not working (2.2.10)

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJava#6552]
The order that the flowables are concat'ed inside the publish function affects the output. I'm not blocked on this because I worked around the issue by using `tags.cache()`.

Test code to reproduce the issue.

```java
package io.reactivex;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.UUID;
import java.util.stream.Collectors;

import org.junit.jupiter.api.Test;

class FlowablePublishTest {
    static class TagEntry {
        private final String key;
        private final String value;
        private final Set<UUID> ids;

        public TagEntry(String key, String value, Set<UUID> ids) {
            this.key = key;
            this.value = value;
            this.ids = ids;
        }

        public String getKey() {
            return key;
        }

        public Set<UUID> getIds() {
            return ids;
        }

        @Override
        public int hashCode() {
            return Objects.hash(key, value, ids);
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj)
                return true;
            if (obj == null)
                return false;
            if (getClass() != obj.getClass())
                return false;
            TagEntry that = (TagEntry) obj;
            return Objects.equals(this.key, that.key) &&//
                    Objects.equals(this.value, that.value) &&//
                    Objects.equals(this.ids, that.ids);
        }

        @Override
        public String toString() {
            return key + "=" + value + ": " + ids;
        }
    }

    @Test
    void test() {
        UUID a = UUID.randomUUID();
        UUID b = UUID.randomUUID();

        HashSet<TagEntry> expected = new HashSet<>();
        expected.add(new TagEntry("hello", null, Collections.singleton(b)));
        expected.add(new TagEntry("hello", "world", Collections.singleton(a)));

        HashSet<TagEntry> actual = addUntagged(Flowable.just(new TagEntry("hello", "world", Collections.singleton(a))),
                Flowable.just(a, b)).collectInto(new HashSet<TagEntry>(), HashSet::add)
                    .blockingGet();

        assertEquals(expected, actual);
    }

    private Flowable<TagEntry> addUntagged(Flowable<TagEntry> tags, Flowable<UUID> allIds) {
        Single<List<UUID>> allRootIds = allIds.toList()
            .cache();

        return tags.publish(pubTags -> {
            Single<Map<String, Set<UUID>>> taggedRootIdsByDim = pubTags.collect(TreeMap::new, (map, entry) -> {
                map.computeIfAbsent(entry.getKey(), (k) -> new TreeSet<>())
                    .addAll(entry.getIds());
            });

            Flowable<TagEntry> untags = taggedRootIdsByDim.zipWith(allRootIds, this::generateUntags)
                .flattenAsFlowable(x -> x);

            return pubTags.concatWith(untags); // only return pubTags
            // return untags.concatWith(pubTags); // only return untags
        });
    }

    private List<TagEntry> generateUntags(Map<String, Set<UUID>> taggedRootIdsByDim, List<UUID> allRootIds) {
        return taggedRootIdsByDim.entrySet()
            .stream()
            .map((entry) -> {
                // substract the two sets to find root ids that are don't have this tag
                TreeSet<UUID> untagged = new TreeSet<>(allRootIds);
                untagged.removeAll(entry.getValue());

                return new TagEntry(entry.getKey(), null, untagged);
            })
            .collect(Collectors.toList());
    }
}
```

The results that I saw when I ran it.

with line 92 commented out
```
org.opentest4j.AssertionFailedError:
expected: <[hello=world: [9dc92d08-9e43-49a7-b30c-dde3060226c0], hello=null: [2aaa21e8-61de-4cec-b8ad-1e964cc62418]]>
but was: <[hello=world: [9dc92d08-9e43-49a7-b30c-dde3060226c0]]>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at io.reactivex.FlowablePublishTest.test(FlowablePublishTest.java:76)
```

with line 93 commented out
```
org.opentest4j.AssertionFailedError:
expected: <[hello=null: [ca32468d-48d6-4ad5-bd61-33f7ccb59088], hello=world: [0ec2a954-ad6f-4d4b-b342-633f3c809ca8]]>
but was: <[hello=null: [ca32468d-48d6-4ad5-bd61-33f7ccb59088]]>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at io.reactivex.FlowablePublishTest.test(FlowablePublishTest.java:76)
```

**Comment by akarnokd** [comment]
I don't think there is a bug in the operator but a misunderstanding.

With `return pubTags.concatWith(untags)`, the shared source `pubTags` is fully consumed in its entirety, then `concatWith` switches to `untags` which now tries to work with a completed `pubTags`.

With `return untags.concatWith(pubTags)`, the `untags` consumes the shared `pubTags` to completion and `concatWith` switches to a now terminated `pubTags`.

Looks like you wanted to have the original sequence and a processed variants of it, but `concatWith` won't let you do both at the same time. `replay(Function)` would cache all items for whatever the second reprocessing would be.

**Comment by abersnaze** [comment]
I thought the point of ‘publish’ was to allow multiple subscriptions to the same`Flowable`.

> selector - a function that can use the multicasted source sequence as many times as needed, without causing multiple subscriptions to the source sequence. Subscribers to the given source will receive all notifications of the source from the time of the subscription forward.

**Comment by akarnokd** [comment]
> Subscribers to the given source will receive all notifications of the source from **the time of the subscription forward.**

This is the key phrase. `concatWith` will trigger a new subscription when the shared source has ended, thus it won't receive anything other than the terminal event. The operator is analogous how `PublishProcessor`/`PublishSubject` multicasts items where late consumers will not see previous items.
