### ISSUE TITLE
Using Emmitter#tryOnError can't avoid UndeliverableException 

### ISSUE THREAD

**Issue by chxchen** [ReactiveX/RxJava#6557]
Relative issue: 
1. https://github.com/ReactiveX/RxJava/issues/5477
2. https://github.com/ReactiveX/RxJava/issues/6213

Version: 2.2.3/2.2.4

Description:
If dispose the stream in a thread that different with the "error" produced in, even using tryOnError can't avoid crash by undeliverableException. This happens rarely but it exist.
"tryOnError" is using in case Callback-Fail frequently, so as to use "retry" and other operation in My project. This thread-safe problem like a bomb.

I use this sample recurrent this problem:
```
class RxJavaTryOnError {

    public static void main(String[] args) {
        for (int i = 0; i < 1000; i++) {
            Single.create(emitter -> new RxJavaTryOnError().setListener(throwable -> {
                System.out.println(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(new Date(System.currentTimeMillis())) + " " + Thread.currentThread().getId()+
                        " fetch error ");
                emitter.tryOnError(throwable);
            }))
                    .timeout(1000_000,TimeUnit.NANOSECONDS)
                    .doOnError(throwable -> System.out.println(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(new Date(System.currentTimeMillis())) +" " + Thread.currentThread().getId() + " fetch err." + throwable))
                    .onErrorResumeNext(Single.just(1))
                    .subscribe();
            try {
                TimeUnit.MILLISECONDS.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

        try {
            TimeUnit.SECONDS.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    public void setListener(Consumer<Throwable> throwableConsumer) {
        Schedulers.io().scheduleDirect(() -> throwableConsumer.accept(new Throwable("throw" + System.currentTimeMillis())), 1000_000,
                TimeUnit.NANOSECONDS);
    }
}
```

And system.out :
```
2019-07-04 14:40:06.930 14 fetch error 
2019-07-04 14:40:06.931 19 fetch err.java.util.concurrent.TimeoutException: The source did not signal an event for 1000000 nanoseconds and has been terminated.
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.Throwable: throw1562222406930
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.onError(SingleTimeout.java:152)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
	at RxJavaTryOnError.lambda$null$0(RxJavaTryOnError.java:22)
	at RxJavaTryOnError.lambda$setListener$3(RxJavaTryOnError.java:51)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Throwable: throw1562222406930
	... 10 more
Exception in thread "RxCachedThreadScheduler-1" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.Throwable: throw1562222406930
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.onError(SingleTimeout.java:152)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
	at RxJavaTryOnError.lambda$null$0(RxJavaTryOnError.java:22)
	at RxJavaTryOnError.lambda$setListener$3(RxJavaTryOnError.java:51)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Throwable: throw1562222406930
	... 10 more
```

As other issue said, "use RxJavaPlugin#setErrorHandle" is a way, but I don't think that is a best way.
Any other way to avoid this?

**Comment by akarnokd** [comment]
With that many async stages, the cancellation may reach an operator the same time the error reaches it, thus you have an undeliverable error situation. The only reliable way to avoid crashing on Android is to set the global error handler.

**Comment by chxchen** [comment]
> reliable

**Comment by chxchen** [comment]
> With that many async stages, the cancellation may reach an operator the same time the error reaches it, thus you have an undeliverable error situation. The only reliable way to avoid crashing on Android is to set the global error handler.

This means if "tryOnError" is used, global error handler should be set? 
How can I distinguish this UndeliverableException in global handler produced by "tryOnError" but not other case?

**Comment by akarnokd** [comment]
`tryOnError` is not a guaranteed solution. It was introduced so that when a cancellation interrupts a blocking operation in `create`, there won't be a guaranteed undeliverable exception right there.

You can throw custom exceptions you and/or check `getCause()` if you get an undeliverable one.

**Comment by chxchen** [comment]
Thank you!  I find "io.reactivex.plugins.RxJavaPlugins#isBug" method, this method returns false, the error will be wrapped with UndeliverableException.
The case `tryOnError` failed by thread-safe will produce UndeliverableException.
And other case, "forget error handler","a unexpect error" and without error consumer will produce OnErrorNotImplementedException.
So, maybe do this will cover this problem, and make no  effect to other case.
```
RxJavaPlugins.setErrorHandler(throwable -> {
            if (throwable instanceof UndeliverableException) {
                System.err.println(throwable);
            }
        });
```
