### ISSUE TITLE
The thread in RxIoScheduler is always running after SocketTimeout by using Rxjava1.3.8 and Retrofit

### ISSUE THREAD

**Issue by XiaoCaiZn** [ReactiveX/RxJava#6578]
The thread in RxIoScheduler is always running after SocketTimeout by using Rxjava1.3.8 and Retrofit

this is how i uesd RxJava, and the timeout when create OkHttpClient was 10s.
public static void setSubscribe(Observable observable, Observer observer) {
observable.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
.subscribe(observer);
}

this is Stacktrace, this exception was be catched in rx.Observer's onError, but The thread in RxIoScheduler is always running.

java.net.SocketTimeoutException: timeout
at okhttp3.internal.framed.FramedStream$StreamTimeout.newTimeoutException(FramedStream.java:600)
at okhttp3.internal.framed.FramedStream$StreamTimeout.exitAndThrowIfTimedOut(FramedStream.java:608)
at okhttp3.internal.framed.FramedStream.getResponseHeaders(FramedStream.java:142)
at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)
at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
at okhttp3.z.a(RealCall.java:244)
at okhttp3.z$a.proceed(RealCall.java:201)

Need help, thanks.

**Comment by akarnokd** [comment]
RxJava 1 is no longer supported or maintained. Also I don't understand what you mean by the thread is always running.

**Comment by XiaoCaiZn** [comment]
@akarnokd 
Thanks. It's means the thread in Rxjava's RxIoScheduler is still running after sockettimeout. And my app is using CPU for a long time because this thread is running. unless you kill app. 
And I'm not sure this bug will be ok by using Rxjava3.
This is system trace.
![IMG_20190718143547](https://user-images.githubusercontent.com/53027655/61434814-9223f100-a969-11e9-949a-8b367ea76904.png)

**Comment by akarnokd** [comment]
What is it running? Could you trigger a stacktrace on it? The IO schedulers may stay idle for a minute before they stop.

**Comment by XiaoCaiZn** [comment]
@akarnokd There is my code. Could you get something useful.  And I'm not sure what is it running. I'm not very clear about retrofit,  I  just use retrofit to get data from net. 
According to the system trace, i'm very sure the IO schedulers is not idle, but is running.

	public static Retrofit getRetrofit(Context context, String url) {
        String cacheDir = context.getCacheDir().getAbsolutePath();
        Cache cache = new Cache(new File(cacheDir), CACHE_SIZE);
        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .addInterceptor(getInterceptor(context))
                .connectTimeout(10, TimeUnit.SECONDS)
                .readTimeout(10, TimeUnit.SECONDS)
                .writeTimeout(10, TimeUnit.SECONDS)
                .cache(cache)
                .build();

        Gson gson = new GsonBuilder().setLenient().create();
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(url)
                .addConverterFactory(GsonConverterFactory.create(gson))
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .client(okHttpClient)
                .build();
        return retrofit;
    }
    private interface NewsInterface {
        @POST("list")
        Observable<NewsResult> getNewsList(@Body RequestBody body);
    }

    protected static void requestNewsList(Context context, NewsRequest request, Observer<NewsResult> observer) {
        NetWorks.setSubscribe(getNewsApi(context).getNewsList(createRequestBody(request)), observer);
    }
	 public static <T> void setSubscribe(Observable<T> observable, Observer<T> observer) {
        observable.subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(observer);
    }
	
    NewsNetHelper.requestNewsList(mContext, getNewsRequest(tab), new Observer<NewsResult>() {
        @Override
        public void onCompleted() {
        }
        @Override
        public void onError(Throwable e) {
             // there catch SocketTimeoutException
        }
        @Override
        public void onNext(NewsResult result) {
        }
    });
 java.net.SocketTimeoutException: timeout
 	at okhttp3.internal.framed.FramedStream$StreamTimeout.newTimeoutException(FramedStream.java:600)
 	at okhttp3.internal.framed.FramedStream$StreamTimeout.exitAndThrowIfTimedOut(FramedStream.java:608)
 	at okhttp3.internal.framed.FramedStream.getResponseHeaders(FramedStream.java:142)
 	at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)
 	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
 	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
 	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
 	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
 	at okhttp3.z.a(RealCall.java:244)
	at okhttp3.z$a.proceed(RealCall.java:201)

**Comment by akarnokd** [comment]
The listing shows nothing particular to me. If the IO scheduler thread is running, you should be able to get the stacktrace of what it is running via debugging tools I presume, or at worst, [Thread.getAllStacktraces()](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#getAllStackTraces()) upon a button click or something.

**Comment by XiaoCaiZn** [comment]
Thanks.  I'm not known about what is it running in thread because this bug is very very hard to make it happen again. So now i may only can add some log about thread's stacktrace. And what can i do before this bug happen again.
