### ISSUE TITLE
TestSubscriber  worked only in blocking mode?

### ISSUE THREAD

**Issue by deripas** [ReactiveX/RxJava#6613]
Hi!
I'm using version `2.2.10` rxjava.
I want testing custom `Publisher` with using `TestSubscriber`:
```java
     Flowable.fromPublisher(publisher)
                .test()
                .assertSubscribed()
                .assertValue("test")
                .assertNoErrors()
                .assertComplete();
```

Where simple `Publisher` (blocing mode):
```java
        Publisher<String> publisher = subscriber -> subscriber.onSubscribe(new Subscription() {
            @SneakyThrows
            @Override
            public void request(long n) {
                log.info("request({})", n);
                // async task
                CompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {
                    sleep(100);
                    log.info("call");
                    return "test";
                }, executor);
                
                // blocking mode
                String result = future.get();
                log.info("onNext");
                subscriber.onNext(result);
                subscriber.onComplete();
            }

            @Override
            public void cancel() {}
        });
```
Worked fine, output:
```
[main] INFO exampleTest - request(9223372036854775807)
[pool-2-thread-1] INFO exampleTest  - call
[main] INFO exampleTest  - onNext
```

But with *non-blocking*  mode I have *problem*:
```java
        Publisher<String> publisher = subscriber -> subscriber.onSubscribe(new Subscription() {
            @SneakyThrows
            @Override
            public void request(long n) {
                log.info("request({})", n);
                // async task
                CompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {
                    sleep(100);
                    log.info("call");
                    return "test";
                }, executor);
                
                // async mode
                future.whenComplete((result, throwable) -> {
                    log.info("onNext");
                    subscriber.onNext(result);
                    subscriber.onComplete();
                });
            }

            @Override
            public void cancel() {}
        });
```
*NOT* worked!:
```
[main] INFO exampleTest - request(9223372036854775807)


java.lang.AssertionError: expected: test (class: String) but was: [] (latch = 1, values = 0, errors = 0, completions = 0)
Expected :test (class: String) 
Actual   :[] (latch = 1, values = 0, errors = 0, completions = 0)
<Click to see difference>


	at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:189)
	at io.reactivex.observers.BaseTestConsumer.assertValue(BaseTestConsumer.java:354)
	...
```

PS: For comparison, both of these options work fine on StepVerifier (Reactor Test)
```java
        StepVerifier.create(publisher)
                .expectSubscription()
                .expectNext("test")
                .verifyComplete();
```

**Comment by akarnokd** [comment]
You have to [await the termination](https://github.com/ReactiveX/RxJava/blob/228f6d9f8b717e7f46bdc5b5505d576b5e592375/src/test/java/io/reactivex/internal/operators/flowable/FlowableIntervalRangeTest.java#L35) of the source before asserting most properties about since you have code running asynchronously to the test thread. `StepVerifier` has been designed differently and it will implicitly block for the source to complete.

Also it is not recommended you implement `Publisher`s that way, especially when trying to bridge to an async source. Use [`fromFuture`](https://github.com/akarnokd/RxJavaJdk8Interop/tree/master#completionstage-to-rxjava) of the extensions project instead.
