### ISSUE TITLE
Crash when returning share()d Observable inside flatMap 

### ISSUE THREAD

**Issue by makaroffandrey** [ReactiveX/RxJava#6646]
Thanks for using RxJava but before you post an issue, please consider the following points:

  - [X] Please include the library version number, including the minor and patch version, in the issue text. In addition, if you'd include the major version in the title (such as `3.x`) that would be great.
Library version: `io.reactivex.rxjava2:rxjava:2.2.12`

  - [X] If you think you found a bug, please include a code sample that reproduces the problem. Dumping a stacktrace is usually not enough for us.

This code will crash:
```Java
import io.reactivex.Observable;
import io.reactivex.schedulers.Schedulers;
import io.reactivex.subjects.PublishSubject;

public class Main {

    public static void main(String[] args) throws InterruptedException {
        Observable<String> failingDelayedOperation = Observable.<String>fromCallable(() -> {
            Thread.sleep(1000);
            throw new Exception();
        }).subscribeOn(Schedulers.newThread()).share();
        PublishSubject<Integer> subject = PublishSubject.create();
        subject.flatMap((string) -> failingDelayedOperation).subscribe(
                (i) -> System.out.println("onNext with " + i),
                (error) -> System.out.println("OnError with " + error));
        subject.onNext(1);
        subject.onNext(2);
        Thread.sleep(2000);
    }
}

```

<details><summary>Stacktrace</summary>

```
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.Exception
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.onError(ObservableRefCount.java:236)
	at io.reactivex.internal.operators.observable.ObservablePublishAlt$PublishConnection.onError(ObservablePublishAlt.java:187)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:47)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception
	at Main.lambda$main$0(Main.java:10)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
	... 11 more
Exception in thread "RxNewThreadScheduler-1" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.Exception
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.onError(ObservableRefCount.java:236)
	at io.reactivex.internal.operators.observable.ObservablePublishAlt$PublishConnection.onError(ObservablePublishAlt.java:187)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:47)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception
	at Main.lambda$main$0(Main.java:10)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
	... 11 more
```
</details>

You can substitute a `PublishSubject` with any `Observable` that emits more than one item fast enough.
It does not crash if there is only one call to `subject.onNext` or if there is a sufficient delay between first end second call to `subject.onNext`

  - [X] RxJava has more than 150 operators, we recommend searching the [javadoc](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/Observable.html) for keywords of what you try to accomplish.

  - [X] If you have a question/issue about a library/technology built on top of RxJava (such as Retrofit, RxNetty, etc.), please consider asking a question on StackOverflow first (then maybe on their issue list).

N/A

  - [X] Questions like "how do I X with RxJava" are generally better suited for StackOverflow (where it may already have an answer).

N/A

  - [X] Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

Bugs and Feedback section of [`README.md`](https://github.com/ReactiveX/RxJava/blob/85e1c4ca4979c63fb840d0ae7ea672f30394d0f0/README.md#bugs-and-feedback) instructs to create an issue, therefore posting it here.

**Comment by akarnokd** [comment]
The exception message explains the reason and what to read: 

> The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

That specific `flatMap` allows only one exception signal, even if the exact same exception instance is coming through multiple inner sources. You can install a global error handler or use `delayErrors = true` to wait for all possible terminal signals.

**Comment by makaroffandrey** [comment]
I could not use `delayErrors = true` because in that case I would receive the errors only when `subject` terminates and in my use case I did not want it to terminate, but I wanted my subscription to `flatMap` to terminate in case of an error. I also did not want to use global error handler for the sake of one `Observable` in an environment that always has several active subscriptions at any given time.

So for future reference, here is what I ended up doing:
```Java
Observable<Notification<String>> failingDelayedOperation = Observable.<String>fromCallable(() -> {
    Thread.sleep(1000);
    throw new Exception();
}).subscribeOn(Schedulers.newThread()).materialize().share();
PublishSubject<Integer> subject = PublishSubject.create();
subject.flatMap((string) -> failingDelayedOperation)
        .takeUntil(notification -> !notification.isOnNext())
        .dematerialize(notification -> notification)
        .subscribe(
                (i) -> System.out.println("onNext with " + i),
                (error) -> System.out.println("OnError with " + error));
subject.onNext(1);
subject.onNext(2);
Thread.sleep(2000);
```
