### ISSUE TITLE
3.x: Observable.groupBy test failures

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#6663]
Two tests fail randomly on CI:

This is probably failing because some non-atomicity bug in determining a group has been abandoned?
```
io.reactivex.rxjava3.internal.operators.observable.ObservableGroupByTest > firstGroupsCompleteAndParentSlowToThenEmitFinalGroupsWhichThenSubscribesOnAndDelaysAndThenCompletes FAILED
    java.lang.AssertionError: expected:<6> but was:<5>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableGroupByTest.firstGroupsCompleteAndParentSlowToThenEmitFinalGroupsWhichThenSubscribesOnAndDelaysAndThenCompletes(ObservableGroupByTest.java:765)
```

and this fails because dispose still doesn't get propagated to upstream.

```
io.reactivex.rxjava3.internal.operators.observable.ObservableGroupByTest > cancelOverFlatmapRace()
      at assertFalse("Round " + i, ps.hasObservers());
```

I can't make these tests fail on my machine at all so the GroupBy logic has to be rechecked. The `Flowable` variants have not failed (yet).

**Comment by akarnokd** [comment]
I've run the changes with the build matrix and no failures popped up. Closing for now.
