### ISSUE TITLE
2.X: Maybe#empty test

### ISSUE THREAD

**Issue by CedrickFlocon** [ReactiveX/RxJava#6952]
I have trouble unit testing a Maybe#empty

````
Maybe.empty<String>().test().assertEmpty()
````

> java.lang.AssertionError: Completed! (latch = 0, values = 0, errors = 0, completions = 1)
	at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:189)
	at io.reactivex.observers.BaseTestConsumer.assertNotComplete(BaseTestConsumer.java:258)
	at io.reactivex.observers.BaseTestConsumer.assertEmpty(BaseTestConsumer.java:879)

is it desired ?

**Comment by akarnokd** [comment]
As the [JavaDocs](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/observers/BaseTestConsumer.html#assertEmpty--) states, `assertEmpty` verifies no items or terminal event have been received, but `Maybe.empty()` completes. Use `assertResult` with no items.

Btw, there is generally no reason to test RxJava's own first party constructs.
