### ISSUE TITLE
[3.x] Nested resources created with 'using' operator are getting closed out of order

### ISSUE THREAD

**Issue by 404-** [ReactiveX/RxJava#6957]
`io.reactivex.rxjava3 / rxjava / 3.0.2`

Observed: nested resources created via `Single.using` are being closed out of order.
Expected: nested resources created via `Single.using` should be closed in order, i.e. inner resources should be closed before outer resources are closed.

Reproducible with the following code (Kotlin):

```kotlin
package com.example

import com.example.RxSessionUtils.connect
import com.example.RxSessionUtils.rxQuery
import io.reactivex.rxjava3.core.Flowable
import io.reactivex.rxjava3.core.Single
import io.reactivex.rxjava3.functions.BiFunction
import io.reactivex.rxjava3.functions.Supplier
import java.time.Instant
import java.time.LocalTime
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicReference

fun main() {
    val connector = { Thread.sleep(500) ; EmulatedSession(listOf("a", "b", "c")) as Session }
    val results = connect(connector).flatMapPublisher { session -> session.rxQuery("...") }

    val deadline = Instant.now().plusSeconds(4)

    results
        .takeWhile { Instant.now() < deadline } // <-- not reproducible without this call
        .map { el -> say("Processing result: $el") }
        .ignoreElements()
        .blockingAwait()
}

fun tname() = Thread.currentThread().name
fun say(msg: String) = println("[${tname()}] ${LocalTime.now()} $msg")

interface Results {
    fun next(): String?
    fun close()
}

interface Session {
    fun query(select: String): Results
    fun close()
}

object RxSessionUtils {
    fun connect(f: () -> Session): Single<Session> = Single.using(
        {
            say("acquire(session)...")
            val session = f()
            say("...acquire(session)")
            session
        },
        { session -> Single.just(session) },
        { session ->
            say("release(session)...")
            session.close()
            say("...release(session)")
        },
        false // really? how is this not the default?
    )

    private fun Session.safelyQuery(select: String): Single<Results> = Single.using(
        {
            say("acquire(results)...")
            val results = query(select)
            say("...acquire(results)")
            results
        },
        { results -> Single.just(results) },
        { results ->
            say("release(results)...")
            results.close()
            say("...release(results)")
        }
        false // really? how is this not the default?
    )

    fun Session.rxQuery(select: String): Flowable<IndexedValue<String>> =
        safelyQuery(select).flatMapPublisher { initial ->
            Flowable.generate<IndexedValue<String>, IndexedValue<Results>>(
                Supplier { IndexedValue(0, initial) },
                BiFunction { (idx, results), emitter ->
                    when(val next = results.next()) {
                        null -> emitter.onComplete()
                        else -> emitter.onNext( IndexedValue(idx, next) )
                    }
                    IndexedValue(idx + 1, results)
                }
            )
        }
}

class EmulatedResults(private val els: Iterator<String>) : Results {
    private val closed = AtomicBoolean(false)

    override fun next(): String? = synchronized(this) {
        if (closed.get())
            error("results closed")

        if (els.hasNext()) {
            Thread.sleep(2_000) // simulate I/O
            els.next()
        } else null
    }

    override fun close() {
        Thread.sleep(500) // simulate I/O
        say("EmulatedResults#close()")
        closed.set(true)
    }

    fun isClosed(): Boolean = closed.get()
}

class EmulatedSession(private val results: List<String>) : Session {
    private var curr: AtomicReference<EmulatedResults?> = AtomicReference(null)

    override fun query(select: String): Results = synchronized(this) {
        Thread.sleep(500) // simulate I/O
        EmulatedResults(results.iterator()).also(curr::set)
    }

    override fun close() {
        Thread.sleep(500) // simulate I/O
        say("EmulatedSession#close()")
        synchronized(this) {
            curr.get()?.let { curr -> if (!curr.isClosed()) error("open results!") }
            curr.set(null)
        }
    }
}
```

Sample output:

```
[main] 13:51:57.562 acquire(session)...
[main] 13:51:58.127 ...acquire(session)
[main] 13:51:58.132 acquire(results)...
[main] 13:51:58.638 ...acquire(results)
[main] 13:52:00.649 Processing result: IndexedValue(index=0, value=a)
[main] 13:52:02.653 release(session)...
[main] 13:52:03.157 EmulatedSession#close()
[main] 13:52:03.163 release(results)...
java.lang.IllegalStateException: open results!
	at com.example.EmulatedSession.close(RxJavaEvaluation.kt:122)
	at com.example.RxSessionUtils$connect$3.accept(RxJavaEvaluation.kt:51)
	at com.example.RxSessionUtils$connect$3.accept(RxJavaEvaluation.kt:40)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.disposeResource(SingleUsing.java:192)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.dispose(SingleUsing.java:116)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.cancel(SingleFlatMapPublisher.java:127)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableTakeWhile$TakeWhileSubscriber.onNext(FlowableTakeWhile.java:74)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onNext(SingleFlatMapPublisher.java:107)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onNext(SingleFlatMapPublisher.java:107)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.onNext(FlowableGenerate.java:173)
	at com.example.RxSessionUtils$rxQuery$1$2.apply(RxJavaEvaluation.kt:80)
	at com.example.RxSessionUtils$rxQuery$1$2.apply(RxJavaEvaluation.kt:40)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:108)
	at io.reactivex.rxjava3.internal.subscriptions.SubscriptionHelper.deferredSetOnce(SubscriptionHelper.java:202)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSubscribe(SingleFlatMapPublisher.java:102)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:51)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15696)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSuccess(SingleFlatMapPublisher.java:96)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.onSuccess(SingleUsing.java:154)
	at io.reactivex.rxjava3.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing.subscribeActual(SingleUsing.java:83)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher.subscribeActual(SingleFlatMapPublisher.java:59)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15696)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSuccess(SingleFlatMapPublisher.java:96)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.onSuccess(SingleUsing.java:154)
	at io.reactivex.rxjava3.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing.subscribeActual(SingleUsing.java:83)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher.subscribeActual(SingleFlatMapPublisher.java:59)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableTakeWhile.subscribeActual(FlowableTakeWhile.java:33)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableIgnoreElementsCompletable.subscribeActual(FlowableIgnoreElementsCompletable.java:34)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1460)
	at com.example.RxJavaEvaluationKt.main(RxJavaEvaluation.kt:24)
	at com.example.RxJavaEvaluationKt.main(RxJavaEvaluation.kt)
Exception in thread "main" java.lang.IllegalStateException: open results!
	at com.example.EmulatedSession.close(RxJavaEvaluation.kt:122)
	at com.example.RxSessionUtils$connect$3.accept(RxJavaEvaluation.kt:51)
	at com.example.RxSessionUtils$connect$3.accept(RxJavaEvaluation.kt:40)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.disposeResource(SingleUsing.java:192)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.dispose(SingleUsing.java:116)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.cancel(SingleFlatMapPublisher.java:127)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableTakeWhile$TakeWhileSubscriber.onNext(FlowableTakeWhile.java:74)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onNext(SingleFlatMapPublisher.java:107)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onNext(SingleFlatMapPublisher.java:107)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.onNext(FlowableGenerate.java:173)
	at com.example.RxSessionUtils$rxQuery$1$2.apply(RxJavaEvaluation.kt:80)
	at com.example.RxSessionUtils$rxQuery$1$2.apply(RxJavaEvaluation.kt:40)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:108)
	at io.reactivex.rxjava3.internal.subscriptions.SubscriptionHelper.deferredSetOnce(SubscriptionHelper.java:202)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSubscribe(SingleFlatMapPublisher.java:102)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:51)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15696)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSuccess(SingleFlatMapPublisher.java:96)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.onSuccess(SingleUsing.java:154)
	at io.reactivex.rxjava3.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing.subscribeActual(SingleUsing.java:83)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher.subscribeActual(SingleFlatMapPublisher.java:59)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15696)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSuccess(SingleFlatMapPublisher.java:96)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing$UsingSingleObserver.onSuccess(SingleUsing.java:154)
	at io.reactivex.rxjava3.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleUsing.subscribeActual(SingleUsing.java:83)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher.subscribeActual(SingleFlatMapPublisher.java:59)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableTakeWhile.subscribeActual(FlowableTakeWhile.java:33)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableIgnoreElementsCompletable.subscribeActual(FlowableIgnoreElementsCompletable.java:34)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1460)
	at com.example.RxJavaEvaluationKt.main(RxJavaEvaluation.kt:24)
	at com.example.RxJavaEvaluationKt.main(RxJavaEvaluation.kt)
[main] 13:52:03.665 EmulatedResults#close()
[main] 13:52:03.666 ...release(results)
```

**Comment by akarnokd** [comment]
Please provide a smaller reproducing example and please indicate what happens and what is your expectation.

**Comment by 404-** [comment]
I added observed/expected behavior. The example above is isolated, self-contained and as small as I could get it to be...

**Comment by akarnokd** [comment]
Try setting the inner `using` to close eagerly.

**Comment by 404-** [comment]
That makes it worse. Not only are the resources still being released in the wrong order, but making the inner `using` close eagerly also prevents any results from being read, because the inner resource gets released immediately after being acquired.

**Comment by akarnokd** [comment]
Okay. One of the problems I see here is that by using `Single.just`, the resource can escape its `using` scope. So in order to bind the resource to its usage scope, which is determined by a terminal event or cancellation by `using`, you'll have to nest the code using those resources into the mapper function argument.

**Comment by 404-** [comment]
It sounds like you're saying that the intended way to leverage the `using` operator  is to pass the code which depends on the resource as the second argument of `using` (called `sourceSupplier`)? That is, the instance of `Single<T>` returned from `Single.using` represents a "used up resource"? Isn't that a violation of the [spec]?

Concretely, here are two scenarios:

```
interface Resource {}

fun acquire(): Resource { /*...*/ }
fun release(resource: Resource) { /*...*/ }

// scenario 1
Single.using(
  { acquire() },
  { resource ->
       Single.fromCallable {
         /* the 'resource' *MUST* be used here and only here? */ 
       }
  },
  { resource -> release(resource) },
  false
)

// scenario 2
val x = Single.using(
  { acquire() },
  { resource -> Single.just(resource) },
  { resource -> release(resource) },
  false
)

x.flatMap { resource -> /* using the resource here is forbidden? because it has escaped its scope? */ }
```

My impression is that `Scenario 2` is exactly what the [spec] outlines as the intended usage.

[spec]: http://reactivex.io/documentation/operators/using.html

**Comment by akarnokd** [comment]
> represents a "used up resource"
No. The linked document appears to be cropped as the `Observable` indicated should be the one returned by the `observableFactory`. 

To illustrate the problem, for example, the following Java code has the same issue:

```java
Connection useResource() {
   try(var conn = createConnection()) {
      return conn;
   } // this closes conn
}

useResource().query(""); // query would find a closed connection
```

Thus the correct usage is Scenario 1.

> spec

Also it is preferred to use [RxJava's own JavaDocs](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Single.html#using-io.reactivex.rxjava3.functions.Supplier-io.reactivex.rxjava3.functions.Function-io.reactivex.rxjava3.functions.Consumer-).

**Comment by 404-** [comment]
Maybe I'm spoiled/biased by my experience with other libraries, where the whole point of "lifting" resources into "containers" is to avoid any nesting and allow end-users to leverage Monadic constructs.

Anyway, what I'm really looking for is usually referred to as a `bracket` operation. I thought that in ReactiveX that translated to the `using` operator, which (I thought) in RxJava meant setting `eager` to false. Is there such an operator in RxJava?

Here are examples of this construct from other libraries:
  * Cats [Resource] (or, more generally [Bracket typeclass])
  * Akka-Streams: [Source.unfoldResource]
  * Monix: [Observable.resource]
  * FS2: [fs2.Stream.bracket]
  * ZIO: [ZIO#bracket]



[Source.unfoldResource]: https://doc.akka.io/docs/akka/current/stream/operators/Source/unfoldResource.html
[fs2.Stream.bracket]: https://fs2.io/guide.html#resource-acquisition
[Observable.resource]: https://monix.io/api/3.0/monix/reactive/Observable$.html#resource[A](acquire:monix.eval.Task[A])(release:A=%3Emonix.eval.Task[Unit]):monix.reactive.Observable[A]
[ZIO#bracket]: https://zio.dev/docs/overview/overview_handling_resources
[Resource]: https://typelevel.org/cats-effect/tutorial/tutorial.html#acquiring-and-releasing-resources
[Bracket typeclass]: https://typelevel.org/cats-effect/typeclasses/bracket.html

**Comment by akarnokd** [comment]
> avoid any nesting

- The Akka-Streams example does use nesting by requiring a callback for `read`.
- I don't know Monix in detail but I assume its sequences have to call some dispose when they complete to clean up resources. This is forbidden in Reactive Streams and the only way to detect if the downstream has completed is to intercept it basically, which requires nesting.
- The same might be true for FS2 requiring the call of close on a sequence and thus knowing when the downstream usage ends.

So all in all, you can't avoid nesting in RxJava.

**Comment by 404-** [comment]
Just to clarify, the nesting I'm referring to is that of the "containers" - `Single` in the case of RxJava. So, in Akka Streams the `read` callback represents an interaction with a "live" resource and the return type indicates a single element being returned (not the totality of resource interaction, just _one_ single interaction such as getting the "next" element from a stream), meaning the `read` function is invoked continuously until it returns a instance of `None`. In, RxJava that second argument (`sourceSupplier`) seems to represent the entire sequence of interactions with the resource (_not_ just a single operation, but all of them).

**Comment by 404-** [comment]
For posterity, going back to my original example, updating the function signatures and using `Flowable.using` instead of `Single.using` in `RxSessionUtils` (see snippet below) causes the resources to be closed in the correct order (thereby fixing the issue):

```
object RxSessionUtils {
  fun <T> connect(mk: () -> Session, use: (Session) -> Flowable<T>): Flowable<T> = Flowable.using( ... )

  private fun <T> Session.safelyQuery(select: String, use: (Results) -> Flowable<T>): Flowable<T> = Flowable.using( ... )

}
```

**Comment by 404-** [comment]
Since the initial issue was addressed and any confusion clarified, I'm closing the ticket. Thank you for your help, @akarnokd
