### ISSUE TITLE
Error building `rxjava`on ppc64le platform

### ISSUE THREAD

**Issue by sarveshtamba** [ReactiveX/RxJava#6965]
Trying to build rxjava v2.2.7 and v3.0.2 (REPOSITORY="https://github.com/ReactiveX/RxJava.git") on ppc64le platform, however facing the following errors:-
```
io.reactivex.internal.operators.observable.ObservableRefCountTest > publishNoLeak FAILED
    java.lang.AssertionError: 7,780,912 -> 107,596,880
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.reactivex.internal.operators.observable.ObservableRefCountTest.publishNoLeak(ObservableRefCountTest.java:726)

io.reactivex.validators.JavadocWording > singleDocRefersToSingleTypes FAILED
    java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileReader.<init>(FileReader.java:72)
        at io.reactivex.validators.JavadocForAnnotations.readFile(JavadocForAnnotations.java:56)
        at io.reactivex.validators.BaseTypeParser.parse(BaseTypeParser.java:53)
        at io.reactivex.validators.JavadocWording.singleDocRefersToSingleTypes(JavadocWording.java:427)

io.reactivex.validators.JavadocWording > flowableDocRefersToFlowableTypes FAILED
    java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileReader.<init>(FileReader.java:72)
        at io.reactivex.validators.JavadocForAnnotations.readFile(JavadocForAnnotations.java:56)
        at io.reactivex.validators.BaseTypeParser.parse(BaseTypeParser.java:53)
        at io.reactivex.validators.JavadocWording.flowableDocRefersToFlowableTypes(JavadocWording.java:217)

io.reactivex.validators.JavadocWording > completableDocRefersToCompletableTypes FAILED
    java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileReader.<init>(FileReader.java:72)
        at io.reactivex.validators.JavadocForAnnotations.readFile(JavadocForAnnotations.java:56)
        at io.reactivex.validators.BaseTypeParser.parse(BaseTypeParser.java:53)
        at io.reactivex.validators.JavadocWording.completableDocRefersToCompletableTypes(JavadocWording.java:601)

io.reactivex.validators.JavadocWording > observableDocRefersToObservableTypes FAILED
    java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileReader.<init>(FileReader.java:72)
        at io.reactivex.validators.JavadocForAnnotations.readFile(JavadocForAnnotations.java:56)
        at io.reactivex.validators.BaseTypeParser.parse(BaseTypeParser.java:53)
        at io.reactivex.validators.JavadocWording.observableDocRefersToObservableTypes(JavadocWording.java:326)

io.reactivex.validators.JavadocWording > maybeDocRefersToMaybeTypes FAILED
    java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileReader.<init>(FileReader.java:72)
        at io.reactivex.validators.JavadocForAnnotations.readFile(JavadocForAnnotations.java:56)
        at io.reactivex.validators.BaseTypeParser.parse(BaseTypeParser.java:53)
        at io.reactivex.validators.JavadocWording.maybeDocRefersToMaybeTypes(JavadocWording.java:41)

io.reactivex.validators.MaybeNo2Dot0Since > noSince20InMaybe FAILED
    java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileReader.<init>(FileReader.java:72)
        at io.reactivex.validators.MaybeNo2Dot0Since.noSince20InMaybe(MaybeNo2Dot0Since.java:77)

10869 tests completed, 7 failed, 235 skipped
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/sar/rxjava-2.2.7/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 28s
19 actionable tasks: 16 executed, 3 up-to-date
```
Any inputs will be highly appreciated.

**Comment by akarnokd** [comment]
v2.2.7 is a pretty old build at this point. Try building the most recent version. Also try checking out into a directory named `RxJava`.

**Comment by sarveshtamba** [comment]
@akarnokd Tried checking out into a directory named RxJava. Now I am facing only 1 error as below:-
```
io.reactivex.internal.operators.observable.ObservableRefCountTest > publishNoLeak FAILED
    java.lang.AssertionError: 7,732,440 -> 107,856,800
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.reactivex.internal.operators.observable.ObservableRefCountTest.publishNoLeak(ObservableRefCountTest.java:726)
```

**Comment by akarnokd** [comment]
It tends to be a flaky GC-related test issue. It has been [fixed](https://github.com/ReactiveX/RxJava/blob/b3ad0752de398f4536bb88a7b1c77b0b9fbecb87/src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableRefCountTest.java#L723-L744) via [this helper](https://github.com/ReactiveX/RxJava/blob/b3ad0752de398f4536bb88a7b1c77b0b9fbecb87/src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableRefCountTest.java#L723-L744) in 3.x but not backported.

**Comment by sarveshtamba** [comment]
@akarnokd Any way we can backport this?

**Comment by akarnokd** [comment]
Since it doesn't fail on our build systems, it's not a high priority for us. You are welcome to post a PR.
