### ISSUE TITLE
Sometimes RxJava onError doesn’t catch Exception

### ISSUE THREAD

**Issue by TikTak123** [ReactiveX/RxJava#6971]
I have list of news. When user click one of the news, I show full news info. In that moment I send to backend request in header with alias of this news. Sometimes my app crashes. But this request have onError handler. I can't reproduce this error. But I see this error on Crashlytics.

I know there are Non ASCII symbols. Can't show all header. I have a lot of news and one of them can have Non ASCII symbols. I need to sure this error will be handle in onError and App won't crash.

Here is log error

```
Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0x430 at 12 in Params value: {"itemId":"акция"}
       at okhttp3.Headers$Companion.checkValue(Headers.java:434)
       at okhttp3.Headers$Companion.access$checkValue(Headers.java:346)
       at okhttp3.Headers$Builder.add(Headers.java:245)
       at okhttp3.Request$Builder.addHeader(Request.java:210)
       at com.example.NetworkModule.lambda$provideAuthOkHttpClient$1(NetworkModule.java:112)
       at com.example.-$$Lambda$NetworkModule$0kozbr2vzEMUs4EGFjGRxf09B6g.intercept(-.java)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:87)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:219)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:87)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:194)
       at okhttp3.RealCall$AsyncCall.run(RealCall.java:138)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```
Here is sample code.

```
mNetworkHelper.sendGrafanaMetrics()
                    .compose(RxUtil.applySchedulers())
                    .subscribe(response -> {
                    }, this::silentError);
```

**Comment by akarnokd** [comment]
> Please avoid cross-posting questions on StackOverflow, this issue list, the Gitter room or the mailing list.

https://stackoverflow.com/questions/61542954/sometimes-rxjava-onerror-doesn-t-catch-exception
