### ISSUE TITLE
Keep alive subscription to the Observable after exception occurred in the Consumer

### ISSUE THREAD

**Issue by felipeska** [ReactiveX/RxJava#7022]
_RxJava version: 2.2.19_

This code:

```java
import io.reactivex.Observable;
import io.reactivex.functions.Consumer;

public class Main {

  public static void main(String[] args) {
    Observable.range(0, 6).subscribe(new Consumer<Integer>() {
      public void accept(Integer integer) throws Exception {
        if (integer != 3) {
          System.out.println("Integer: " + integer);
        } else {
          someOperation();
        }
      }
    }, new Consumer<Throwable>() {
      public void accept(Throwable throwable) throws Exception {
        System.out.println("Error!");
        throwable.printStackTrace();
      }
    });
  }

  static void someOperation() {
    throw new IllegalStateException("error in consumer");
  }
}
```

This is the log:

```java
Integer: 0
Integer: 1
Integer: 2
Error!
java.lang.IllegalStateException: error in consumer
	at com.rx.test.Main$1.accept(Main.java:14)
	at com.rx.test.Main$1.accept(Main.java:9)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.onNext(ObservableRetryPredicate.java:69)
	at io.reactivex.internal.operators.observable.ObservableRange$RangeDisposable.run(ObservableRange.java:64)
	at io.reactivex.internal.operators.observable.ObservableRange.subscribeActual(ObservableRange.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.subscribeNext(ObservableRetryPredicate.java:112)
	at io.reactivex.internal.operators.observable.ObservableRetryPredicate.subscribeActual(ObservableRetryPredicate.java:41)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.rx.test.Main.main(Main.java:9)

Process finished with exit code 0

```

- Is it possible to keep the observable subscription alive after the exception?

- Is there any way to continue consuming the stream?

**Comment by akarnokd** [comment]
> Is it possible to keep the observable subscription alive after the exception?

No. Exceptions terminate the flow.

> Is there any way to continue consuming the stream?

Yes, do not crash into RxJava. Wrap your call into try-catch.
