### ISSUE TITLE
UndeliverableException

### ISSUE THREAD

**Issue by wangshouxue** [ReactiveX/RxJava#7065]
io.reactivex.exceptions.UndeliverableException: java.io.InterruptedIOException: timeout
    at l.a.a1.a.Y(TbsSdkJava:4)
    at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.disposeAll(TbsSdkJava:9)
    at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.cancel(TbsSdkJava:4)
    at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(TbsSdkJava:5)
    at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.cancel(TbsSdkJava:1)
    at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.cancel(TbsSdkJava:3)
    at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(TbsSdkJava:5)
    at io.reactivex.internal.operators.flowable.FlowableZip$ZipSubscriber.cancel(TbsSdkJava:1)
    at io.reactivex.internal.operators.flowable.FlowableZip$ZipCoordinator.cancelAll(TbsSdkJava:2)
    at io.reactivex.internal.operators.flowable.FlowableZip$ZipCoordinator.drain(TbsSdkJava:9)
    at io.reactivex.internal.operators.flowable.FlowableZip$ZipCoordinator.error(TbsSdkJava:3)
    at io.reactivex.internal.operators.flowable.FlowableZip$ZipSubscriber.onError(TbsSdkJava:1)
    at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runBackfused(TbsSdkJava:5)
    at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(TbsSdkJava:2)
    at l.a.q0.c.b$b.run(TbsSdkJava:1)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8347)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
Caused by: java.io.InterruptedIOException: timeout
    at q.o0.j.j.r(TbsSdkJava:3)
    at q.o0.j.j.j(TbsSdkJava:12)
    at q.o0.j.j.l(TbsSdkJava:4)
    at q.g0.c(TbsSdkJava:18)
    at q.g0.T(TbsSdkJava:8)
    at u.l.T(TbsSdkJava:8)
    at u.x.a.c.B5(TbsSdkJava:5)
    at l.a.z.subscribe(TbsSdkJava:4)
    at u.x.a.a.B5(TbsSdkJava:1)
    at l.a.z.subscribe(TbsSdkJava:4)
    at l.a.w0.e.b.h0.c6(TbsSdkJava:1)
    at l.a.j.b6(TbsSdkJava:4)
    at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.c6(TbsSdkJava:1)
    at l.a.j.b6(TbsSdkJava:4)
    at io.reactivex.internal.operators.flowable.FlowableFlatMap.c6(TbsSdkJava:2)
    at l.a.j.b6(TbsSdkJava:4)
    at l.a.j.subscribe(TbsSdkJava:2)
    at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(TbsSdkJava:4)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(TbsSdkJava:2)
    at io.reactivex.internal.schedulers.ScheduledRunnable.call(TbsSdkJava:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)
Caused by: java.net.SocketException: Socket closed
    at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
    at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
    at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
    at r.o$b.W0(TbsSdkJava:4)
    at r.a$b.W0(TbsSdkJava:2)
    at r.u.e0(TbsSdkJava:4)
    at r.u.j0(TbsSdkJava:1)
    at q.o0.l.a.A(TbsSdkJava:1)
    at q.o0.l.a.e(TbsSdkJava:3)
    at q.o0.j.d.m(TbsSdkJava:1)
    at q.o0.k.b.intercept(TbsSdkJava:27)
    at q.o0.k.g.j(TbsSdkJava:9)
    at q.o0.j.b.intercept(TbsSdkJava:6)
    at q.o0.k.g.j(TbsSdkJava:9)
    at q.o0.k.g.f(TbsSdkJava:1)
    at q.o0.h.a.intercept(TbsSdkJava:22)
    at q.o0.k.g.j(TbsSdkJava:9)
    at q.o0.k.g.f(TbsSdkJava:1)
    at q.o0.k.a.intercept(TbsSdkJava:22)
    at q.o0.k.g.j(TbsSdkJava:9)
    at q.o0.k.j.intercept(TbsSdkJava:6)
    at q.o0.k.g.j(TbsSdkJava:9)
    at q.o0.k.g.f(TbsSdkJava:1)
    at com.hualongxiang.base.retrofit.QfInterceptor.addLog(TbsSdkJava:11)
    at com.hualongxiang.base.retrofit.QfInterceptor.intercept(TbsSdkJava:10)
    at q.o0.k.g.j(TbsSdkJava:9)
    at q.o0.k.g.f(TbsSdkJava:1)
    at q.g0.c(TbsSdkJava:13)
    ... 21 more

**Comment by akarnokd** [comment]
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

**Comment by wangshouxue** [comment]
RxJavaPlugins.setErrorHandler(new Consumer<Throwable>() {
            @Override
            public void accept(Throwable throwable) throws Exception {
                throwable.printStackTrace();
            }
        });
项目里这样写的ErrorHandler
