### ISSUE TITLE
ObservableSwitchMap crashes with NullPointerException

### ISSUE THREAD

**Issue by xinneph** [ReactiveX/RxJava#7074]
I'm using RxJava3 in version 3.0.6 in one of my projects.
The sample code
```import io.reactivex.rxjava3.core.Observable
import io.reactivex.rxjava3.subjects.BehaviorSubject

private val sampleJson = "\"isMessagingEnabled\": true}"
private val overrideConfiguration = BehaviorSubject.create<Boolean>().apply { onNext(false) }

fun main() {
    val configurationFetcher = ConfigurationFetcher()
    val configurationLoader = ConfigurationLoader(configurationFetcher)
    configurationLoader.configuration.subscribe()
}

class ConfigurationLoader(private val configurationFetcher: ConfigurationFetcher) {
    val configuration: Observable<String> = overrideConfiguration
        .switchMap { override ->
            if (override) {
                Observable.just(sampleJson)
            } else {
                configurationFetcher.configurationData
            }
        }
}

class ConfigurationFetcher {
    val configurationData: Observable<String> = Observable.fromPublisher { subscriber ->
        val listener = object : RemoteCallback {
            override fun onSuccess(json: String) {
                subscriber.onNext(json)
                subscriber.onComplete()
            }
        }
        RequestCallable().request(listener)
    }
}

interface RemoteCallback {
    fun onSuccess(json: String)
}

class RequestCallable {
    fun request(callback: RemoteCallback) {
        callback.onSuccess(sampleJson)
    }
}
```
crashes for me with stacktrace
```
Exception in thread "main" java.lang.NullPointerException
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchMap$SwitchMapInnerObserver.onNext(ObservableSwitchMap.java:353)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at ConfigurationFetcher$configurationData$1$listener$1.onSuccess(ObservableSwitchMapDemo.kt:28)
	at RequestCallable.request(ObservableSwitchMapDemo.kt:42)
	at ConfigurationFetcher$configurationData$1.subscribe(ObservableSwitchMapDemo.kt:32)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)
	at io.reactivex.rxjava3.internal.util.NotificationLite.accept(NotificationLite.java:246)
	at io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:507)
	at io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:468)
	at io.reactivex.rxjava3.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:224)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchMap.subscribeActual(ObservableSwitchMap.java:51)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13085)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13000)
	at ObservableSwitchMapDemoKt.main(ObservableSwitchMapDemo.kt:10)
	at ObservableSwitchMapDemoKt.main(ObservableSwitchMapDemo.kt)
```
Could you help me understand what the issue is?

**Comment by akarnokd** [comment]
The problem is in `Observable.fromPublisher`. The method is there to convert a Reactive Streams conformant `Publisher` implementation to an `Observable`, which you instead tried to use as a basic value emitter and violating the underlying protocol:

http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#fromPublisher-org.reactivestreams.Publisher-

> The Publisher must follow the Reactive-Streams specification. Violating the specification may result in undefined behavior.
> If possible, use create(ObservableOnSubscribe) to create a source-like Observable instead.
> Note that even though Publisher appears to be a functional interface, it is not recommended to implement it through a lambda as the specification requires state management that is not achievable with a stateless lambda.

**Comment by xinneph** [comment]
Thank you @akarnokd!
