### ISSUE TITLE
onErrorReturn[Item] not working as expected in 3.0.8 when error is thrown in `flatMap`

### ISSUE THREAD

**Issue by dnmolchanov** [ReactiveX/RxJava#7130]
**Deviation:**
Behavior deviates from previous version and is not covered in [What's-different-in-3.0](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0)
When using `io.reactivex.rxjava2:rxjava:2.2.20` (and substituting appropriate imports), the following test passes.

<hr>

**Minimal reproducible code (the gist of this issue)**
`MyClass.kt:`
```kotlin
package com.molchanov.android.sandbox

import io.reactivex.rxjava3.core.Observable

class MyClass {
    fun myFunction(): Observable<Boolean> = Observable
        .just(true)
        .flatMap<Boolean> { throw UnknownError("TestError") }
        .onErrorReturn { false }
}
```
`MyClassTest.kt:`
```kotlin
package com.molchanov.android.sandbox

import org.junit.Test

class MyClassTest {
    private val testable: MyClass = MyClass()

    @Test
    fun `should return false with no errors`() {
        testable.myFunction()
            .test()
            .assertNoErrors()
            .assertValue(false)
    }
}
```

**Expected result:**
Test passes.

**Actual result:**
Test fails with the following stack trace:
```
java.lang.UnknownError: TestError

	at com.molchanov.android.sandbox.MyClass$myFunction$1.apply(MyClass.kt:8)
	at com.molchanov.android.sandbox.MyClass$myFunction$1.apply(MyClass.kt:5)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableOnErrorReturn.subscribeActual(ObservableOnErrorReturn.java:31)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
	at io.reactivex.rxjava3.core.Observable.test(Observable.java:16457)
	at com.molchanov.android.sandbox.MyClassTest.should return false with no errors(MyClassTest.kt:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)


Process finished with exit code 255
```

On a related note, `doOnError` also does not get called in this case.

**Comment by akarnokd** [comment]
UnknownError is a VirtualMachineError and is considered fatal, therefore it doesn't propagate through onError. The 2.x behavior is most likely a bug or oversight.

**Comment by dnmolchanov** [comment]
Thanks @akarnokd
Changing the error (to say NullPointerException) changes the behavior to the desired.
