### ISSUE TITLE
2.1.9 version - java.lang.ArrayIndexOutOfBoundsException in RxJavaPlugins.java

### ISSUE THREAD

**Issue by JayasreePattabiraman** [ReactiveX/RxJava#7180]
Process: com.trimble.ag.precisioniq.g12.tnl, PID: 1822
b.a.c.f: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at b.a.g.a.a(RxJavaPlugins.java:366)
at b.a.h.a(Observable.java:11201)
at b.c.d.a.runscreen.ui.c.a(xxxx.java:36)
at c.a.d.h(xxxx.java:124)
at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:436)
at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:394)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
at androidx.fragment.app.Fragment.performStart(Fragment.java:2637)

**Comment by akarnokd** [comment]
Looks like you have a custom Observable implementation that fails at subscription time with `ArrayIndexOutOfBoundsException`.
