### ISSUE TITLE
FlowableConcatMapSchedulerTest > mapperDelayError2ScheduledLong failed

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#7200]
```
io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMapSchedulerTest > mapperDelayError2ScheduledLong FAILED
    java.lang.AssertionError: Not completed (latch = 1, values = 1, errors = 0, completions = 0, timeout!, disposed!)
        at io.reactivex.rxjava3.observers.BaseTestConsumer.fail(BaseTestConsumer.java:125)
        at io.reactivex.rxjava3.observers.BaseTestConsumer.assertComplete(BaseTestConsumer.java:178)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMapSchedulerTest.mapperDelayError2ScheduledLong(FlowableConcatMapSchedulerTest.java:1093)
```

**Comment by akarnokd** [comment]
Haven't seent his ever since.
