### ISSUE TITLE
Unable to find root cause of crashlog  from firebase related to Rxjava 3.

### ISSUE THREAD

**Issue by preeti16k8** [ReactiveX/RxJava#7228]
**Below is crash log. could someone help me in finding the root cause?**

   rxkotlinversion = '3.0.1'
    rxJavaVersion = '1.1.4'
    rxJavaVersionUpdated = '3.0.7'
    rxAndroidVersionUpdated = '3.0.0'
    rxAndroidVersion = '1.2.0'

            rxkotlin           : "io.reactivex.rxjava3:rxkotlin:${rxkotlinversion}",
            rxJava             : "io.reactivex:rxjava:${rxJavaVersion}",
            rxJavaUpdated      :  "io.reactivex.rxjava3:rxjava:${rxJavaVersionUpdated}",
            rxAndroid          : "io.reactivex:rxandroid:${rxAndroidVersion}",
            rxAndroidUpdated   :  "io.reactivex.rxjava3:rxandroid:${rxAndroidVersionUpdated}"

Fatal Exception: q2.b.a.d.a: 2 exceptions occurred. 
       at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:80)
       at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by akarnokd** [comment]
There is not much information in this log. You have a lambda-based `subscribe()` method whose `onNext` handler crashes, then the `onError` handler crashes too, either because it is missing or for some other reason.

**Comment by preeti16k8** [comment]
@akarnokd  
Other than above below is also in log.
 Caused by q2.b.a.d.a$a: Multiple exceptions (2)
|-- java.lang.NullPointerException: null
    at j.a.a.r0.d.l5(CashFragment.kt:1)
|-- java.lang.NullPointerException: null
    at j.a.a.r0.d.l5(CashFragment.kt:1)

**Comment by akarnokd** [comment]
You have to deobfuscate your code and find out what `j.a.a.r0.d.l5` is, then see what could be `null` that shouldn't.

**Comment by akarnokd** [comment]
https://stackoverflow.com/questions/67016293/how-to-resolve-rxjava-exception-below-is-log-from-firebase-crashanalytics
