### ISSUE TITLE
UnicastSubjectTest > fusedNoConcurrentCleanDueToCancel FAILED

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#7308]
```
io.reactivex.rxjava3.subjects.UnicastSubjectTest > fusedNoConcurrentCleanDueToCancel FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 5 minutes
        at io.reactivex.rxjava3.subjects.UnicastSubject.drainFused(UnicastSubject.java:416)
        at io.reactivex.rxjava3.subjects.UnicastSubject.drain(UnicastSubject.java:464)
        at io.reactivex.rxjava3.subjects.UnicastSubject.onNext(UnicastSubject.java:319)
        at io.reactivex.rxjava3.subjects.UnicastSubjectTest.fusedNoConcurrentCleanDueToCancel(UnicastSubjectTest.java:481)
```

**Comment by akarnokd** [comment]
Closing as not seen this ever since.
