### ISSUE TITLE
NPE if upstream is null

### ISSUE THREAD

**Issue by DarwinsBuddy** [ReactiveX/RxJava#7364]
https://github.com/ReactiveX/RxJava/blob/223667b37dcd5e33b41d45bc8482c5eabeac8235/src/main/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapCompletable.java#L158

That line causes a NullPointerException, in cases of `upstream = null`.

Steps to reproduce:

1. Take an empty ReadStream
```
var rs = ReadStream.newInstance(FlowableHelper.toReadStream(Flowable.of()))
```
2. Get it's flowable and call `concatMap` on it 
```
rs.toFlowable().concatMap(x -> ...).subscribe(...)
```
3. observe
```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Cannot invoke "org.reactivestreams.Subscription.cancel()" because "this.upstream" is null
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:117)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:97)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onNext(ObservableOnErrorNext.java:64)
	at io.vertx.rxjava3.impl.ObservableReadStream$Subscription.lambda$set$2(ObservableReadStream.java:61)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:169)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:134)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:111)
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:105)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:56)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "org.reactivestreams.Subscription.cancel()" because "this.upstream" is null
	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapCompletable$ConcatMapCompletableObserver.drain(FlowableConcatMapCompletable.java:158)
	at io.reactivex.rxjava3.internal.operators.mixed.ConcatMapXMainSubscriber.onComplete(ConcatMapXMainSubscriber.java:121)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onComplete(FlowableDoOnEach.java:135)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
	at io.vertx.rxjava3.impl.FlowableReadStream.lambda$subscribeActual$0(FlowableReadStream.java:76)
```

**Comment by akarnokd** [comment]
That line can only fail if the main source to the `concatMapX` operator violates the Reactive Streams contract and doesn't call `onSubscribe`.

To verify this, place a `doOnSubscribe()` between `toFlowable()` and `concatMap()` and look out for the (lack of) invocation.

Looking at the source code [FlowableReadStream.java](https://github.com/vert-x3/vertx-rx/blob/master/rx-java3-gen/src/main/java/io/vertx/rxjava3/impl/FlowableReadStream.java#L74-L86), it is suspicious that the `onSubscribe` call is at the very end while callbacks on the stream are setup prior to that, which seem to be triggerable early.
