### ISSUE TITLE
[version 2.2.19] Sometimes I got a stuck while calling dispose()

### ISSUE THREAD

**Issue by surprisen85** [ReactiveX/RxJava#7450]
Hello,

Underlying is the stack trace while it gets stuck. Sometimes, it does not disposed like below. I think there's a deadlock. FYI, those disposables' dispose() is called only at one thread.

  | group="main" sCount=0 ucsCount=0 flags=0 obj=0x12cc0000 self=0xb400006fbad97890
  | sysTid=4090 nice=0 cgrp=foreground sched=0/0 handle=0x6e2f2adcb0
  | state=R schedstat=( 2004042016584 5476972973 35378 ) utm=200322 stm=82 core=4 HZ=100
  | stack=0x6e2f1aa000-0x6e2f1ac000 stackSize=1039KB
  | held mutexes= "mutator lock"(shared held)
  at io.reactivex.internal.queue.SpscLinkedArrayQueue.clear(SpscLinkedArrayQueue.java:186)
  at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.dispose(ObservableObserveOn.java:149)
  at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
  at io.reactivex.internal.observers.LambdaObserver.dispose(LambdaObserver.java:102)
  at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:240)
  at io.reactivex.disposables.CompositeDisposable.clear(CompositeDisposable.java:206)

Looks similar to the previous issue.
https://github.com/ReactiveX/RxJava/issues/6689

**Comment by akarnokd** [comment]
Hi. Issue #6689 has been fixed a long time ago. Looks like you have a queue corruption which may happen if you invoke `onNext` on a `PublishSubject` from multiple threads without using `toSerialized` for example.

**Comment by surprisen85** [comment]
I found the problem you pointed out Thank you so much!!
(Even if the user uses API incorrectly, the infinite loop is too harsh😭)
