### ISSUE TITLE
A crash is inevitable. Suspicion and retry have something to do with it.

### ISSUE THREAD

**Issue by yangwuan55** [ReactiveX/RxJava#7502]
rxjava 3.0.6
The following code is bound to have a crash, although it looks like it should go to onError.
```

            Flowable
            .just("")
            .repeat(5)
            .flatMap { singleIpHostAddress ->
                Flowable.create(FlowableOnSubscribe<String> { o ->
                    throw RuntimeException("test exception")
                    if (!o.isCancelled) {
                        o.onNext("")
                        o.onComplete()
                    }
                }, BackpressureStrategy.BUFFER)
                    .subscribeOn(Schedulers.io())
                    .retry(50)
            }
            .subscribe({
                println("onSuccess")
            },{
                println("onError")
            })

```

crash info：
```

io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.RuntimeException: test exception
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryAddThrowableOrReport(AtomicThrowable.java:52)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:565)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:637)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.onError(FlowableRetryPredicate.java:84)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onError(FlowableSubscribeOn.java:102)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BaseEmitter.errorDownstream(FlowableCreate.java:299)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:539)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.signalError(FlowableCreate.java:489)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:277)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:74)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15696)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: test exception
	at com.beem.rtc.common.TrueTimeTest.utcTime$lambda-1$lambda-0(TrueTimeTest.kt:28)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	... 10 more

```

**Comment by akarnokd** [comment]
What happens is you run 1-5 failing inner sources concurrently of which only one can be reported as error by `flatMap`, the rest will be directed to the global error handler.

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

**Comment by yangwuan55** [comment]
```
Flowable.just("")
                .repeat(5)
                .flatMap { singleIpHostAddress ->
                    Flowable.create(FlowableOnSubscribe<String> { o ->
                        try {
                            throw RuntimeException("test exception")
                            if (!o.isCancelled) {
                                o.onNext("")
                                o.onComplete()
                            }
                        } catch (e: IOException) {
                            if (!o.isCancelled) {
                                o.onError(e)
                            }
                        }
                    },BackpressureStrategy.BUFFER)
                        .retry(50)
                        .doOnError { e ->
                            println("onError 0")
                        }
                        .subscribeOn(Schedulers.computation())
                }
                .toList()
                .subscribe({
                    println("onSuccess")
                },{
                    println("onError")
                })

```

I changed the replay code so it might be a little clearer. I caught the error and checked in the catch block to see if the emitter was canceled, but the error still exists. This result is not in line with expectations, and the developer would have thought that by adding this judgment the error would not occur, but in fact the error occurs within rxjava.

**Comment by yangwuan55** [comment]
Also, if I don't ```retry```, the error won't happen, so hopefully that helped.

**Comment by akarnokd** [comment]
The errors are inherently racing with each other and checking for `isCancelled` is not good enough to ensure only one error is signaled. You have to install a global error handler and ignore the excess exceptions.

Alternatively, materialize the inner source and dematerialize after the flatMap.
```kotlin
Flowable.just("")
.repeat(5)
.flatMap { singleIpHostAddress ->
    Flowable.create(FlowableOnSubscribe<String> { o ->
        try {
            throw RuntimeException("test exception")
            if (!o.isCancelled) {
                o.onNext("")
                o.onComplete()
            }
        } catch (e: IOException) {
            if (!o.isCancelled) {
                o.onError(e)
            }
        }
    },BackpressureStrategy.BUFFER)
        .retry(50)
        .doOnError { e ->
            println("onError 0")
        }
        .subscribeOn(Schedulers.computation())
        .materialize()
}
.dematerialize { it }
.toList()
.subscribe({
    println("onSuccess")
},{
    println("onError")
})
```

**Comment by yangwuan55** [comment]
> The errors are inherently racing with each other and checking for `isCancelled` is not good enough to ensure only one error is signaled. You have to install a global error handler and ignore the excess exceptions.
> 
> Alternatively, materialize the inner source and dematerialize after the flatMap.
> 
> ```kotlin
> Flowable.just("")
> .repeat(5)
> .flatMap { singleIpHostAddress ->
>     Flowable.create(FlowableOnSubscribe<String> { o ->
>         try {
>             throw RuntimeException("test exception")
>             if (!o.isCancelled) {
>                 o.onNext("")
>                 o.onComplete()
>             }
>         } catch (e: IOException) {
>             if (!o.isCancelled) {
>                 o.onError(e)
>             }
>         }
>     },BackpressureStrategy.BUFFER)
>         .retry(50)
>         .doOnError { e ->
>             println("onError 0")
>         }
>         .subscribeOn(Schedulers.computation())
>         .materialize()
> }
> .dematerialize { it }
> .toList()
> .subscribe({
>     println("onSuccess")
> },{
>     println("onError")
> })
> ```

The global error handler can solve this problem, but one problem is that you can only set one Global error handler and it may be overwritten.
I've figured out why this problem occurs, but I think the current way it's handled is confusing for developers, and probably everyone who encounters this kind of error needs to search the Internet, or go to github and ask if there's better guidance or apis to avoid this confusion. I think it's normal for developers to find it reliable to judge isCanceled.

**Comment by akarnokd** [comment]
> Global error handler and it may be overwritten

Coordinate with other developers of your application so this doesn't happen.

> I think it's normal for developers to find it reliable to judge isCanceled.

This is not possible when cancellation can happen asynchronously. Finding `isCancelled` `false` is no guarantee a few nanoseconds later it would return `true`.

**Comment by yangwuan55** [comment]
Could you describe the situation in a more general language? So far, it looks like I can have a good chance when it comes to retry and asynchronously. I've used rxjava for years, but haven't used retry much, and I'm worried that there will be other scenarios that have similar problems.

**Comment by akarnokd** [comment]
> Could you describe the situation in a more general language?

Not sure how to explain it better for you.

With that retry, you are forcing the race condition. The underlying decision to make is what to do with the possible 5 exceptions that can happen concurrently given that only one exception is ever allowed to reach the `subscribe`?
