### ISSUE TITLE
UndeliverableException when use zip compose 2 observable , send Exceptions at same time in the two Observable 。

### ISSUE THREAD

**Issue by maoqis** [ReactiveX/RxJava#7618]
Question:
![image](https://github.com/ReactiveX/RxJava/assets/3467849/4f1dba56-cdc8-4841-a92c-78cf90cbe5a7)

1.  why not " E " level  log in logcat？ the level is “ W ” for UndeliverableException。
2.  but system show a dialog to show the stack of method   ，app process is be killed when i cancle the dialog。is the the UndeliverableException not be try catch  and after  "E  FATAL EXCEPTION"?

Version:
implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
implementation 'io.reactivex.rxjava3:rxjava:3.0.8'

For example : https://github.com/maoqis/AndroidExperienceCase/blob/master/app/src/main/java/com/maoqis/testcase/RxZipErrorFragment.java

```
            Observable first = Observable.create(e -> {
                System.out.println("first");
                throw new Exception("first exception");
            }).subscribeOn(Schedulers.io());

            Observable second = Observable.create(e -> {
                System.out.println("second");
                throw new Exception("second exception");
            }).subscribeOn(Schedulers.io());


            List<Observable<?>> observableList = new ArrayList<>();
            observableList.add(first);
            observableList.add(second);

            Observable.zip(observableList, objects -> "result")
                    .subscribeOn(Schedulers.io())
                    .subscribe(t -> {
                        System.out.println("result");
                    }, e -> {
                        Log.w(TAG, "Observable zip: try catch 1");
                    });
```

Logcat :

```
15:13:49.105  I  first
15:13:49.106  I  second
15:13:49.106  W  Observable zip: try catch 1
15:13:49.107  W  io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.Exception: second exception
15:13:49.108  W  	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
15:13:49.108  W  	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
15:13:49.109  W  	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:43)
15:13:49.109  W  	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
15:13:49.109  W  	at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
15:13:49.109  W  	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
15:13:49.110  W  	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
15:13:49.110  W  	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
15:13:49.111  W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:13:49.111  W  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
15:13:49.111  W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
15:13:49.111  W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
15:13:49.111  W  	at java.lang.Thread.run(Thread.java:764)
15:13:49.112  W  Caused by: java.lang.Exception: second exception
15:13:49.112  W  	at com.maoqis.testcase.RxZipErrorFragment.lambda$null$2(RxZipErrorFragment.java:64)
15:13:49.112  W  	at com.maoqis.testcase.-$$Lambda$RxZipErrorFragment$d0gZw506znokShgrSfoRIiWhEH8.subscribe(Unknown Source:0)
15:13:49.113  W  	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
15:13:49.113  W  	... 10 more
15:13:50.197  I  ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000

// 这个地方比较奇怪，为什么系统会弹窗？ 没发现E级别日志。弹窗打印的也是一样的日志，UndeliverableException
/ /此时弹出了异常信息弹窗，内容同上，但是没有 E级别日志。
//点击取消，系统发出信号9. 
---------------------------- PROCESS ENDED (4773) for package com.maoqis.testcase ----------------------------
15:13:57.965  I  Process 4773 exited due to signal (9)
```

**Comment by maoqis** [comment]
i found it , why the level is " W "  and system receive it and send signal 9 to kill app。
 
![image](https://github.com/ReactiveX/RxJava/assets/3467849/6760c485-7716-4ca6-98bf-9ce15ff9b288)

![image](https://github.com/ReactiveX/RxJava/assets/3467849/1eb21117-3b45-49e6-9d27-b59ce494d4a4)


but app is killed。

**Comment by akarnokd** [comment]
Please read the section the error links to and act accordingly:

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

**Comment by maoqis** [comment]
I got it ， the android platform maybe kille app 。

make sure the 2 Exception be handled in the two Observalbe before zip
