### ISSUE TITLE
2.x: Infinity loop on subscription cancel

### ISSUE THREAD

**Issue by gustavomahlow** [ReactiveX/RxJava#7620]
We're facing an infinity loop in our application.

We have a GraphQL application that uses RxJava to handle subscription notifications. Every event received via Kafka is emitted to a flowable.

The same flowable is used for the same type of subscription (GraphQL subscription). Depending on the information, we apply some filters to the `Flowable`.

Every time a stop command is received via subscription (GraphQL subscription) or the Websocket channel is closed, the subscriber is cancelled.

Our observer is instantiated this way:

```
ConnectableObservable<T> connectableObservable =
        Observable.create(this::attachListener).share().publish();
connectableObservable.connect();

return connectableObservable.toFlowable(BackpressureStrategy.BUFFER);
```

Our CPU usage is reaching 100% after a couple of hours running the application. We did some troubleshooting and realized that the problem was an infinity loop while closing the subscription. Here is the stack trace obtained via jstack:

```
at io.reactivex.internal.queue.SpscLinkedArrayQueue.clear(SpscLinkedArrayQueue.java:186)
at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.cancel(FlowableOnBackpressureBuffer.java:154)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:181)
at io.reactivex.internal.subscribers.StrictSubscriber.cancel(StrictSubscriber.java:77)
at graphql.execution.reactive.DelegatingSubscription.cancel(DelegatingSubscription.java:26)
at graphql.kickstart.execution.subscriptions.SessionSubscriptions.cancel(SessionSubscriptions.java:37)
at graphql.kickstart.execution.subscriptions.DefaultSubscriptionSession.unsubscribe(DefaultSubscriptionSession.java:47)
at graphql.kickstart.execution.subscriptions.apollo.SubscriptionStopCommand.apply(SubscriptionStopCommand.java:15)
at graphql.kickstart.execution.subscriptions.apollo.ApolloSubscriptionConsumer.accept(ApolloSubscriptionConsumer.java:25)
at graphql.kickstart.execution.subscriptions.apollo.ApolloSubscriptionConsumer.accept(ApolloSubscriptionConsumer.java:11)
at graphql.kickstart.servlet.GraphQLWebsocketServlet$1.onMessage(GraphQLWebsocketServlet.java:146)
at graphql.kickstart.servlet.GraphQLWebsocketServlet$1.onMessage(GraphQLWebsocketServlet.java:142)
at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415)
at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:156)
at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
- locked <0x00000006cfc00110> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@13.0.2/ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@13.0.2/ThreadPoolExecutor.java:628)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(java.base@13.0.2/Thread.java:830)
```

I confess that I'm new to RxJava, and because of that, I don't understand every core concept of the library. Maybe we are doing something wrong. I really don't know if the problem is caused by the library.

We are using version 2.2.21.

Thanks in advance guys.

**Comment by gustavomahlow** [comment]
Another stack trace obtained via jstack:

```
   java.lang.Thread.State: RUNNABLE
	at io.reactivex.internal.queue.SpscLinkedArrayQueue.lvElement(SpscLinkedArrayQueue.java:251)
	at io.reactivex.internal.queue.SpscLinkedArrayQueue.poll(SpscLinkedArrayQueue.java:138)
	at io.reactivex.internal.queue.SpscLinkedArrayQueue.clear(SpscLinkedArrayQueue.java:186)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.cancel(FlowableOnBackpressureBuffer.java:154)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:181)
	at io.reactivex.internal.subscribers.StrictSubscriber.cancel(StrictSubscriber.java:77)
	at graphql.execution.reactive.DelegatingSubscription.cancel(DelegatingSubscription.java:26)
	at graphql.kickstart.execution.subscriptions.SessionSubscriptions.cancel(SessionSubscriptions.java:37)
	at graphql.kickstart.execution.subscriptions.DefaultSubscriptionSession.unsubscribe(DefaultSubscriptionSession.java:47)
	at graphql.kickstart.execution.subscriptions.apollo.SubscriptionStopCommand.apply(SubscriptionStopCommand.java:15)
	at graphql.kickstart.execution.subscriptions.apollo.ApolloSubscriptionConsumer.accept(ApolloSubscriptionConsumer.java:25)
	at graphql.kickstart.execution.subscriptions.apollo.ApolloSubscriptionConsumer.accept(ApolloSubscriptionConsumer.java:11)
	at graphql.kickstart.servlet.GraphQLWebsocketServlet$1.onMessage(GraphQLWebsocketServlet.java:146)
	at graphql.kickstart.servlet.GraphQLWebsocketServlet$1.onMessage(GraphQLWebsocketServlet.java:142)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415)
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:156)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x00000006c8a00140> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@13.0.2/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@13.0.2/ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(java.base@13.0.2/Thread.java:830)
```

It seems that `poll()` call is always returning a value different than null.

**Comment by akarnokd** [comment]
An infinite loop in `clear` usually indicates some part of the flow called an `onNext` concurrently at some point, which is not allowed.

Anything non-standard is your `attachListener` so if whatever drives the the emitter in there gets called concurrently, you'll get a corrupted queue.

**Comment by gustavomahlow** [comment]
The serialized observer can resolve this issue for me? Or I have to synchronize onNext call by myself?
The way we implemented, onNext call be called concurrently.

The attach listener call, wraps a ApplicationListener from spring (A listener that receives application events that happened)(It can be asynchronous) and make it call onNext every time a new evened is received.

**Comment by akarnokd** [comment]
-> https://reactivex.io/RxJava/2.x/javadoc/io/reactivex/ObservableEmitter.html

```java
Observable.create(emitter -> {
   ObservableEmitter<T> serializedEmitter = emitter.serialize();

  someApi.addListener(data -> {
       serializedEmitter.onNext(data);
  });
});

**Comment by gustavomahlow** [comment]
Just to confirm. A concrete example:

```
        ConnectableObservable<T> connectableObservable =
                Observable.create(emitter -> {
                    ObservableEmitter<T> serializedEmitter = emitter.serialize();
                    
                    configurableApplicationContext.addApplicationListener(event -> serializedEmitter::onNext);
                }).share().publish();
        connectableObservable.connect();

        return connectableObservable.toFlowable(BackpressureStrategy.BUFFER);
```

My observer should call serialize as well?

```
        ConnectableObservable<T> connectableObservable =
                Observable.create(emitter -> {
                    ObservableEmitter<T> serializedEmitter = emitter.serialize();
                    
                    configurableApplicationContext.addApplicationListener(event -> serializedEmitter::onNext);
                }).serialize().share().publish();
        connectableObservable.connect();

        return connectableObservable.toFlowable(BackpressureStrategy.BUFFER);
```

Thanks a lot for your help!

**Comment by akarnokd** [comment]
No need to call `serialize()` after `create`.
